/*
    This file is part of Go.dot — https://github.com/pob31/go.dot

    Copyright (C) 2026 Pierre-Olivier Boulant

    Go.dot is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later
    version. Go.dot is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
    (LICENSE, at the repository root) for more details.

    SPDX-License-Identifier: GPL-3.0-or-later
*/

#pragma once

/*
    The bundle's grammar, as RELAX NG, generated from the same table everything
    else comes from.

    WHY GENERATE IT AT ALL, when ShowDocument::validate() already checks a
    document against the schema. Because that check and the schema are the same
    code: it can prove the engine is self-consistent and nothing more. A
    grammar in a standard language, checked by somebody else's validator
    (lxml, in scripts/validate-show.py), is an OUTSIDE opinion - it catches the
    case where our reader is wrong in the same direction as our writer, which is
    exactly the failure a self-check cannot see.

    It also gives everyone else a way in. A show file is XML with a published
    grammar, so an editor can complete it, a build can gate on it, and someone
    writing a tool against Go.dot does not have to read our C++ to learn what a
    Cue may carry.

    THE COMMITTED FILE IS THE CONTRACT. docs/schema/show.rng is generated by
    `wfg schema` and committed, and a test fails when the two disagree - the
    same arrangement as the generated schema header and CLAUDE.md, for the same
    reason: two things that must agree need something that checks they do.

    ONE GRAMMAR, THREE ROOTS. `start` is a choice of Show, State and Bundle, so
    a single file validates every XML file a bundle contains. Show comes from
    the parameter table (the `persist=show` rows); State likewise (the
    `persist=state` rows); Bundle is the manifest and carries a version and
    nothing else.
*/

#include <string>

namespace wfg::doc
{
    namespace RelaxNg
    {
        /*  The grammar for a bundle, ending in a newline.

            Deterministic: elements in the schema's own order, attributes sorted
            by name, no timestamp and no generator version. It has to be, or the
            committed copy could not be compared byte for byte. */
        std::string generate();
    }
}
