/*
    This file is part of Go.dot — https://github.com/pob31/go.dot

    Copyright (C) 2026 Pierre-Olivier Boulant

    Go.dot is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later
    version. Go.dot is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
    (LICENSE, at the repository root) for more details.

    SPDX-License-Identifier: GPL-3.0-or-later
*/

#pragma once

/*
    GENERATED FILE — do not edit.

    Written by scripts/generate-schema.py from
    docs/parameters/godot-parameters.csv. To change anything here, change a
    row in that file and run the generator; the test `schema.generated` fails
    if the two disagree, so a hand edit here does not survive CI.

    It is committed rather than generated at build time so that a clone with
    no Python still builds.
*/

#include <wfg/engine/document/SchemaTypes.h>

namespace wfg::doc::generated
{
    inline constexpr std::string_view enum_engine_clock[] = { "dummy", "device" };
    inline constexpr std::string_view enum_cue_kind[] = { "memo", "group" };
    inline constexpr std::string_view enum_group_mode[] = { "timeline", "sequence" };
    inline constexpr std::string_view enum_group_advance[] = { "auto", "manual" };
    inline constexpr std::string_view enum_mount_transport[] = { "udp", "tcp", "ws" };
    inline constexpr std::string_view enum_mount_panic[] = { "park", "snap" };
    inline constexpr std::string_view enum_audio_status[] = { "stopped", "running", "noClock" };

    inline constexpr AttributeRow attributes[] =
    {
        { "engine", "product",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "Go.dot",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The product name." },
        { "engine", "version",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The running build's version." },
        { "engine", "tick",
          ValueType::integer64, 'h', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "tick", 5.0, false, "park",
          "The current tick index." },
        { "engine", "sampleRate",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "Hz", 1.0, false, "park",
          "The clock's sample rate. Observed from the device from Phase 2; not a setting." },
        { "engine", "blockSize",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 1.0, false, "park",
          "The audio block size the clock is being advanced by." },
        { "engine", "samplesPerTick",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 1.0, false, "park",
          "Samples per 50 Hz tick; the sample rate divided by 50." },
        { "engine", "lateness",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 5.0, false, "park",
          "How late the last tick was processed, in samples." },
        { "engine", "latenessMax",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 5.0, false, "park",
          "The worst lateness since the engine started." },
        { "engine", "clock",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "dummy",
          false, 0.0, false, 0.0,
          enum_engine_clock, 2,
          "", 1.0, false, "park",
          "Which clock is advancing the sample counter." },
        { "engine", "errorCount",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "Commands rejected since the engine started." },
        { "engine", "rtViolations",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "Allocations Go.dot's own code made on the audio thread since the engine started. Zero is the only acceptable value: PRD 4.2 forbids allocation there, and an allocation is a lock inside the allocator taken while a block is due. Reads zero in a build configured without the real-time checks, where nobody is looking." },
        { "engine", "rtForeignAllocations",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "Allocations Tracktion made inside the audio callback since the engine started, counted separately and never hidden. Tracktion takes a shared lock every block by design; this is a measured fact about a dependency, not a defect in it." },
        { "engine", "lastError",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "The most recent rejection: tick, sequence, origin, reason and command. The only way an OSC client can learn that its write was refused." },
        { "document", "path",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The open bundle's folder." },
        { "document", "name",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The open bundle's name." },
        { "document", "formatVersion",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "1",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The show format this document was written against." },
        { "document", "dirty",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::none,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "Whether there are unsaved changes." },
        { "list", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue list's name." },
        { "list", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifiers of the list's top-level children, in order, space-separated." },
        { "list", "standby",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::state,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue GO will act on. One per list, and always one of that list's own top-level children or empty; moved only by a standby command, a write to this node, or the repair when the cue it names is deleted or moved away. Never by selection or scrolling." },
        { "cue", "kind",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "memo",
          false, 0.0, false, 0.0,
          enum_cue_kind, 2,
          "", 50.0, false, "park",
          "What kind of cue this is, derived from the element rather than stored: a Group is a group. Phase 1 has memo (a cue with no output) and group." },
        { "cue", "number",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The decimal cue number. A string, because 12.5.1 is one; mutable, renumbered during tech, and never an identity." },
        { "cue", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue's name, as the operator reads it." },
        { "cue", "notes",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Free text for the designer." },
        { "cue", "enabled",
          ValueType::boolean, 'T', false, Access::readWrite, Kind::state, Persist::show,
          true, "true",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Whether the cue runs at all. A disabled cue is skipped, not deleted." },
        { "cue", "colour",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "A #RRGGBB decoration. Never the sole carrier of information." },
        { "cue", "preWait",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How long after entry before this cue starts. A group has one of its own, and it runs before its members begin their own pre-waits, so raising it defers the whole group." },
        { "cue", "postWait",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How long after completion before this cue reports done to its parent. A group is complete once every member is, its members' own post-waits included; the group's post-wait then runs on top of that." },
        { "cue", "parent",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifier of the containing list or group." },
        { "cue", "index",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Position among siblings, zero-based." },
        { "group", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifiers of the group's children, in order, space-separated." },
        { "group", "mode",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "sequence",
          false, 0.0, false, 0.0,
          enum_group_mode, 2,
          "", 50.0, false, "park",
          "Whether members are scheduled at entry or run one after another." },
        { "group", "advance",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "manual",
          false, 0.0, false, 0.0,
          enum_group_advance, 2,
          "", 50.0, false, "park",
          "Whether a member starts when the previous completes or on GO." },
        { "mount", "prefix",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The address the foreign namespace is mounted at." },
        { "mount", "transport",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "udp",
          false, 0.0, false, 0.0,
          enum_mount_transport, 3,
          "", 1.0, false, "park",
          "How the mounted target is reached. Declared now; used from Phase 2." },
        { "mount", "namespace",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The bundle-relative OSCQuery namespace file describing the target." },
        { "mount", "rateCap",
          ValueType::number, 'd', false, Access::read, Kind::state, Persist::show,
          true, "50",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "Hz", 1.0, false, "park",
          "Default outbound rate cap for the mounted nodes." },
        { "mount", "anticipatable",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::show,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "Whether the mounted nodes may be pre-sent before GO. False for third parties." },
        { "mount", "panic",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "park",
          false, 0.0, false, 0.0,
          enum_mount_panic, 2,
          "", 1.0, false, "park",
          "Default resting state for the mounted nodes." },
        { "mount", "loaded",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::none,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "Whether the namespace file has been read." },
        { "mount", "nodeCount",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "How many nodes the mount contributed." },
        { "audio", "tracks",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          false, "",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The fixed number of audio tracks, and so the polyphony ceiling: N tracks is N simultaneous cues. Zero is legal and means a show with no audio. Required, and deliberately without a default - the number is a decision about the shape of a show, and no value here could be right for every rig." },
        { "audio", "device",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The audio device the engine has open, or empty when there is none." },
        { "audio", "outputs",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "How many hardware output channels are available to route to. A cue wider than this is refused when the show loads." },
        { "audio", "status",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "stopped",
          false, 0.0, false, 0.0,
          enum_audio_status, 3,
          "", 5.0, false, "park",
          "Whether audio is running. An unlocked device is present and producing nothing, which is a different failure from no device at all and wants a different remedy." },
        { "bus", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The bus name as the designer wrote it. Names are what appear in a dropdown and on a scribble strip; channel numbers are not." },
        { "bus", "firstChannel",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The first hardware output channel this bus occupies, counting from zero." },
        { "bus", "width",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "1",
          true, 1.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "How many consecutive channels the bus occupies. Explicit and never inferred: the engine will not quietly widen or narrow a cue to make it fit." },
    };
}
