/*
    This file is part of Go.dot — https://github.com/pob31/go.dot

    Copyright (C) 2026 Pierre-Olivier Boulant

    Go.dot is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later
    version. Go.dot is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
    (LICENSE, at the repository root) for more details.

    SPDX-License-Identifier: GPL-3.0-or-later
*/

#pragma once

/*
    GENERATED FILE — do not edit.

    Written by scripts/generate-schema.py from
    docs/parameters/godot-parameters.csv. To change anything here, change a
    row in that file and run the generator; the test `schema.generated` fails
    if the two disagree, so a hand edit here does not survive CI.

    It is committed rather than generated at build time so that a clone with
    no Python still builds.
*/

#include <wfg/engine/document/SchemaTypes.h>

namespace wfg::doc::generated
{
    inline constexpr std::string_view enum_engine_clock[] = { "dummy", "device" };
    inline constexpr std::string_view enum_cue_kind[] = { "memo", "group", "media", "fade", "stop", "osc" };
    inline constexpr std::string_view enum_fade_curve[] = { "linear", "sCurve" };
    inline constexpr std::string_view enum_stop_verb[] = { "hard", "fade", "afterMember", "afterIteration" };
    inline constexpr std::string_view enum_stop_curve[] = { "linear", "sCurve" };
    inline constexpr std::string_view enum_osc_wait[] = { "none", "sent", "verified" };
    inline constexpr std::string_view enum_run_kind[] = { "memo", "group", "media", "fade", "stop", "osc" };
    inline constexpr std::string_view enum_run_state[] = { "waiting", "armed", "playing", "stopping", "postWait", "done", "failed" };
    inline constexpr std::string_view enum_group_mode[] = { "timeline", "sequence" };
    inline constexpr std::string_view enum_group_advance[] = { "auto", "manual" };
    inline constexpr std::string_view enum_group_selection[] = { "sequential", "shuffle" };
    inline constexpr std::string_view enum_mount_transport[] = { "udp", "tcp", "ws" };
    inline constexpr std::string_view enum_mount_panic[] = { "park", "snap" };
    inline constexpr std::string_view enum_mount_readback[] = { "none", "oscquery" };
    inline constexpr std::string_view enum_audio_status[] = { "stopped", "running", "noClock" };

    inline constexpr AttributeRow attributes[] =
    {
        { "engine", "product",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "Go.dot",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The product name." },
        { "engine", "version",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The running build's version." },
        { "engine", "tick",
          ValueType::integer64, 'h', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "tick", 5.0, false, "park",
          "The current tick index." },
        { "engine", "sampleRate",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "Hz", 1.0, false, "park",
          "The clock's sample rate. Observed from the device from Phase 2; not a setting." },
        { "engine", "blockSize",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 1.0, false, "park",
          "The audio block size the clock is being advanced by." },
        { "engine", "samplesPerTick",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 1.0, false, "park",
          "Samples per 50 Hz tick; the sample rate divided by 50." },
        { "engine", "lateness",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 5.0, false, "park",
          "How late the last tick was processed, in samples." },
        { "engine", "latenessMax",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 5.0, false, "park",
          "The worst lateness since the engine started." },
        { "engine", "clock",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "dummy",
          false, 0.0, false, 0.0,
          enum_engine_clock, 2,
          "", 1.0, false, "park",
          "Which clock is advancing the sample counter." },
        { "engine", "errorCount",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "Commands rejected since the engine started." },
        { "engine", "rtViolations",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "Allocations Go.dot's own code made on the audio thread since the engine started. Zero is the only acceptable value: PRD 4.2 forbids allocation there, and an allocation is a lock inside the allocator taken while a block is due. Reads zero in a build configured without the real-time checks, where nobody is looking." },
        { "engine", "rtForeignAllocations",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "Allocations Tracktion made inside the audio callback since the engine started, counted separately and never hidden. Tracktion takes a shared lock every block by design; this is a measured fact about a dependency, not a defect in it." },
        { "engine", "launchLatencyTicks",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "How many ticks pass between a GO being applied and the sound starting. It is not a preference: it is one tick plus however many the audio block spans, which is the smallest delay that guarantees the launch is never placed in the past and so never back-dated. Published because a designer timing a cue against light needs the number rather than a feeling about it." },
        { "engine", "sequenceGapTicks",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "How many ticks pass between one member of an automatic sequence ending and the next one sounding. Two, plus the launch latency: a member reports it has ended during one tick, the scheduler sees that on the next and asks for the next member, and the launch is placed on the one after. It is the price of every decision being a logged command rather than something a hook quietly does - which is what lets a whole show replay - and it is published for the same reason the launch latency is: a designer timing a chain against light needs the number rather than a feeling about it. A sample-accurate join is what ranges are for (PRD 3.24); a sequence group is discrete cues relaunched." },
        { "engine", "lastError",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "The most recent rejection: tick, sequence, origin, reason and command. The only way an OSC client can learn that its write was refused." },
        { "document", "path",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The open bundle's folder." },
        { "document", "name",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The open bundle's name." },
        { "document", "formatVersion",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "1",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The show format this document was written against." },
        { "document", "dirty",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::none,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "Whether there are unsaved changes." },
        { "lists", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifiers of the show's cue lists, in order, space-separated. The roster of what can be run at once: PRD 3.5 has several lists live together, each with a standby of its own, so that a timecode- or OSC-triggered chain can never move the operator's position." },
        { "lists", "focus",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::state,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Which list GO acts on. Exactly one, and exclusive by construction rather than by upkeep - it is one value, so there is no flag anywhere to leave set. A list that has gone takes the focus with it and the first remaining list has it instead, which is why nothing has to remember to move this when a list is deleted. It is remembered across a save for the same reason the standby is: a rehearsal reopened where it was left is the kinder default, and losing state.xml costs only where somebody had got to." },
        { "list", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue list's name." },
        { "list", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifiers of the list's top-level children, in order, space-separated." },
        { "list", "standby",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::state,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue GO will act on. One per list, and always one of that list's own top-level children or empty; moved only by a standby command, a write to this node, or the repair when the cue it names is deleted or moved away. Never by selection or scrolling." },
        { "cue", "kind",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "memo",
          false, 0.0, false, 0.0,
          enum_cue_kind, 6,
          "", 50.0, false, "park",
          "What kind of cue this is, derived from the element rather than stored: a Group is a group and a Media is media. Deriving it is what stops a client turning one kind into another by writing a word, and what lets the grammar refuse a file attribute on a cue that plays nothing." },
        { "cue", "number",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The decimal cue number. A string, because 12.5.1 is one; mutable, renumbered during tech, and never an identity." },
        { "cue", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue's name, as the operator reads it." },
        { "cue", "notes",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Free text for the designer." },
        { "cue", "enabled",
          ValueType::boolean, 'T', false, Access::readWrite, Kind::state, Persist::show,
          true, "true",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Whether the cue runs at all. A disabled cue is skipped, not deleted." },
        { "cue", "colour",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "A #RRGGBB decoration. Never the sole carrier of information." },
        { "cue", "preWait",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How long after entry before this cue starts. A group has one of its own, and it runs before its members begin their own pre-waits, so raising it defers the whole group." },
        { "cue", "postWait",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How long after completion before this cue reports done to its parent. A group is complete once every member is, its members' own post-waits included; the group's post-wait then runs on top of that." },
        { "cue", "parent",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifier of the containing list or group." },
        { "cue", "index",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Position among siblings, zero-based." },
        { "media", "file",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The media to play, as a path relative to the bundle's media/ folder. Relative because a show travels between machines and an absolute path is a fact about the machine it was authored on. A file that is missing is reported when the show loads and fails the cue when it is armed - it never fails the load, because a show with one missing sound is still a show somebody has to run tonight." },
        { "media", "level",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, -120.0, true, 12.0,
          nullptr, 0,
          "dB", 50.0, false, "park",
          "The level the cue plays at, as decided. Not what it is doing: a fade writes run/<id>/level and leaves this alone, so the document keeps saying what somebody chose while the run says what is happening. -120 dB is silence rather than a very small number." },
        { "media", "startOffset",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How far into the file playback begins. A cue that starts at the downbeat rather than at the top of the recording." },
        { "route", "bus",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifier of the bus this destination feeds. A destination names a bus and never a hardware channel: the bus is where the author said a channel exists, and a show moved to a different rig re-points buses rather than every cue." },
        { "route", "gains",
          ValueType::number, 'd', true, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The coefficients from the cue's channels to the bus's, row by row: input 0 to every bus channel, then input 1, and so on. Its length is the cue's channel count times the bus width, and a length that does not match is refused when the show loads rather than discovered mid-cue. A coefficient is a plain multiplier and carries no dB - level is the cue's, and this is where it goes." },
        { "fade", "target",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue whose sound this fade moves. It targets the CUE and finds its live run when it fires, because a cue is what somebody wrote down and a run is what happens to be playing - and the show has to say the first without knowing the second." },
        { "fade", "level",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "-120",
          true, -120.0, true, 12.0,
          nullptr, 0,
          "dB", 50.0, false, "park",
          "Where the fade ends, in dB. -120 is silence rather than a very small number, and it is the default because a fade to silence is what most fades are - a fresh fade cue is a slow cut to nothing, which is a real thing to want and can only ever make the show quieter." },
        { "fade", "duration",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How long it takes. Zero is a jump, and it is the default so that a fade nobody has finished writing does something obvious rather than something slow and mysterious." },
        { "fade", "curve",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "linear",
          false, 0.0, false, 0.0,
          enum_fade_curve, 2,
          "", 50.0, false, "park",
          "The shape it takes between the two levels. Linear in the dB domain, which is what a fader feels like; sCurve eases out of the start and into the end, for a fade that should not announce itself. Two shapes until the curve editor of Phase 5." },
        { "stop", "target",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue this stops. As with a fade it names the cue and finds the run, and a target that is not running is a no-op that is applied rather than refused." },
        { "stop", "verb",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "hard",
          false, 0.0, false, 0.0,
          enum_stop_verb, 4,
          "", 50.0, false, "park",
          "How it stops. Hard stops now and takes Tracktion's own click suppression with it; fade runs a fade to silence first and stops when it arrives. The verb is separate from the duration so that a stop with a duration nobody meant cannot become a slow one by accident. afterMember and afterIteration are the two GRACEFUL ones, and they are only meaningful against a group: they let the scene reach a boundary it was going to reach anyway - the end of the member playing now, or the end of this round - and stop there, which is how an infinite loop is left without a cut. Against anything else they are a hard stop, because there is no boundary to wait for." },
        { "stop", "duration",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How long the fade half takes, when the verb is fade. Ignored by a hard stop." },
        { "stop", "curve",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "linear",
          false, 0.0, false, 0.0,
          enum_stop_curve, 2,
          "", 50.0, false, "park",
          "The shape of that fade. Ignored by a hard stop." },
        { "osc", "address",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The node this cue writes, which is an address in a mounted namespace rather than a message somebody composed. Naming the NODE is what lets the tree check it: a cue pointing at something the target does not have is findable before the show rather than during it, and the node already says what type it takes." },
        { "osc", "value",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "What to write, spelled the way the log spells an argument - f:0.5 for a float, i:3 for an integer, T for true. One atom, because a mounted node holds one value; the type is in the text so that a cue meaning the float and a cue meaning the integer are different cues rather than the same cue read twice by two machines." },
        { "osc", "wait",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "none",
          false, 0.0, false, 0.0,
          enum_osc_wait, 3,
          "", 50.0, false, "park",
          "How long the cue takes to be done. None finishes as soon as it is fired; sent finishes when the datagram has left the socket; verified finishes when the target has been asked and has answered with the value that was written. A sequence of verified cues is a chain that waits for each device instead of hoping (PRD 3.11), and it is the only one of the three that can tell you the device disagreed." },
        { "osc", "timeout",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "5",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How long verified waits for an answer before failing the run. Ignored by the other two waits. Five seconds because it is long enough for a device that is thinking and short enough that a cue which is never going to answer does not hold a show past the point anybody would have given up on it. Zero means the first reply or nothing." },
        { "runs", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifiers of the runs the engine is publishing, in the order they were created. A finished run keeps its place here for five seconds and is then dropped - Gogo is the present tense (PRD 7), and a four-hour show would otherwise publish four hours of finished runs on every tick." },
        { "run", "cue",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue this run instantiates. A run is the live instance and the cue is what somebody wrote: the cue keeps saying what was decided while the run says what is happening (PRD 4.10)." },
        { "run", "kind",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          enum_run_kind, 6,
          "", 50.0, false, "park",
          "The kind of the cue this run instantiates, copied at launch so a client reading a run does not have to go and look the cue up - and so the answer survives the cue being edited underneath it." },
        { "run", "parent",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The group run this one is a member of, or empty at the top of a list. Runs and not cues, because the same cue can be a member of a group that is running twice - a shuffled loop plays it in round three and again in round five - and which one finished has to have an answer." },
        { "run", "children",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The runs this group run is organising, in the order they were spawned, space-separated. A group owns time, order and lifetime and no output of its own (PRD 4.12), so this is the whole of what it holds." },
        { "run", "state",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "armed",
          false, 0.0, false, 0.0,
          enum_run_state, 7,
          "", 50.0, false, "park",
          "Where the run is. Waiting means its pre-wait is running and nothing has fired yet; armed means its track is held and its media is being made ready; playing means the launch has been placed; stopping means a stop was asked for and has not landed; postWait means its own work is over and it is holding before it reports done to whatever is waiting on it; done and failed are both finished, and a failed run says why in error." },
        { "run", "track",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "-1",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The track it plays on, or -1 before one is held and after it is given back. The track count is the polyphony ceiling, so this is also which of those voices it is using. A playing track is never stolen." },
        { "run", "position",
          ValueType::number, 'd', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "How far into the file it has got. A READOUT and never a model input: it is published for a client to watch and is not written to the log, because a log of every position would be a log of the clock rather than of anything anybody decided." },
        { "run", "level",
          ValueType::number, 'd', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, -120.0, true, 12.0,
          nullptr, 0,
          "dB", 50.0, false, "park",
          "The level it is playing at now, which is what a fade writes. Not the cue's authored level - that one stays where the designer left it, so a night of riding faders does not rewrite the show." },
        { "run", "late",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "How many blocks the launch was late by, when GO arrived before the arm had finished. Zero is the ordinary case, and the number is here because it is the difference between GO is instant as a claim and as a measurement." },
        { "run", "iteration",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Which round this group run is on, counting from one. Zero before the first round has been drawn. A client showing 3/8 is showing this and iterations." },
        { "run", "iterations",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "1",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "How many rounds this run will play, copied from the group when it started - so an edit to loops changes the next run and not this one. Zero means for ever." },
        { "run", "round",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cue identifiers of the round in progress, in the order they will play, space-separated. MATERIALISED rather than computed: a shuffled round is drawn once, written into the log, and read back from there on replay - which is what lets a session reproduce without the random number generator ever being consulted again." },
        { "run", "pruned",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The members dropped from this run, space-separated. Pruning is RUN-LOCAL and evaporates with the run (PRD 3.6): it is what an operator does at 22:40 when one of eight ambiences is wrong tonight, and it must not be an edit to the show - tomorrow the cue is back." },
        { "run", "seed",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The seed this run is drawing its rounds from: the group seed when there is one, and a fresh one otherwise. Published because a shuffled night somebody liked is a night worth being able to ask for again." },
        { "run", "error",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "Why it failed, when it did: no-track when every voice was busy, media-missing when the file is not in the bundle, bad-route when the destination cannot be honoured, send-failed when a message could not be put on the wire, and the write refusals - bad-address, read-only, type-mismatch - when a network cue names a node the target does not have or will not take. timeout when a verified cue asked and nothing answered in time, and disagreed when something answered with a different value, which is the one failure that means the device is there and is not doing what it was told. Empty otherwise. A failed run was still an APPLIED command - the request was legal and the show could not honour it, which is a different thing from a request that was malformed." },
        { "group", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The identifiers of the group's children, in order, space-separated." },
        { "group", "headerOrder",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cues in this group's header, in order, space-separated. A header runs before the group's members (PRD 3.6) and is an ordinary cue list, so this is the same kind of answer as order - about a different list." },
        { "group", "footerOrder",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The cues in this group's footer, in order, space-separated. A footer runs at group exit and BLOCKS: the group is not done until its cues are, so a following scene that reallocates the same channels waits for the release rather than racing it." },
        { "group", "mode",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "sequence",
          false, 0.0, false, 0.0,
          enum_group_mode, 2,
          "", 50.0, false, "park",
          "Whether members are scheduled at entry or run one after another." },
        { "group", "advance",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "manual",
          false, 0.0, false, 0.0,
          enum_group_advance, 2,
          "", 50.0, false, "park",
          "Whether a member starts when the previous completes or on GO." },
        { "group", "selection",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "sequential",
          false, 0.0, false, 0.0,
          enum_group_selection, 2,
          "", 50.0, false, "park",
          "How the members of a round are ordered. sequential plays them as they are written; shuffle draws a fresh order for each round, redrawing until the first of the new round differs from the last of the one before it - so a member is never heard twice running across a boundary. With two members that constraint decides the order completely, which is correct rather than a degenerate case: alternating is what a designer asking for two shuffled ambiences means." },
        { "group", "loops",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "1",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "How many ROUNDS this group plays before it is done. Rounds, not playbacks: with play set, a round is a subset of the members, and three loops of two-of-five is six cues rather than three. Zero means for ever, which is what an ambience bed is, and is left by a stop verb, an advance or run.stop rather than by counting." },
        { "group", "play",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "How many members a round plays, out of however many there are (PRD 3.6 play N of M). Zero means all of them, which is the ordinary group. Larger than the membership is the same as all of them rather than a refusal: a designer deleting a member should not have their show stop loading." },
        { "group", "seed",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The seed a shuffled group draws its rounds from. Zero means a fresh one per run, drawn when the run starts and written into its log - so a shuffled show is different every night AND every night reproduces exactly. A seed set here is the other thing somebody wants: the same order at every performance, which is how a shuffled scene gets rehearsed." },
        { "mount", "prefix",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The address the foreign namespace is mounted at." },
        { "mount", "transport",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "udp",
          false, 0.0, false, 0.0,
          enum_mount_transport, 3,
          "", 1.0, false, "park",
          "How the mounted target is reached. Only udp carries messages today; tcp and ws are declared because a document should be able to say what a device is before Go.dot can talk to it, and a mount declaring either is refused when the show loads rather than going quiet during it." },
        { "mount", "host",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "127.0.0.1",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "Where the target is. A literal address rather than a name, because a socket resolves a hostname on every send whose destination differs from the last one, and a blocking lookup on the tick thread is a frame nobody gets back. It defaults to this machine because the ordinary rig is Go.dot and its processors on one box; anything else says so." },
        { "mount", "port",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          false, "",
          true, 1.0, true, 65535.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The port the target listens on. Required, and deliberately without a default for the same reason audio/tracks is: no number could be right for every device, and a mount that guessed would send into the dark and report success. UDP never tells you nobody was listening, so this one has to be right in the document or it is never right at all." },
        { "mount", "namespace",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The bundle-relative OSCQuery namespace file describing the target." },
        { "mount", "rateCap",
          ValueType::number, 'd', false, Access::read, Kind::state, Persist::show,
          true, "50",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "Hz", 1.0, false, "park",
          "Default outbound rate cap for the mounted nodes." },
        { "mount", "anticipatable",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::show,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "Whether the mounted nodes may be pre-sent before GO. False for third parties." },
        { "mount", "panic",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "park",
          false, 0.0, false, 0.0,
          enum_mount_panic, 2,
          "", 1.0, false, "park",
          "Default resting state for the mounted nodes." },
        { "mount", "loaded",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::none,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "Whether the namespace file has been read." },
        { "mount", "nodeCount",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "How many nodes the mount contributed." },
        { "mount", "queryPort",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "0",
          true, 0.0, true, 65535.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The port the target answers OSCQuery on, which is a different number from the one it listens for messages on - WFS-DIY takes messages on 8000 and describes itself on 5005. Zero means it was not declared, which is the only honest default: most devices do not run an OSCQuery server at all." },
        { "mount", "readback",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "none",
          false, 0.0, false, 0.0,
          enum_mount_readback, 2,
          "", 1.0, false, "park",
          "Whether this target can be ASKED what a value is, and how. Transport says how to send and says nothing about the other direction, so without this a cue whose wait is verified against a write-only device is a cue that can never succeed and nothing notices until the show. None is the default because it is true of most devices: OSCQuery was never standardised, and a mounted namespace is usually hand-written for a box that will never answer. A verified cue aimed at a none is refused when the show loads, which is the whole point of declaring it." },
        { "mount", "sent",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "How many messages have left for this target since the show opened. A readout for a tech rehearsal, and the first thing to establish when a device is not moving and nobody knows whose end is wrong: UDP cannot report delivery, so what Go.dot can honestly say is how many times it sent." },
        { "audio", "tracks",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          false, "",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The fixed number of audio tracks, and so the polyphony ceiling: N tracks is N simultaneous cues. Zero is legal and means a show with no audio. Required, and deliberately without a default - the number is a decision about the shape of a show, and no value here could be right for every rig." },
        { "audio", "device",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The audio device the engine has open, or empty when there is none." },
        { "audio", "outputs",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "How many hardware output channels are available to route to. A cue wider than this is refused when the show loads." },
        { "audio", "status",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "stopped",
          false, 0.0, false, 0.0,
          enum_audio_status, 3,
          "", 5.0, false, "park",
          "Whether audio is running. An unlocked device is present and producing nothing, which is a different failure from no device at all and wants a different remedy." },
        { "bus", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "The bus name as the designer wrote it. Names are what appear in a dropdown and on a scribble strip; channel numbers are not." },
        { "bus", "firstChannel",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "The first hardware output channel this bus occupies, counting from zero." },
        { "bus", "width",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "1",
          true, 1.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "How many consecutive channels the bus occupies. Explicit and never inferred: the engine will not quietly widen or narrow a cue to make it fit." },
    };
}
