/*
    This file is part of Go.dot — https://github.com/pob31/go.dot

    Copyright (C) 2026 Pierre-Olivier Boulant

    Go.dot is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later
    version. Go.dot is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
    (LICENSE, at the repository root) for more details.

    SPDX-License-Identifier: GPL-3.0-or-later
*/

#pragma once

/*
    GENERATED FILE — do not edit.

    Written by scripts/generate-schema.py from
    docs/parameters/godot-parameters.csv. To change anything here, change a
    row in that file and run the generator; the test `schema.generated` fails
    if the two disagree, so a hand edit here does not survive CI.

    It is committed rather than generated at build time so that a clone with
    no Python still builds.
*/

#include <wfg/engine/document/SchemaTypes.h>

namespace wfg::doc::generated
{
    inline constexpr std::string_view enum_engine_clock[] = { "dummy", "device" };
    inline constexpr std::string_view enum_cue_kind[] = { "memo", "group", "media", "fade", "stop", "osc", "midi" };
    inline constexpr std::string_view enum_cue_role[] = { "member", "header", "footer", "persistent" };
    inline constexpr std::string_view enum_cue_prepare[] = { "idle", "preparing", "pending", "partial", "armed", "verified" };
    inline constexpr std::string_view enum_trigger_kind[] = { "osc", "midi", "clock" };
    inline constexpr std::string_view enum_trigger_type[] = { "noteOn", "noteOff", "programChange", "controlChange" };
    inline constexpr std::string_view enum_fade_curve[] = { "linear", "sCurve" };
    inline constexpr std::string_view enum_stop_verb[] = { "hard", "fade", "afterMember", "afterIteration", "advance" };
    inline constexpr std::string_view enum_stop_curve[] = { "linear", "sCurve" };
    inline constexpr std::string_view enum_osc_wait[] = { "none", "sent", "verified" };
    inline constexpr std::string_view enum_midi_type[] = { "noteOn", "noteOff", "programChange", "controlChange", "pitchBend", "aftertouch", "channelPressure", "sysex" };
    inline constexpr std::string_view enum_midi_wait[] = { "none", "sent" };
    inline constexpr std::string_view enum_run_kind[] = { "memo", "group", "media", "fade", "stop", "osc", "midi" };
    inline constexpr std::string_view enum_run_phase[] = { "entering", "preparing", "prepared", "header", "members", "footer" };
    inline constexpr std::string_view enum_run_state[] = { "preparing", "waiting", "armed", "playing", "stopping", "postWait", "done", "failed" };
    inline constexpr std::string_view enum_run_warning[] = { "no-channel", "revoked" };
    inline constexpr std::string_view enum_group_mode[] = { "timeline", "sequence" };
    inline constexpr std::string_view enum_group_advance[] = { "auto", "manual" };
    inline constexpr std::string_view enum_group_selection[] = { "sequential", "shuffle" };
    inline constexpr std::string_view enum_mount_transport[] = { "udp", "tcp", "ws" };
    inline constexpr std::string_view enum_mount_panic[] = { "park", "snap" };
    inline constexpr std::string_view enum_mount_readback[] = { "none", "oscquery" };
    inline constexpr std::string_view enum_audio_status[] = { "stopped", "running", "noClock" };
    inline constexpr std::string_view enum_slot_kind[] = { "processorInput", "rackChannel" };
    inline constexpr std::string_view enum_rackChannel_class[] = { "mono", "monoToStereo", "stereo" };
    inline constexpr std::string_view enum_rackChannel_access[] = { "exclusive", "shared" };

    inline constexpr AttributeRow attributes[] =
    {
        { "engine", "product",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "Go.dot",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The product name." },
        { "engine", "version",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The running build's version." },
        { "engine", "tick",
          ValueType::integer64, 'h', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "tick", 5.0, false, "park",
          "",
          "The current tick index." },
        { "engine", "sampleRate",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "Hz", 1.0, false, "park",
          "",
          "The clock's sample rate. Observed from the device from Phase 2; not a setting." },
        { "engine", "blockSize",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 1.0, false, "park",
          "",
          "The audio block size the clock is being advanced by." },
        { "engine", "samplesPerTick",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 1.0, false, "park",
          "",
          "Samples per 50 Hz tick; the sample rate divided by 50." },
        { "engine", "lateness",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 5.0, false, "park",
          "",
          "How late the last tick was processed, in samples." },
        { "engine", "latenessMax",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "samples", 5.0, false, "park",
          "",
          "The worst lateness since the engine started." },
        { "engine", "clock",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "dummy",
          false, 0.0, false, 0.0,
          enum_engine_clock, 2,
          "", 1.0, false, "park",
          "",
          "Which clock is advancing the sample counter." },
        { "engine", "errorCount",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "Commands rejected since the engine started." },
        { "engine", "rtViolations",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "Allocations Go.dot's own code made on the audio thread since the engine started. Zero is the only acceptable value: PRD 4.2 forbids allocation there, and an allocation is a lock inside the allocator taken while a block is due. Reads zero in a build configured without the real-time checks, where nobody is looking." },
        { "engine", "rtForeignAllocations",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "Allocations Tracktion made inside the audio callback since the engine started, counted separately and never hidden. Tracktion takes a shared lock every block by design; this is a measured fact about a dependency, not a defect in it." },
        { "engine", "launchLatencyTicks",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "How many ticks pass between a GO being applied and the sound starting. It is not a preference: it is one tick plus however many the audio block spans, which is the smallest delay that guarantees the launch is never placed in the past and so never back-dated. Published because a designer timing a cue against light needs the number rather than a feeling about it." },
        { "engine", "sequenceGapTicks",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "How many ticks pass between one member of an automatic sequence ending and the next one sounding. Two, plus the launch latency: a member reports it has ended during one tick, the scheduler sees that on the next and asks for the next member, and the launch is placed on the one after. It is the price of every decision being a logged command rather than something a hook quietly does - which is what lets a whole show replay - and it is published for the same reason the launch latency is: a designer timing a chain against light needs the number rather than a feeling about it. A sample-accurate join is what ranges are for (PRD 3.24); a sequence group is discrete cues relaunched." },
        { "engine", "lastError",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "The most recent rejection: tick, sequence, origin, reason and command. The only way an OSC client can learn that its write was refused." },
        { "engine", "analysisRebuilds",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "How many times the edit-time liveness analysis has been rebuilt since the engine started. Published so that the cache behind it can be asserted by COUNTING rather than by timing (measurement M18): what the design guarantees is that a hundred publishes with nothing edited cost no rebuild at all, and a wall-clock threshold on a shared CI runner is a flaky test that teaches people to re-run the suite. The same argument as mountRebuilds in Phase 3, which is the shape this borrows." },
        { "document", "path",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The open bundle's folder." },
        { "document", "name",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The open bundle's name." },
        { "document", "formatVersion",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "1",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The show format this document was written against." },
        { "document", "dirty",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::none,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "Whether there are unsaved changes to show.xml." },
        { "document", "warnings",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "Everything wrong with the open show that did not stop it opening, one per line: the references that point at nothing, and the slot overlaps the edit-time analysis found. NEWLINE-SEPARATED and not space-separated, which no other list-shaped readout here is, because a warning is a sentence and sentences contain spaces. A refusal is not in it - a document that fails validate is never handed to the engine, so by the time anything can read this there are none." },
        { "lists", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The identifiers of the show's cue lists, in order, space-separated. The roster of what can be run at once: PRD 3.5 has several lists live together, each with a standby of its own, so that a timecode- or OSC-triggered chain can never move the operator's position." },
        { "lists", "focus",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::state,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "list",
          "Which list GO acts on. Exactly one, and exclusive by construction rather than by upkeep - it is one value, so there is no flag anywhere to leave set. A list that has gone takes the focus with it and the first remaining list has it instead, which is why nothing has to remember to move this when a list is deleted. It is remembered across a save for the same reason the standby is: a rehearsal reopened where it was left is the kinder default, and losing state.xml costs only where somebody had got to." },
        { "list", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cue list's name." },
        { "list", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The identifiers of the list's top-level children, in order, space-separated." },
        { "list", "persistentOrder",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The identifiers of the cues in this list's persistent section, in order, space-separated. PRD 3.29: a persistent cue is the thing that should be running at all times and is relaunched if it is not, in a section of its own - not the header, because a header fires once and never resets while a persistent cue re-asserts. The cursor skips the section as it skips a footer, standby.set refuses its cues, and they are not GO targets; after every applied go, cue.fire or trigger.fire the engine checks each one against what it declares and relaunches or re-sends through run.assert. Kinds honoured: media, osc and midi; a fade, a stop or a group in the section is a validate warning and is ignored. Empty when the list has no section." },
        { "list", "persistent",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The identifier of this list's persistent section, or empty when it has none - what cue.create takes as a parent to put a cue in it. Made by list.persistent, which answers with the one that exists." },
        { "list", "standby",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::state,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "cue",
          "The cue GO will act on. One per list, and always one of that list's own top-level children or empty; moved only by a standby command, a write to this node, or the repair when the cue it names is deleted or moved away. Never by selection or scrolling." },
        { "list", "aim",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Where an operator is pointing when they ask what the show WOULD be: a cue identifier and an offset in seconds, space-separated. PRD 3.13-s state position, and it is a cue and an offset rather than a wall time because a manual list has no time in it - between two GOs there is however long the actor took, so -the state at 04:12- is a question the document cannot answer. An offset of -1 means BEFORE that cue has fired: standby on it and nothing of it done, which is what -take it back to cue 12- means and is a different position from nought seconds in. Written through list.aim; read by a client dragging a finger along the list." },
        { "list", "solve",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 5.0, false, "park",
          "",
          "What the show would be at the aim, as JSON: the standby to set, the runs that should be sounding and how far into each, the values the desk should be holding and which cue last wrote each, the trims a fade left behind, and the CONFUSED list. One node holding a document rather than a subtree of nodes appearing and vanishing under a dragged finger - a solve changes shape as the aim moves, and a namespace that grew and shrank at fifty hertz would be one no client could subscribe to. The confused list is the feature rather than the apology (PRD 3.24): every place the walk could not know, with the default it took." },
        { "list", "statePosition",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Where the last load-to-time actually landed, in the same spelling as aim - PRD 3.13-s second pointer. After a jump the two agree; after a manual tweak they do not, and that divergence is exactly what a running view has to show, because it is the difference between where the operator asked to be and where the show has got to since." },
        { "list", "history",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The last sixty-four steps this list took, newest first, space-separated, each as tick:cue:origin - when, what, and whether it was a GO (g), a cue fired by name (f) or a trigger (t). PRD 3.13 keeps manual waypoints as a way to force a divergent world back into agreement, and the author-s decision (Q) is that the operator should not have to keep any: this is the history the engine keeps for them, and each step is a load-to-time target - before cue 12 is that cue at -1. Appended by the HANDLER of every applied go, cue.fire and trigger.fire, which is what makes it model state a replay reproduces rather than something a hook noticed; never stored, because a history is what the machine happened to be doing (PRD 4.10) and a show reopened tomorrow starts a new one." },
        { "cue", "kind",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "memo",
          false, 0.0, false, 0.0,
          enum_cue_kind, 7,
          "", 50.0, false, "park",
          "",
          "What kind of cue this is, derived from the element rather than stored: a Group is a group and a Media is media. Deriving it is what stops a client turning one kind into another by writing a word, and what lets the grammar refuse a file attribute on a cue that plays nothing." },
        { "cue", "number",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The decimal cue number. A string, because 12.5.1 is one; mutable, renumbered during tech, and never an identity." },
        { "cue", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cue's name, as the operator reads it." },
        { "cue", "notes",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Free text for the designer." },
        { "cue", "enabled",
          ValueType::boolean, 'T', false, Access::readWrite, Kind::state, Persist::show,
          true, "true",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Whether the cue runs at all. A disabled cue is skipped, not deleted." },
        { "cue", "colour",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "A #RRGGBB decoration. Never the sole carrier of information." },
        { "cue", "preWait",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "How long after entry before this cue starts. A group has one of its own, and it runs before its members begin their own pre-waits, so raising it defers the whole group." },
        { "cue", "postWait",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "How long after completion before this cue reports done to its parent. A group is complete once every member is, its members' own post-waits included; the group's post-wait then runs on top of that." },
        { "cue", "parent",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The identifier of the containing list or group." },
        { "cue", "index",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Position among siblings, zero-based." },
        { "cue", "role",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "member",
          false, 0.0, false, 0.0,
          enum_cue_role, 4,
          "", 50.0, false, "park",
          "",
          "Where this cue sits in the thing that contains it: an ordinary member, one of the cues in its group's header or footer, or one of the list's persistent cues. Derived from the element that contains it rather than stored, like `kind` and for the same reason - a client that could write it could move a cue between a group's preparation and its members without the group knowing. A cue at the top level of a list is a member. The whole vocabulary is declared here although `persistent` cannot occur until the section exists, because an enum that grows later grows under a client that has already read it." },
        { "cue", "prepare",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "idle",
          false, 0.0, false, 0.0,
          enum_cue_prepare, 6,
          "", 50.0, false, "park",
          "",
          "How far ahead this cue has been got ready, derived from its prepared run. PRD 3.12: preparation is per PARAMETER rather than per cue, so a block that is partly anticipatable says so rather than pretending. Idle is the resting state and means nothing has been prepared, which is not a failure - a MIDI cue can never be prepared and reads idle for ever. Preparing is in progress; pending is waiting for a slot somebody else holds (3.9e, in words rather than colour); partial means something in the block could not be anticipated and will happen at entry; armed means everything that could be prepared was, with nothing to verify; verified means every pre-sent value was read back equal, which is the only one of the six that says the desk agrees." },
        { "cue", "preset",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "cue",
          "The ancestor group whose header prepares this cue, or empty for the ordinary case - prepared with its own group, as everything is. THE MARK IS THE DECISION AND THE HEADER LINE IS A READING OF IT (PRD 4.10): nothing is copied into the Header element, so editing the line is editing the member, deleting the member removes the line with no repair rule to write, and the two can never come to disagree because there is only one of them. It names an ANCESTOR rather than being a tickbox, because a cue three groups deep can be got ready by its own group, by the act, or by the opening scene, and which one is a decision about how early. A value naming a group that is not an ancestor is a validate warning and is ignored - not a refusal, because the repair is somebody dragging it somewhere sensible and yesterday-s show must still open." },
        { "media", "file",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The media to play, as a path relative to the bundle's media/ folder. Relative because a show travels between machines and an absolute path is a fact about the machine it was authored on. A file that is missing is reported when the show loads and fails the cue when it is armed - it never fails the load, because a show with one missing sound is still a show somebody has to run tonight." },
        { "media", "level",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, -120.0, true, 12.0,
          nullptr, 0,
          "dB", 50.0, false, "park",
          "",
          "The level the cue plays at, as decided. Not what it is doing: a fade writes run/<id>/level and leaves this alone, so the document keeps saying what somebody chose while the run says what is happening. -120 dB is silence rather than a very small number." },
        { "media", "startOffset",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "How far into the file playback begins. A cue that starts at the downbeat rather than at the top of the recording." },
        { "media", "duration",
          ValueType::number, 'd', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 1.0, false, "park",
          "",
          "How long the file is, in seconds, read from its header once when the show is opened. On owner `media` and not `cue`, or every memo, group and fade would grow one - and `fade` and `stop` already carry a duration of their own, which is a different thing entirely. A READOUT about a file rather than a decision anybody took, so it is never stored (PRD 4.10) and never logged. Nought means the file is missing, unreadable, or in a format this build has no reader for; the state solver reads that as -I do not know how long this is- and says so rather than guessing." },
        { "route", "bus",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "bus",
          "The identifier of the bus this destination feeds. A destination names a bus and never a hardware channel: the bus is where the author said a channel exists, and a show moved to a different rig re-points buses rather than every cue." },
        { "route", "gains",
          ValueType::number, 'd', true, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The coefficients from the cue's channels to the bus's, row by row: input 0 to every bus channel, then input 1, and so on. Its length is the cue's channel count times the bus width, and a length that does not match is refused when the show loads rather than discovered mid-cue. A coefficient is a plain multiplier and carries no dB - level is the cue's, and this is where it goes." },
        { "range", "cue",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cue this range belongs to, derived from where it sits. A range is a child of the media cue whose file it cuts up (PRD 3.24), so this is the containment read back rather than a second copy of it that could disagree." },
        { "range", "index",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Where it sits in the cue's list of ranges, counting from nought. Derived, and the one thing about a range that IS positional: the ranges of a cue are a playlist and a playlist is an order. It is read-only for the reason a cue's index is - moving a range is object.move, an edit somebody made, not a number somebody wrote." },
        { "range", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "What the strip shows (PRD 3.24). A range is a region of a file that somebody named - the verse, the approach, the last eight bars - and the name is the only part of it a designer says out loud." },
        { "range", "in",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "Where in the file the range begins, in seconds. Ranges may be discontiguous and in any file order (author, 2026-09-06): a media cue with ranges is a playlist over one file, so the second range may start before the first ends, or before it begins." },
        { "range", "out",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "Where in the file it ends, in seconds. Checked against the file length when the cue is ARMED, which is when the file is read, and not when the show loads - a show whose media is not on this machine yet is still a show somebody has to open. An out that is not after its in fails the arm." },
        { "range", "loops",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "1",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "How many passes of this range before playback continues into the next. Nought is for ever, which is what an ambience bed is: it plays until something advances it. The count is of passes rather than of repeats, so one is the range played once." },
        { "trigger", "cue",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cue this trigger fires, derived from where it sits. A trigger is a child of the cue it belongs to (PRD 3.7), so this is the containment read back rather than a second copy of it that could disagree." },
        { "trigger", "kind",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "osc",
          false, 0.0, false, 0.0,
          enum_trigger_kind, 3,
          "", 50.0, false, "park",
          "",
          "What kind of thing fires it. The three inputs Phase 3 builds: a message on Go.dot own OSC port, a MIDI event on an input it was told to open, and a time of day. Timecode is Phase 10, and GO is not in this list at all - GO is the operator, and the only trigger that moves the standby (PRD 3.5)." },
        { "trigger", "enabled",
          ValueType::boolean, 'T', false, Access::readWrite, Kind::state, Persist::show,
          true, "true",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Whether it can fire. A trigger turned off during tech is still written down, which is the whole difference between disabling one and deleting it." },
        { "trigger", "address",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "osc: the address that fires this cue, arriving on Go.dot own OSC port over UDP. Refused at load if it falls under /godot or under a mount prefix, because those are NODES - a trigger there would be a message that both wrote a value and fired a cue, and nobody could tell which had been meant." },
        { "trigger", "value",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "osc: an argument the message must also carry, written the way the log writes one - f:1, i:3, T, s:go. Empty matches any arguments including none, which is what a bare address means to most of the things that will be sending one." },
        { "trigger", "port",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "midi: the declared port the event must arrive on. Empty is any input, which is what a rig with one MIDI cable wants and is the honest default: naming a port that is not bound would be a trigger that silently never fires." },
        { "trigger", "channel",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, true, 16.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "midi: the channel, 1 to 16. Nought is any, and it is nought rather than -1 because MIDI channels are one-based everywhere a musician looks at them." },
        { "trigger", "type",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "noteOn",
          false, 0.0, false, 0.0,
          enum_trigger_type, 4,
          "", 50.0, false, "park",
          "",
          "midi: the event type. Four of them, which are the four a surface sends: the rest of the event types exist for MIDI CUES (PRD 3.10) rather than for listening." },
        { "trigger", "number",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, true, 127.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "midi: the note, controller or program number." },
        { "trigger", "data",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "-1",
          true, -1.0, true, 127.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "midi: the velocity or value that must match, or -1 for any. A note-on with velocity nought is a note-off on a great many devices, so matching on it is a thing somebody will need to do deliberately." },
        { "trigger", "at",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "clock: a local time of day, HH:MM:SS, fired once each day it is crossed while the show is open. The wall clock is the one input the model refuses to read - nothing inside the engine reads a clock, which is what makes a replay reproducible - so a crossing is noticed outside it and arrives as a logged command like any other." },
        { "fade", "target",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "cue",
          "The cue whose sound this fade moves. It targets the CUE and finds its live run when it fires, because a cue is what somebody wrote down and a run is what happens to be playing - and the show has to say the first without knowing the second." },
        { "fade", "level",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "-120",
          true, -120.0, true, 12.0,
          nullptr, 0,
          "dB", 50.0, false, "park",
          "",
          "Where the fade ends, in dB. -120 is silence rather than a very small number, and it is the default because a fade to silence is what most fades are - a fresh fade cue is a slow cut to nothing, which is a real thing to want and can only ever make the show quieter." },
        { "fade", "duration",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "How long it takes. Zero is a jump, and it is the default so that a fade nobody has finished writing does something obvious rather than something slow and mysterious." },
        { "fade", "curve",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "linear",
          false, 0.0, false, 0.0,
          enum_fade_curve, 2,
          "", 50.0, false, "park",
          "",
          "The shape it takes between the two levels. Linear in the dB domain, which is what a fader feels like; sCurve eases out of the start and into the end, for a fade that should not announce itself. Two shapes until the curve editor of Phase 5." },
        { "stop", "target",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "cue",
          "The cue this stops. As with a fade it names the cue and finds the run, and a target that is not running is a no-op that is applied rather than refused." },
        { "stop", "verb",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "hard",
          false, 0.0, false, 0.0,
          enum_stop_verb, 5,
          "", 50.0, false, "park",
          "",
          "How it stops. Hard stops now and takes Tracktion's own click suppression with it; fade runs a fade to silence first and stops when it arrives. The verb is separate from the duration so that a stop with a duration nobody meant cannot become a slow one by accident. afterMember and afterIteration are the two GRACEFUL ones, and they are only meaningful against a group: they let the scene reach a boundary it was going to reach anyway - the end of the member playing now, or the end of this round - and stop there, which is how an infinite loop is left without a cut. Against anything else they are a hard stop, because there is no boundary to wait for. advance is the third graceful one and belongs to a ranged media cue (PRD 3.24): it lets the range playing now finish the pass it is on and then leaves it, either into the next range or into silence - which is how an infinite ambience is got out of without a cut. Against a cue with no ranges it is a hard stop, for the same reason: there is no boundary." },
        { "stop", "duration",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "How long the fade half takes, when the verb is fade. Ignored by a hard stop." },
        { "stop", "curve",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "linear",
          false, 0.0, false, 0.0,
          enum_stop_curve, 2,
          "", 50.0, false, "park",
          "",
          "The shape of that fade. Ignored by a hard stop." },
        { "osc", "address",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The node this cue writes, which is an address in a mounted namespace rather than a message somebody composed. Naming the NODE is what lets the tree check it: a cue pointing at something the target does not have is findable before the show rather than during it, and the node already says what type it takes." },
        { "osc", "value",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "What to write, spelled the way the log spells an argument - f:0.5 for a float, i:3 for an integer, T for true. One atom, because a mounted node holds one value; the type is in the text so that a cue meaning the float and a cue meaning the integer are different cues rather than the same cue read twice by two machines." },
        { "osc", "wait",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "none",
          false, 0.0, false, 0.0,
          enum_osc_wait, 3,
          "", 50.0, false, "park",
          "",
          "How long the cue takes to be done. None finishes as soon as it is fired; sent finishes when the datagram has left the socket; verified finishes when the target has been asked and has answered with the value that was written. A sequence of verified cues is a chain that waits for each device instead of hoping (PRD 3.11), and it is the only one of the three that can tell you the device disagreed." },
        { "osc", "timeout",
          ValueType::number, 'd', false, Access::readWrite, Kind::state, Persist::show,
          true, "5",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "How long verified waits for an answer before failing the run. Ignored by the other two waits. Five seconds because it is long enough for a device that is thinking and short enough that a cue which is never going to answer does not hold a show past the point anybody would have given up on it. Zero means the first reply or nothing." },
        { "midi", "port",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "port",
          "The identifier of the declared <Port> this cue sends on. An identifier and not a name, for the reason a route names its bus by one: the name is what a person reads and what --midi-out is given, and renaming a port must not silence every cue that used it. A port that is declared and not bound fails the RUN with no-port and never the load, because which cable \"Lights\" is on is a fact about the building (PRD 4.10) and a show travels to a rig that has not been patched yet." },
        { "midi", "type",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "noteOn",
          false, 0.0, false, 0.0,
          enum_midi_type, 8,
          "", 50.0, false, "park",
          "",
          "Which event to send. Every type PRD 3.10 lists, including sysex, because a show that can send seven of eight is a show somebody has to keep a second program open for. The type decides which of the fields below mean anything, which wfg validate says out loud rather than the grammar refusing - one element per type would be eight elements for one concept." },
        { "midi", "channel",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "1",
          true, 1.0, true, 16.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The channel, one to sixteen. One-based because that is what is written on every device a musician has ever looked at, and unlike a TRIGGER's channel there is no 'any': a message has to go somewhere." },
        { "midi", "number",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, true, 127.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The note, controller or program number. Ignored by pitchBend, channelPressure and sysex, which have no such thing." },
        { "midi", "data",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, true, 16383.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The velocity, controller value, or the fourteen-bit pitch bend. One row for the three because they are one thing - the payload - and a bend that needed a row of its own would be a second place for a number to be wrong. Nought to 127 for everything but the bend, where 8192 is the centre." },
        { "midi", "sysex",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The bytes of a system-exclusive message, in hex, F0 to F7 inclusive - written the way a manual prints them, because that is where a designer is copying from. Ignored by every other type. A dump of any size is legal and the send is off the tick thread for exactly that reason: on Windows a hundred bytes busy-waits the calling thread for about thirty milliseconds." },
        { "midi", "wait",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "none",
          false, 0.0, false, 0.0,
          enum_midi_wait, 2,
          "", 50.0, false, "park",
          "",
          "How long the cue takes to be done. As a network cue, minus verified: MIDI has no read-back, so there is nothing that could answer, and asking for one is refused when the show loads rather than waiting for ever at half past seven. sent says the bytes reached the port." },
        { "port", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "What the show calls this port. The document holds what somebody decided (PRD 4.10), so it says 'Lights' or 'The desk'; --midi-out=<name>=<device> is what binds it to a cable on this machine, and the two are separate for the reason a bus and a hardware channel are." },
        { "runs", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The identifiers of the runs the engine is publishing, in the order they were created. A finished run keeps its place here for five seconds and is then dropped - Gogo is the present tense (PRD 7), and a four-hour show would otherwise publish four hours of finished runs on every tick." },
        { "run", "cue",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cue this run instantiates. A run is the live instance and the cue is what somebody wrote: the cue keeps saying what was decided while the run says what is happening (PRD 4.10)." },
        { "run", "kind",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          enum_run_kind, 7,
          "", 50.0, false, "park",
          "",
          "The kind of the cue this run instantiates, copied at launch so a client reading a run does not have to go and look the cue up - and so the answer survives the cue being edited underneath it." },
        { "run", "parent",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The group run this one is a member of, or empty at the top of a list. Runs and not cues, because the same cue can be a member of a group that is running twice - a shuffled loop plays it in round three and again in round five - and which one finished has to have an answer." },
        { "run", "children",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The runs this group run is organising, in the order they were spawned, space-separated. A group owns time, order and lifetime and no output of its own (PRD 4.12), so this is the whole of what it holds." },
        { "run", "phase",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          enum_run_phase, 6,
          "", 50.0, false, "park",
          "",
          "Which part of itself a group run is in: its own pre-wait, its header, its members, its footer. A READOUT and never a model input, like `position` and `rangeIteration` - the scheduler holds it on the job and mirrors it here for a client to watch, so it is not written to the log and a replay, which runs no scheduler, leaves it empty. Empty on every run that is not a group. The two prepare values arrive with the horizon (PR 4.5) and are declared here so the enum does not grow under a client that has already read it." },
        { "run", "state",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "armed",
          false, 0.0, false, 0.0,
          enum_run_state, 8,
          "", 50.0, false, "park",
          "",
          "Where the run is. Preparing means the horizon reached it and it is getting ready ahead of any GO - a run in that state is NOT live, and nothing that asks whether a cue is running counts it (PRD 3.12). Waiting means its pre-wait is running and nothing has fired yet; armed means its track is held and its media is being made ready; playing means the launch has been placed; stopping means a stop was asked for and has not landed; postWait means its own work is over and it is holding before it reports done to whatever is waiting on it; done and failed are both finished, and a failed run says why in error." },
        { "run", "track",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "-1",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The track it plays on, or -1 before one is held and after it is given back. The track count is the polyphony ceiling, so this is also which of those voices it is using. A playing track is never stolen." },
        { "run", "position",
          ValueType::number, 'd', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "s", 50.0, false, "park",
          "",
          "How far into the file it has got. A READOUT and never a model input: it is published for a client to watch and is not written to the log, because a log of every position would be a log of the clock rather than of anything anybody decided." },
        { "run", "level",
          ValueType::number, 'd', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, -120.0, true, 12.0,
          nullptr, 0,
          "dB", 50.0, false, "park",
          "",
          "The level it is playing at now, which is what a fade writes. Not the cue's authored level - that one stays where the designer left it, so a night of riding faders does not rewrite the show." },
        { "run", "late",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "How many blocks the launch was late by, when GO arrived before the arm had finished. Zero is the ordinary case, and the number is here because it is the difference between GO is instant as a claim and as a measurement." },
        { "run", "range",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "-1",
          true, -1.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Which of the cue's ranges is playing, counting from nought, or -1 for a run that is not in one - every kind but media, and a media cue with no ranges. A TRANSITION IS AN EVENT (PRD 3.15): this changes when the boundary into the range is PLACED, which is a logged command, so a replay reproduces which range every run was in at every tick with no audio at all." },
        { "run", "rangeIteration",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Which pass of that range is playing, counting from one, or nought when there is no range. A READOUT and not an event, like position: it is computed from the sample counter rather than logged, because a bed looping for four hours would otherwise write a record every few seconds for something nobody decided. It is the 3 of the strip's 3/8." },
        { "run", "iteration",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Which round this group run is on, counting from one. Zero before the first round has been drawn. A client showing 3/8 is showing this and iterations." },
        { "run", "iterations",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "1",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "How many rounds this run will play, copied from the group when it started - so an edit to loops changes the next run and not this one. Zero means for ever." },
        { "run", "round",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cue identifiers of the round in progress, in the order they will play, space-separated. MATERIALISED rather than computed: a shuffled round is drawn once, written into the log, and read back from there on replay - which is what lets a session reproduce without the random number generator ever being consulted again." },
        { "run", "pruned",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The members dropped from this run, space-separated. Pruning is RUN-LOCAL and evaporates with the run (PRD 3.6): it is what an operator does at 22:40 when one of eight ambiences is wrong tonight, and it must not be an edit to the show - tomorrow the cue is back." },
        { "run", "seed",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The seed this run is drawing its rounds from: the group seed when there is one, and a fresh one otherwise. Published because a shuffled night somebody liked is a night worth being able to ask for again." },
        { "run", "error",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Why it failed, when it did: no-track when every voice was busy, media-missing when the file is not in the bundle or a range is not inside it, no-port when a MIDI cue names a port nothing was bound to, bad-message when its own fields do not make a message anybody could send, no-slot when the cue has more ranges than the graph has launcher slots - which is a range added since the show was loaded, and needs a reload rather than an edit - bad-route when the destination cannot be honoured, bad-target when a fade or a stop names a cue this show does not contain at all - which is different from one that is not running, and is a warning wfg validate has already given, send-failed when a message could not be put on the wire, and the write refusals - bad-address, read-only, type-mismatch - when a network cue names a node the target does not have or will not take. timeout when a verified cue asked and nothing answered in time, and disagreed when something answered with a different value, which is the one failure that means the device is there and is not doing what it was told. Empty otherwise. A failed run was still an APPLIED command - the request was legal and the show could not honour it, which is a different thing from a request that was malformed." },
        { "run", "claims",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The slots this run holds, by identifier, space-separated. A VOICE IS NOT AMONG THEM - a track is not a declared object and where a voice is held is this run-s own `track`. Held from the arm until the run reaches done or failed, which is the same moment the voice is freed: `holdsTrack()` is a track and an unfinished run, so the claim-s release and the voice-s are one rule written in two places rather than two rules (PRD 3.9e)." },
        { "run", "pending",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The slots this run has claimed and not yet been given, because something else is holding them. PRD 3.9e: a claim on a busy slot is neither a failure nor a race - it lands when the holder-s run ends, and the claimant shows PENDING meanwhile. GO has already returned (4.1). A holder that never ends on its own, an infinite loop, is the operator-s to end. The launch waits on this being empty: half a cue is not a cue, and sending it into a slot somebody else holds is the fighting a claim exists to prevent." },
        { "run", "warning",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          enum_run_warning, 2,
          "", 50.0, false, "park",
          "",
          "Something this run did less of than it meant to, while still going. NOT a weaker `error`: an error is a run that did not do what it said, and a warning is a run that carried on. `no-channel` is a cue that lost an exclusive rack channel and played dry, which PRD 3.9e calls DEGRADE and which is the whole point of that policy - reporting it as a failure would either stop the scene or teach an operator to ignore the state that means stopped. In words, never colour alone (4.8)." },
        { "run", "asserted",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::none,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Whether this run was started by the persistent assertion (PRD 3.29) rather than by a person or a group: the engine found the cue not as its section declares - a bed whose file had run out, a value the desk no longer held - and put it back through run.assert, after an applied trigger and never on its own clock. Shown so an operator can tell a sound they started from one the machine restored." },
        { "group", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The identifiers of the group's children, in order, space-separated." },
        { "group", "headerOrder",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cues in this group's header, in order, space-separated. A header runs before the group's members (PRD 3.6) and is an ordinary cue list, so this is the same kind of answer as order - about a different list." },
        { "group", "footerOrder",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cues in this group's footer, in order, space-separated. A footer runs at group exit and BLOCKS: the group is not done until its cues are, so a following scene that reallocates the same channels waits for the release rather than racing it." },
        { "group", "headerDerived",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cues whose preset names this group, in document order, space-separated - the header lines somebody did not write. Derived the way order and headerOrder are, and run BEFORE the written header cues when the horizon reaches the group: a written header cue may reasonably depend on what the presets set - position the source, then move it - and the reverse dependency has no natural example. What the horizon does with a preset member is its preparable part and nothing else (PRD 3.12); the member still runs where it sits, at its own moment, in its own group, which adopts the arm the ancestor made rather than making a second one." },
        { "group", "mode",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "sequence",
          false, 0.0, false, 0.0,
          enum_group_mode, 2,
          "", 50.0, false, "park",
          "",
          "Whether members are scheduled at entry or run one after another." },
        { "group", "advance",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "manual",
          false, 0.0, false, 0.0,
          enum_group_advance, 2,
          "", 50.0, false, "park",
          "",
          "Whether a member starts when the previous completes or on GO." },
        { "group", "selection",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "sequential",
          false, 0.0, false, 0.0,
          enum_group_selection, 2,
          "", 50.0, false, "park",
          "",
          "How the members of a round are ordered. sequential plays them as they are written; shuffle draws a fresh order for each round, redrawing until the first of the new round differs from the last of the one before it - so a member is never heard twice running across a boundary. With two members that constraint decides the order completely, which is correct rather than a degenerate case: alternating is what a designer asking for two shuffled ambiences means." },
        { "group", "loops",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "1",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "How many ROUNDS this group plays before it is done. Rounds, not playbacks: with play set, a round is a subset of the members, and three loops of two-of-five is six cues rather than three. Zero means for ever, which is what an ambience bed is, and is left by a stop verb, an advance or run.stop rather than by counting." },
        { "group", "play",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "How many members a round plays, out of however many there are (PRD 3.6 play N of M). Zero means all of them, which is the ordinary group. Larger than the membership is the same as all of them rather than a refusal: a designer deleting a member should not have their show stop loading." },
        { "group", "seed",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The seed a shuffled group draws its rounds from. Zero means a fresh one per run, drawn when the run starts and written into its log - so a shuffled show is different every night AND every night reproduces exactly. A seed set here is the other thing somebody wants: the same order at every performance, which is how a shuffled scene gets rehearsed." },
        { "mount", "prefix",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The address the foreign namespace is mounted at." },
        { "mount", "transport",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "udp",
          false, 0.0, false, 0.0,
          enum_mount_transport, 3,
          "", 1.0, false, "park",
          "",
          "How the mounted target is reached. Only udp carries messages today; tcp and ws are declared because a document should be able to say what a device is before Go.dot can talk to it, and a mount declaring either is refused when the show loads rather than going quiet during it." },
        { "mount", "host",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "127.0.0.1",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "Where the target is. A literal address rather than a name, because a socket resolves a hostname on every send whose destination differs from the last one, and a blocking lookup on the tick thread is a frame nobody gets back. It defaults to this machine because the ordinary rig is Go.dot and its processors on one box; anything else says so." },
        { "mount", "port",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          false, "",
          true, 1.0, true, 65535.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The port the target listens on. Required, and deliberately without a default for the same reason audio/tracks is: no number could be right for every device, and a mount that guessed would send into the dark and report success. UDP never tells you nobody was listening, so this one has to be right in the document or it is never right at all." },
        { "mount", "namespace",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The bundle-relative OSCQuery namespace file describing the target." },
        { "mount", "rateCap",
          ValueType::number, 'd', false, Access::read, Kind::state, Persist::show,
          true, "50",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "Hz", 1.0, false, "park",
          "",
          "Default outbound rate cap for the mounted nodes." },
        { "mount", "anticipatable",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::show,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "Whether the mounted nodes may be pre-sent before GO. False for third parties." },
        { "mount", "panic",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "park",
          false, 0.0, false, 0.0,
          enum_mount_panic, 2,
          "", 1.0, false, "park",
          "",
          "Default resting state for the mounted nodes." },
        { "mount", "loaded",
          ValueType::boolean, 'T', false, Access::read, Kind::state, Persist::none,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "Whether the namespace file has been read." },
        { "mount", "nodeCount",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "How many nodes the mount contributed." },
        { "mount", "queryPort",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "0",
          true, 0.0, true, 65535.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The port the target answers OSCQuery on, which is a different number from the one it listens for messages on - WFS-DIY takes messages on 8000 and describes itself on 5005. Zero means it was not declared, which is the only honest default: most devices do not run an OSCQuery server at all." },
        { "mount", "readback",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::show,
          true, "none",
          false, 0.0, false, 0.0,
          enum_mount_readback, 2,
          "", 1.0, false, "park",
          "",
          "Whether this target can be ASKED what a value is, and how. Transport says how to send and says nothing about the other direction, so without this a cue whose wait is verified against a write-only device is a cue that can never succeed and nothing notices until the show. None is the default because it is true of most devices: OSCQuery was never standardised, and a mounted namespace is usually hand-written for a box that will never answer. A verified cue aimed at a none is refused when the show loads, which is the whole point of declaring it." },
        { "mount", "sent",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "How many messages have left for this target since the show opened. A readout for a tech rehearsal, and the first thing to establish when a device is not moving and nobody knows whose end is wrong: UDP cannot report delivery, so what Go.dot can honestly say is how many times it sent." },
        { "audio", "tracks",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          false, "",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The fixed number of audio tracks, and so the polyphony ceiling: N tracks is N simultaneous cues. Zero is legal and means a show with no audio. Required, and deliberately without a default - the number is a decision about the shape of a show, and no value here could be right for every rig." },
        { "audio", "device",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The audio device the engine has open, or empty when there is none." },
        { "audio", "outputs",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::none,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "How many hardware output channels are available to route to. A cue wider than this is refused when the show loads." },
        { "audio", "status",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "stopped",
          false, 0.0, false, 0.0,
          enum_audio_status, 3,
          "", 5.0, false, "park",
          "",
          "Whether audio is running. An unlocked device is present and producing nothing, which is a different failure from no device at all and wants a different remedy." },
        { "bus", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The bus name as the designer wrote it. Names are what appear in a dropdown and on a scribble strip; channel numbers are not." },
        { "bus", "firstChannel",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "The first hardware output channel this bus occupies, counting from zero." },
        { "bus", "width",
          ValueType::integer, 'i', false, Access::read, Kind::state, Persist::show,
          true, "1",
          true, 1.0, false, 0.0,
          nullptr, 0,
          "", 1.0, false, "park",
          "",
          "How many consecutive channels the bus occupies. Explicit and never inferred: the engine will not quietly widen or narrow a cue to make it fit." },
        { "slots", "order",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Every slot the show declares, in document order: the processor inputs of every mount, then the rack channels. A VOICE IS NOT IN IT - a track is not an object anybody wrote down, it has no identifier, and Show/Audio/@tracks is a count rather than a list; where a voice is held has been readable at /godot/run/<id>/track since Phase 2. The allocator still treats a track as a slot kind (PRD 3.9e); being one mechanism does not oblige it to be one data structure." },
        { "slot", "name",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "What the designer called it. PRD 3.9b: the names appear in the dropdown and on the OLED, and the channel numbers do not - -Voix solo- is what somebody wrote down and -input 3- is a fact about a patch that will change." },
        { "slot", "kind",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          true, "processorInput",
          false, 0.0, false, 0.0,
          enum_slot_kind, 2,
          "", 50.0, false, "park",
          "",
          "Which kind of slot this is, derived from the element rather than stored: a Slot under a Mount is a processor input and a Channel under the Rack is a rack channel. Derived for the reason cue/kind is - a client that could write it could turn one into the other by writing a word, and the two are released and refused by different policies (PRD 3.9e)." },
        { "slot", "holder",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The run holding this slot, or empty. Read off the run table rather than kept beside it, the way a busy track is: a second copy of who holds what is a second thing to keep in step, and the one that is wrong is always the copy." },
        { "slot", "pending",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The runs waiting for this slot, in the order they claimed it. A QUEUE rather than a set, so that who gets it next is read rather than inferred - and the answer is the same on a replay, because the order runs were created in is the order the log made them." },
        { "slot", "usage",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The live ranges of this slot, as cue pairs: the cue that claims it and the cue whose row the claim is released at, space-separated, one pair after another. The data behind PRD 3.9c-s usage-over-show-time plot, which Phase 5 draws. Read in list order rather than in seconds because a manual list has no time between GOs; inside a timeline or an automatic chain the analysis knows the seconds too and uses them to decide overlap, but a pair of cues is what a plot can draw and a person can read." },
        { "slot", "overlaps",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The pairs of cues whose live ranges intersect on this slot, space-separated. A WARNING AND NEVER A REFUSAL (PRD 3.9c): the analysis is conservative by design - it reports overlap it cannot prove impossible - so a show with an ambience looping for ever and two cues on one processor input reports an overlap that is correct, unavoidable and completely fine. Marking either cue-s Feed or Insert shared says the sharing was meant and silences that pair." },
        { "processorInput", "address",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The address of the input this slot is, under its own mount-s prefix: /wfs/input/3 and not input 3. The parameters underneath it - a position, a send, an LFO rate - are ordinary mounted nodes that an osc cue writes; this says which of them belong to the source a cue claims, which is what stops two cues fighting over one trajectory (PRD 3.9b)." },
        { "processorInput", "width",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "1",
          true, 1.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "How many channels the input takes. Explicit and never inferred, like a bus-s: PRD 3.9b refuses a silent downmix or upmix, and a slot is the one destination where width is enforced, because a slot has one and a bus is a summing point that does not care." },
        { "processorInput", "bus",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "bus",
          "The bus that carries audio into this input. A slot is a routing and a claim in one object: the audio reaches the processor through an ordinary bus, and the claim is what keeps a second cue out of the position and the LFO state behind it. Two separate objects would let a show route a cue somewhere it had not claimed." },
        { "processorInput", "firstChannel",
          ValueType::integer, 'i', false, Access::readWrite, Kind::state, Persist::show,
          true, "0",
          true, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "Where in that bus this slot-s channels begin, counting from zero. The attribute that makes one wide send ordinary: a rig feeding a twelve-input processor has one twelve-channel bus rather than twelve buses, and the third input is channel two of it. Exactly bus/firstChannel-s idea one level down. firstChannel + width must fit inside the bus, checked when the show loads." },
        { "rackChannel", "class",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "mono",
          false, 0.0, false, 0.0,
          enum_rackChannel_class, 3,
          "", 50.0, false, "park",
          "",
          "What this channel takes in and puts out. Stereo-to-mono is deliberately absent (PRD 3.18) and wider comes later. The class is the type a claim is matched against, the way a processor input-s width is." },
        { "rackChannel", "access",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          true, "exclusive",
          false, 0.0, false, 0.0,
          enum_rackChannel_access, 2,
          "", 50.0, false, "park",
          "",
          "Whether a cue holds this channel alone. A per-source insert is exclusive and is allocated; a reverb many cues send into is SHARED, which PRD 3.9e says is a bus with a chain rather than a slot - declared and published here, and never claimed." },
        { "feed", "slot",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "slot",
          "The processor input this cue feeds. A cue-s destinations are a list, not a choice (PRD 3.9b): a source into WFS plus a stereo feed to foldback is ordinary, so a Feed sits beside a Route rather than instead of one." },
        { "feed", "gains",
          ValueType::number, 'd', true, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The coefficients from the cue-s channels to the slot-s, row by row, exactly as a route-s are. Its length is the cue-s channel count times the slot-s width, and a length that does not match is refused when the show loads. Required rather than defaulted to an identity: PRD 3.9b says width is explicit and never automatic, and what keeps that from being tedious is copy-assignment and multi-select edit rather than a default that is right until it is not." },
        { "feed", "shared",
          ValueType::boolean, 'T', false, Access::readWrite, Kind::state, Persist::show,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "This cue is MEANT to share the slot with another. PRD 3.9c-s -allow marking deliberate sharing-: the live-range analysis is conservative by design and reports overlaps it cannot prove impossible, so this is how a designer says of one pair that they considered it. It silences that pair-s warning and nothing else." },
        { "feed", "cue",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cue this destination belongs to, derived from where it sits. A Feed is addressed by identity like every other object (§1), so this is how a client that found one gets back to the cue that owns it - the same answer range/cue gives." },
        { "insert", "channel",
          ValueType::string, 's', false, Access::readWrite, Kind::state, Persist::show,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "rackChannel",
          "The rack channel this cue processes through. In Phase 4 the claim is bookkeeping and changes no sound: the pool and its claims are this phase-s, and the tracks, the sends and the plugins inside a channel are Phase 9-s (PRD 3.18)." },
        { "insert", "shared",
          ValueType::boolean, 'T', false, Access::readWrite, Kind::state, Persist::show,
          true, "false",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "As feed/shared, for an exclusive channel two cues are meant to share." },
        { "insert", "cue",
          ValueType::string, 's', false, Access::read, Kind::state, Persist::none,
          false, "",
          false, 0.0, false, 0.0,
          nullptr, 0,
          "", 50.0, false, "park",
          "",
          "The cue this insert belongs to, derived. As feed/cue." },
    };
}
