/*
    This file is part of Go.dot — https://github.com/pob31/go.dot

    Copyright (C) 2026 Pierre-Olivier Boulant

    Go.dot is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later
    version. Go.dot is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
    (LICENSE, at the repository root) for more details.

    SPDX-License-Identifier: GPL-3.0-or-later
*/

/*
    The show document: its schema, its identifiers, its canonical form and the
    commands that are the only way it changes.

    A serialisation surface, so every case here runs under fr_FR as well as C.
    The fixtures are hand-authored and hand-checked rather than produced by the
    writer under test — a golden generated by the code it is testing proves only
    that the code agrees with itself, which is the failure this file exists to
    catch.
*/

#include <3rd_party/doctest/tracktion_doctest.hpp>

#include "TestSupport.h"

#include <wfg/engine/Engine.h>
#include <wfg/engine/document/CanonicalXml.h>
#include <wfg/engine/document/DocumentCommands.h>
#include <wfg/engine/log/Replay.h>

#include <juce_core/juce_core.h>

#include <cstring>
#include <set>
#include <string>
#include <utility>

using namespace wfg;
using namespace wfg::doc;

namespace
{
    std::string fixture (const std::string& name)
    {
        const juce::File file { juce::String (std::string (WFG_TEST_FIXTURES_DIR))
                                  + "/documents/" + juce::String (name) };

        REQUIRE_MESSAGE (file.existsAsFile(), "missing fixture: " << file.getFullPathName());

        /*  Read as bytes and normalise, so a checkout that turned the fixture
            into CRLF tests the same thing as one that did not. The WRITER's
            line endings are pinned separately, below — that is the property
            that actually matters. */
        juce::MemoryBlock block;
        file.loadFileAsData (block);

        std::string text { static_cast<const char*> (block.getData()), block.getSize() };

        std::string out;
        out.reserve (text.size());

        for (const char c : text)
            if (c != '\r')
                out.push_back (c);

        return out;
    }

    ShowDocument loaded (const std::string& fixtureName)
    {
        ShowDocument document;
        const auto result = CanonicalXml::read (fixture (fixtureName), document);

        for (const auto& problem : result.problems)
            INFO (problem);

        REQUIRE (result.ok);
        return document;
    }
}

//==============================================================================
TEST_CASE ("schema: the table describes the elements a show is made of")
{
    const auto& schema = Schema::instance();

    REQUIRE (schema.element ("Show") != nullptr);
    REQUIRE (schema.element ("List") != nullptr);
    REQUIRE (schema.element ("Cue") != nullptr);
    REQUIRE (schema.element ("Group") != nullptr);
    CHECK (schema.element ("Nonsense") == nullptr);

    // A Group is a Cue (PRD §3.6), so it carries every Cue attribute as well as
    // its own. That rule lives in Schema, not in the generated table.
    REQUIRE (schema.attribute ("Cue", "name") != nullptr);
    REQUIRE (schema.attribute ("Group", "name") != nullptr);
    REQUIRE (schema.attribute ("Group", "mode") != nullptr);
    CHECK (schema.attribute ("Cue", "mode") == nullptr);      // a plain cue has no mode

    // Containment: a List holds cues and groups; a plain Cue holds nothing.
    CHECK (schema.element ("List")->mayContain ("Cue"));
    CHECK (schema.element ("List")->mayContain ("Group"));
    CHECK (schema.element ("Group")->mayContain ("Cue"));
    CHECK_FALSE (schema.element ("Cue")->mayContain ("Cue"));
    CHECK_FALSE (schema.element ("List")->mayContain ("List"));

    /*  A RANGE IS A MEDIA CUE'S, and a trigger is everybody's. §3.24 makes a
        range a region of the cue's own file, so a cue that plays nothing has
        nothing to cut up; §3.7 gives a trigger list to "a cue or a group",
        which is every kind there is. */
    REQUIRE (schema.element ("Range") != nullptr);
    CHECK (schema.element ("Media")->mayContain ("Range"));
    CHECK_FALSE (schema.element ("Cue")->mayContain ("Range"));
    CHECK_FALSE (schema.element ("Group")->mayContain ("Range"));
    CHECK (schema.element ("Media")->mayContain ("Trigger"));
    CHECK (schema.element ("Cue")->mayContain ("Trigger"));

    /*  A MIDI CUE IS A CUE and its ports are the show's. Two elements that
        both wanted to be called `Midi` - the kind and the section - are why the
        section is `MidiPorts`: two elements of one name would be one element as
        far as the schema is concerned. */
    REQUIRE (schema.element ("Midi") != nullptr);
    REQUIRE (schema.element ("MidiPorts") != nullptr);
    REQUIRE (schema.element ("Port") != nullptr);

    CHECK (schema.element ("List")->mayContain ("Midi"));
    CHECK (schema.element ("Group")->mayContain ("Midi"));
    CHECK (schema.element ("Show")->mayContain ("MidiPorts"));
    CHECK (schema.element ("MidiPorts")->mayContain ("Port"));
    CHECK_FALSE (schema.element ("MidiPorts")->mayContain ("Midi"));

    REQUIRE (schema.attribute ("Midi", "sysex") != nullptr);
    REQUIRE (schema.attribute ("Midi", "name") != nullptr);      // a cue first
    CHECK (schema.attribute ("Midi", "file") == nullptr);        // and not a media one

    REQUIRE (schema.attribute ("Range", "in") != nullptr);
    REQUIRE (schema.attribute ("Range", "loops") != nullptr);
    CHECK (schema.attribute ("Range", "index") == nullptr);   // derived, so not stored
}

TEST_CASE ("schema: a derived value is not an attribute of anything")
{
    /*  `persist=none` marks a value computed from the tree — a cue's index
        among its siblings, its kind, a list's order. Storing one would be a
        second copy of what the structure already says, and the two would
        eventually disagree. They are absent from the element entirely, which is
        what makes the writer and the reader refuse them without either having
        to know why. */
    const auto& schema = Schema::instance();

    CHECK (schema.attribute ("Cue", "index") == nullptr);
    CHECK (schema.attribute ("Cue", "parent") == nullptr);
    CHECK (schema.attribute ("Cue", "kind") == nullptr);
    CHECK (schema.attribute ("List", "order") == nullptr);

    /*  Read-only is a DIFFERENT thing from derived, and conflating them was a
        real bug here: a mount's prefix is decided by someone, lives in the file,
        and still may not be written over OSC while a show runs. */
    const auto* prefix = schema.attribute ("Mount", "prefix");
    REQUIRE (prefix != nullptr);
    CHECK (prefix->access() == Access::read);
    CHECK (prefix->persist() == Persist::show);
}

//==============================================================================
TEST_CASE ("identifiers: shape, alphabet and round trip")
{
    CHECK (Id::isValid ("K7Q2M9X4"));
    CHECK (Id::isValid ("00000000"));
    CHECK (Id::isValid ("ZZZZZZZZ"));

    CHECK_FALSE (Id::isValid (""));
    CHECK_FALSE (Id::isValid ("K7Q2M9X"));       // seven
    CHECK_FALSE (Id::isValid ("K7Q2M9X45"));     // nine
    CHECK_FALSE (Id::isValid ("k7q2m9x4"));      // lower case is a second spelling

    /*  I, L, O and U are excluded because they are the ones misread aloud and
        in handwriting, and this string is meant to be read over comms. */
    CHECK_FALSE (Id::isValid ("IIIIIIII"));
    CHECK_FALSE (Id::isValid ("LLLLLLLL"));
    CHECK_FALSE (Id::isValid ("OOOOOOOO"));
    CHECK_FALSE (Id::isValid ("UUUUUUUU"));

    for (std::uint64_t v : { 0ull, 1ull, 31ull, 32ull, 1099511627775ull /* 2^40 - 1 */ })
    {
        const auto encoded = Id::encode (v);
        INFO ("value " << v << " encoded as " << encoded);
        REQUIRE (Id::isValid (encoded));
        CHECK (Id::decode (encoded) == v);
    }

    // Eight digits carry exactly 40 bits; anything above is masked rather than
    // silently producing a longer string.
    CHECK (Id::encode (1099511627776ull) == Id::encode (0));
}

TEST_CASE ("identifiers: the registry hands out unique ones and takes them back")
{
    auto registry = IdRegistry::withSeed (20260905u);

    std::set<std::string> drawn;

    for (int i = 0; i < 2000; ++i)
    {
        const auto id = registry.generate();
        REQUIRE (Id::isValid (id));
        CHECK (drawn.insert (id).second);       // never twice while in use
    }

    CHECK (registry.size() == 2000);

    const auto sample = *drawn.begin();
    CHECK (registry.isTaken (sample));
    registry.release (sample);
    CHECK_FALSE (registry.isTaken (sample));

    // Reserving what a file supplied. A second reservation is a duplicate id,
    // which is a validation error rather than something to paper over.
    CHECK (registry.reserve ("K7Q2M9X4"));
    CHECK_FALSE (registry.reserve ("K7Q2M9X4"));
    CHECK_FALSE (registry.reserve ("not an id"));
}

TEST_CASE ("identifiers: two registries do not agree, which is the point")
{
    /*  Identifiers are drawn from entropy rather than counted, so two shows
        edited in parallel and later merged do not collide. A counter would
        guarantee that they did. */
    auto a = IdRegistry::withSystemEntropy();
    auto b = IdRegistry::withSystemEntropy();

    std::set<std::string> fromA, fromB;

    for (int i = 0; i < 200; ++i)
    {
        fromA.insert (a.generate());
        fromB.insert (b.generate());
    }

    std::set<std::string> shared;
    std::set_intersection (fromA.begin(), fromA.end(), fromB.begin(), fromB.end(),
                           std::inserter (shared, shared.begin()));

    CHECK (shared.empty());
}

//==============================================================================
TEST_CASE ("canonical xml: a hand-authored file becomes the committed golden")
{
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    /*  The real test of the writer. The input was typed by hand with its
        attributes in a jumble, its indentation wrong and several values written
        at their defaults; the golden was checked by eye. Neither came out of
        the code under test. */
    ReadResult result;
    const auto produced = CanonicalXml::canonicalise (fixture ("messy-input.xml"), result);

    for (const auto& problem : result.problems)
        INFO (problem);

    REQUIRE (result.ok);
    CHECK (produced == fixture ("canonical.xml"));
}

TEST_CASE ("canonical xml: load then save is byte-identical")
{
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    const auto canonical = fixture ("canonical.xml");

    ShowDocument document;
    const auto result = CanonicalXml::read (canonical, document);
    REQUIRE (result.ok);

    CHECK (CanonicalXml::write (document) == canonical);
}

TEST_CASE ("canonical xml: the writer emits LF and no declaration, on every platform")
{
    const auto text = CanonicalXml::write (loaded ("canonical.xml"));

    CHECK (text.find ('\r') == std::string::npos);
    CHECK (text.rfind ("<?xml", 0) != 0);
    CHECK (! text.empty());
    CHECK (text.back() == '\n');
}

TEST_CASE ("canonical xml: values keep their type through a load")
{
    /*  The defect this whole layer is shaped around. juce::ValueTree::fromXml
        stores every attribute as a string, and juce::var then reports "1.5" ==
        1.5, so a typed write over a string-typed property is dropped without a
        word. Checking the value is not enough — CHECK (v == 1.5) passes for the
        string. The TYPE is what has to be asserted. */
    const auto document = loaded ("canonical.xml");

    const auto cue = document.findById ("F7HR8TVD");
    REQUIRE (cue.isValid());

    const auto postWait = cue.getProperty ("postWait");
    CHECK (postWait.isDouble());
    CHECK_FALSE (postWait.isString());
    CHECK (static_cast<double> (postWait) == doctest::Approx (1.5));

    const auto name = cue.getProperty ("name");
    CHECK (name.isString());
}

TEST_CASE ("canonical xml: an attribute at its default is omitted, and still reads back")
{
    /*  Omitting defaults is what keeps a diff about decisions. It only works if
        an absent attribute and a present default are the same thing everywhere,
        so the getter has to agree with the writer. */
    const auto canonical = fixture ("canonical.xml");

    CHECK (canonical.find ("enabled=") == std::string::npos);
    CHECK (canonical.find ("mode=") == std::string::npos);
    CHECK (canonical.find ("advance=") == std::string::npos);

    const auto document = loaded ("canonical.xml");

    CHECK (document.getAttribute ("/godot/cue/B3N8R5TW/enabled") == std::string ("true"));
    CHECK (document.getAttribute ("/godot/cue/D9FH2JKA/mode") == std::string ("sequence"));
    CHECK (document.getAttribute ("/godot/cue/D9FH2JKA/advance") == std::string ("manual"));
}

//==============================================================================
TEST_CASE ("canonical xml: clearing an attribute writes what never setting it would")
{
    /*  Canonical means one show has exactly one spelling, and this is the case
        that nearly got away. For a row the table gives NO default - a name, a
        note, a cue number - an absent attribute still reads back as the empty
        string, because that is what getAttribute returns for one. So writing
        `notes=""` would be a second file for a show already spelled by the file
        without it, and load-save-compare would pass on both while a diff
        between two people's copies showed a change nobody made.

        The writer therefore takes its omit rule from what ABSENCE MEANS rather
        than from whether a default was declared. Clearing a note and never
        having written one are the same show. */
    ShowDocument untouched;
    REQUIRE (CanonicalXml::read (fixture ("canonical.xml"), untouched).ok);

    ShowDocument cleared;
    REQUIRE (CanonicalXml::read (fixture ("canonical.xml"), cleared).ok);
    REQUIRE (cleared.setAttribute ("/godot/cue/B3N8R5TW/notes", "").ok);

    const auto written = CanonicalXml::write (cleared);

    CHECK (written == CanonicalXml::write (untouched));
    CHECK (written.find ("notes=\"\"") == std::string::npos);
}

TEST_CASE ("canonical xml: a broken document is refused, and says why")
{
    struct Case { const char* xml; const char* mentions; };

    const Case cases[] = {
        { "<Nonsense/>",                                            "root element" },
        { "<Show><Lists><Wrong/></Lists></Show>",                   "may not contain" },
        { "<Show><Lists><List id=\"7K2QM9X4\" nope=\"1\"/></Lists></Show>", "unknown attribute" },
        { "<Show><Lists><List name=\"no id\"/></Lists></Show>",     "missing id" },
        { "<Show><Lists><List id=\"lowercase\"/></Lists></Show>",   "malformed id" },
        { "<Show><Lists><List id=\"7K2QM9X4\"/><List id=\"7K2QM9X4\"/></Lists></Show>", "duplicate id" },
        { "<Show><Lists><List id=\"7K2QM9X4\"><Cue id=\"B3N8R5TW\" preWait=\"soon\"/></Cue></List></Lists></Show>",
          "" },
        { "<Show><Lists><List id=\"7K2QM9X4\"><Cue id=\"B3N8R5TW\" preWait=\"-1\"/></List></Lists></Show>",
          "out of range" },
        { "<Show><Lists><List id=\"7K2QM9X4\"><Group id=\"D9FH2JKA\" mode=\"sideways\"/></List></Lists></Show>",
          "expected one of" },
        { "<Show><Lists id=\"7K2QM9X4\"/></Show>",                  "may not carry an id" },
        { "not xml at all",                                         "" },
    };

    for (const auto& c : cases)
    {
        INFO ("document: " << c.xml);

        ShowDocument document;
        const auto result = CanonicalXml::read (c.xml, document);

        CHECK_FALSE (result.ok);
        REQUIRE_FALSE (result.problems.empty());

        if (std::string (c.mentions).empty())
            continue;

        bool mentioned = false;

        for (const auto& problem : result.problems)
            if (problem.find (c.mentions) != std::string::npos)
                mentioned = true;

        if (! mentioned)
            for (const auto& problem : result.problems)
                INFO ("reported: " << problem);

        CHECK (mentioned);
    }
}

TEST_CASE ("canonical xml: a refused document leaves the old one untouched")
{
    /*  A show that half-loaded is worse than one that did not: the operator
        finds out during the show. */
    auto document = loaded ("canonical.xml");
    const auto before = CanonicalXml::write (document);

    const auto result = CanonicalXml::read ("<Show><Lists><Broken/></Lists></Show>", document);

    CHECK_FALSE (result.ok);
    CHECK (CanonicalXml::write (document) == before);
}

TEST_CASE ("canonical xml: awkward text survives the round trip")
{
    ShowDocument document;
    const auto list = document.createList ("Main");
    REQUIRE (list.ok);

    const std::vector<std::string> awkward {
        "a & b", "<angle>", "quote \" here", "tab\there", "line\nbreak",
        "Repetition generale", "  leading and trailing  "
    };

    for (const auto& name : awkward)
    {
        const auto cue = document.createCue (list.id, 0, "memo", name);
        REQUIRE (cue.ok);
    }

    const auto text = CanonicalXml::write (document);

    ShowDocument reloaded;
    const auto result = CanonicalXml::read (text, reloaded);

    for (const auto& problem : result.problems)
        INFO (problem);

    REQUIRE (result.ok);
    CHECK (CanonicalXml::write (reloaded) == text);
}

//==============================================================================
TEST_CASE ("document: structure is built and taken apart through the commands")
{
    ShowDocument document;

    const auto list = document.createList ("Main");
    REQUIRE (list.ok);
    CHECK (Id::isValid (list.id));

    const auto group = document.createCue (list.id, 0, "group", "Preshow");
    REQUIRE (group.ok);

    const auto first = document.createCue (group.id, 0, "memo", "Walk-in");
    const auto second = document.createCue (group.id, 1, "memo", "Announce");
    REQUIRE (first.ok);
    REQUIRE (second.ok);

    CHECK (document.findById (group.id).getNumChildren() == 2);

    // An index past the end appends rather than failing; a negative one is
    // refused, because it usually means the caller computed it wrong.
    CHECK (document.createCue (group.id, 99, "memo", "Last").ok);
    CHECK_FALSE (document.createCue (group.id, -1, "memo", "Nope").ok);

    // A group takes its contents with it, and gives every identifier back.
    const auto sizeBefore = document.ids().size();
    REQUIRE (document.remove (group.id).ok);
    CHECK (document.findById (first.id).isValid() == false);
    CHECK (document.ids().size() == sizeBefore - 4);
}

TEST_CASE ("document: a group cannot be moved inside itself")
{
    /*  Without this the tree stops being a tree: the subtree detaches with the
        node, is never seen again, and its identifiers stay reserved forever. */
    ShowDocument document;

    const auto list = document.createList ("Main");
    const auto outer = document.createCue (list.id, 0, "group", "Outer");
    const auto inner = document.createCue (outer.id, 0, "group", "Inner");

    REQUIRE (inner.ok);

    CHECK_FALSE (document.move (outer.id, inner.id, 0).ok);
    CHECK_FALSE (document.move (outer.id, outer.id, 0).ok);

    // Moving the other way round is fine.
    CHECK (document.move (inner.id, list.id, 0).ok);
    CHECK (document.findById (inner.id).getParent().getType().toString() == "List");
}

TEST_CASE ("document: an identifier supplied twice is refused")
{
    ShowDocument document;

    const auto list = document.createList ("Main", "7K2QM9X4");
    REQUIRE (list.ok);
    CHECK (list.id == "7K2QM9X4");

    CHECK_FALSE (document.createList ("Other", "7K2QM9X4").ok);
    CHECK_FALSE (document.createList ("Other", "lowercase").ok);
}

//==============================================================================
TEST_CASE ("document: addresses resolve, and only to what they name")
{
    const auto document = loaded ("canonical.xml");

    CHECK (document.resolve ("/godot/cue/B3N8R5TW/name").isValid());
    CHECK (document.resolve ("/godot/list/7K2QM9X4/name").isValid());
    CHECK (document.resolve ("/godot/mount/G1JS4VWE/prefix").isValid());
    CHECK (document.resolve ("/godot/document/formatVersion").isValid());

    // A group is addressed as a cue, because a Group is a Cue and a client with
    // an identifier should not have to know which it got.
    CHECK (document.resolve ("/godot/cue/D9FH2JKA/mode").isValid());

    CHECK_FALSE (document.resolve ("/godot/cue/B3N8R5TW/nonsense").isValid());
    CHECK_FALSE (document.resolve ("/godot/cue/ZZZZZZZZ/name").isValid());
    CHECK_FALSE (document.resolve ("/godot/cue/B3N8R5TW").isValid());
    CHECK_FALSE (document.resolve ("/elsewhere/cue/B3N8R5TW/name").isValid());

    // The owner word has to match what was found. An identifier alone is
    // unambiguous; the word is there for the reader, and a reader that can be
    // wrong is worse than no reader.
    CHECK_FALSE (document.resolve ("/godot/list/B3N8R5TW/name").isValid());
}

TEST_CASE ("document: a write is checked before it lands")
{
    ShowDocument document;
    const auto list = document.createList ("Main");
    const auto cue = document.createCue (list.id, 0, "memo", "Original");

    const auto address = "/godot/cue/" + cue.id + "/";

    CHECK (document.setAttribute (address + "name", "Renamed").ok);
    CHECK (document.getAttribute (address + "name") == std::string ("Renamed"));

    CHECK (document.setAttribute (address + "preWait", "2.5").ok);
    CHECK (document.getAttribute (address + "preWait") == std::string ("2.5"));

    // Refusals, each with the reason a client reads back.
    CHECK (document.setAttribute (address + "preWait", "soon").reason == reason::typeMismatch);
    CHECK (document.setAttribute (address + "preWait", "-1").reason == reason::typeMismatch);
    CHECK (document.setAttribute (address + "enabled", "yes").reason == reason::typeMismatch);
    CHECK (document.setAttribute (address + "nonsense", "x").reason == reason::badAddress);
    CHECK (document.setAttribute ("/godot/cue/ZZZZZZZZ/name", "x").reason == reason::badAddress);

    // Read-only means read-only, even though the value IS stored.
    const auto mount = document.createMount ("/wfs", "namespaces/wfs.json");
    REQUIRE (mount.ok);
    CHECK (document.setAttribute ("/godot/mount/" + mount.id + "/prefix", "/other").reason
             == reason::readOnly);

    // A refused write changes nothing.
    CHECK (document.getAttribute (address + "preWait") == std::string ("2.5"));
}

TEST_CASE ("document: a number keeps its VALUE through a write and a read")
{
    /*  Its value, not its spelling. A number has more than one valid text, and
        the canonical one is the shortest that reads back identically — so
        1000000 comes back as "1e+06" and 1.0 as "1". What must hold is that the
        double is the same double, which is what a replay compares. */
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    ShowDocument document;
    const auto list = document.createList ("Main");
    const auto cue = document.createCue (list.id, 0, "memo", "Timing");
    const auto address = "/godot/cue/" + cue.id + "/preWait";

    for (const char* written : { "0.5", "1.25", "0.1", "3.141592653589793",
                                 "1000000", "0.0000001", "1", "0" })
    {
        const std::string text { written };
        REQUIRE (document.setAttribute (address, text).ok);

        const auto readBack = document.getAttribute (address);
        REQUIRE (readBack.has_value());
        INFO ("wrote " << text << ", read back " << *readBack);

        const auto wanted = osc::parseDouble (text);
        const auto got = osc::parseDouble (*readBack);
        REQUIRE (wanted.has_value());
        REQUIRE (got.has_value());

        CHECK (std::memcmp (&*wanted, &*got, sizeof (double)) == 0);
    }
}

TEST_CASE ("document: the canonical spelling of a number is pinned")
{
    /*  Whatever a number is written as, canonicalising it twice gives the same
        text — that is the whole of what "canonical" claims. These are the
        spellings, recorded so a change to the formatter shows up here rather
        than as a mysterious diff in someone's show file.

        Note where the exponent appears and where it does not: every quantity a
        show actually carries — seconds, decibels, metres, hertz — is well
        inside the fixed range, so the scientific form is what you get for
        values no cue would have. */
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    ShowDocument document;
    const auto list = document.createList ("Main");
    const auto cue = document.createCue (list.id, 0, "memo", "Timing");
    const auto address = "/godot/cue/" + cue.id + "/preWait";

    const std::pair<const char*, const char*> spellings[] = {
        { "0",        "0" },
        { "0.0",      "0" },
        { "1",        "1" },
        { "1.0",      "1" },
        { "0.5",      "0.5" },
        { "2.50",     "2.5" },
        { "1e2",      "100" },
        { "3600",     "3600" },
        { "20000",    "20000" },
        { "1000000",  "1e+06" },
    };

    for (const auto& [written, canonical] : spellings)
    {
        REQUIRE (document.setAttribute (address, written).ok);
        INFO ("wrote " << std::string (written));
        CHECK (document.getAttribute (address) == std::string (canonical));
    }
}

//==============================================================================
TEST_CASE ("document commands: every structural edit is a named command")
{
    /*  PRD §4.11 — every gesture-reachable action exists as a named command. The
        document has no setter that is not one of these. */
    ShowDocument document;
    CommandRegistry registry;
    registerDocumentCommands (registry, document);

    for (const char* name : { "list.create", "cue.create", "mount.create",
                              "object.delete", "object.move", "node.set" })
    {
        INFO ("command: " << name);
        CHECK (registry.find (name) != nullptr);
    }
}

TEST_CASE ("document commands: a created identifier comes back in the applied arguments")
{
    /*  The property replay rests on. The caller omits the identifier, the engine
        draws one, and the LOG records the call with it — so replaying that
        record supplies the identifier rather than drawing a different one. */
    Engine engine;
    ShowDocument document;
    registerDocumentCommands (engine.commands(), document);

    engine.log().openInMemory ({});
    engine.submit (origin::cli, "list.create", { osc::Value::string ("Main") });
    engine.processTick (0);

    const auto parsed = LogFile::parse (engine.log().contents());
    REQUIRE (parsed.records.size() == 1);
    REQUIRE (parsed.records[0].kind == LogRecord::Kind::applied);
    REQUIRE (parsed.records[0].args.size() == 2);

    const auto id = parsed.records[0].args[1].getString();
    CHECK (Id::isValid (id));
    CHECK (document.findById (id).isValid());
}

TEST_CASE ("document commands: a rejection reaches the log with its reason")
{
    Engine engine;
    ShowDocument document;
    registerDocumentCommands (engine.commands(), document);

    engine.log().openInMemory ({});
    engine.submit (origin::cli, "node.set",
                   { osc::Value::string ("/godot/cue/ZZZZZZZZ/name"), osc::Value::string ("x") });
    engine.processTick (0);

    const auto parsed = LogFile::parse (engine.log().contents());
    REQUIRE (parsed.records.size() == 1);
    CHECK (parsed.records[0].kind == LogRecord::Kind::rejected);
    CHECK (parsed.records[0].reason == reason::badAddress);
    CHECK (engine.lastError().find (reason::badAddress) != std::string::npos);
}

//==============================================================================
TEST_CASE ("replay: a session that builds a cue list reproduces itself and its document")
{
    /*  Replay fixture #1. Two claims, and the second is the stronger one: the
        log reproduces itself record for record, AND the document the replay
        arrives at is byte-identical to the one the session saved. A log that
        replays to a different show would be a log worth nothing. */
    const auto record = [] (Engine& engine, ShowDocument& document)
    {
        engine.submit (origin::cli, "list.create", { osc::Value::string ("Main") });
        engine.processTick (0);

        const auto listId = document.root().getChildWithName ("Lists").getChild (0)
                              .getProperty ("id").toString().toStdString();

        engine.submit (origin::cli, "cue.create",
                       { osc::Value::string (listId), osc::Value::int32 (0),
                         osc::Value::string ("memo"), osc::Value::string ("House to half") });
        engine.submit (origin::cli, "cue.create",
                       { osc::Value::string (listId), osc::Value::int32 (1),
                         osc::Value::string ("group"), osc::Value::string ("Preshow") });
        engine.processTick (4);

        const auto groupId = document.root().getChildWithName ("Lists").getChild (0)
                               .getChild (1).getProperty ("id").toString().toStdString();

        engine.submit ("ws:127.0.0.1:51234", "cue.create",
                       { osc::Value::string (groupId), osc::Value::int32 (0),
                         osc::Value::string ("memo"), osc::Value::string ("Walk-in") });
        engine.processTick (9);

        const auto firstCueId = document.root().getChildWithName ("Lists").getChild (0)
                                  .getChild (0).getProperty ("id").toString().toStdString();

        engine.submit (origin::cli, "node.set",
                       { osc::Value::string ("/godot/cue/" + firstCueId + "/number"),
                         osc::Value::string ("1") });
        engine.submit (origin::cli, "node.set",
                       { osc::Value::string ("/godot/cue/" + firstCueId + "/preWait"),
                         osc::Value::string ("2.5") });
        engine.submit (origin::cli, "object.move",
                       { osc::Value::string (firstCueId), osc::Value::string (groupId),
                         osc::Value::int32 (0) });
        engine.submit (origin::cli, "node.set",
                       { osc::Value::string ("/godot/cue/ZZZZZZZZ/name"), osc::Value::string ("x") });
        engine.processTick (25);
    };

    Engine session;
    ShowDocument sessionDocument;
    registerDocumentCommands (session.commands(), sessionDocument);
    session.log().openInMemory ({});
    record (session, sessionDocument);

    const auto sessionXml = CanonicalXml::write (sessionDocument);
    const auto original = LogFile::parse (session.log().contents());

    REQUIRE (original.errors.empty());
    REQUIRE (original.records.size() == 8);

    Engine fresh;
    ShowDocument freshDocument;
    registerDocumentCommands (fresh.commands(), freshDocument);

    const auto result = replay (fresh, original);

    for (const auto& mismatch : result.mismatches)
        INFO (mismatch);

    CHECK (result.ok);
    CHECK (result.producedLog == session.log().contents());

    // And the document the replay arrived at is the same show.
    CHECK (CanonicalXml::write (freshDocument) == sessionXml);
}
