/*
    This file is part of Go.dot — https://github.com/pob31/go.dot

    Copyright (C) 2026 Pierre-Olivier Boulant

    Go.dot is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later
    version. Go.dot is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
    (LICENSE, at the repository root) for more details.

    SPDX-License-Identifier: GPL-3.0-or-later
*/

/*
    The show document: its schema, its identifiers, its canonical form and the
    commands that are the only way it changes.

    A serialisation surface, so every case here runs under fr_FR as well as C.
    The fixtures are hand-authored and hand-checked rather than produced by the
    writer under test — a golden generated by the code it is testing proves only
    that the code agrees with itself, which is the failure this file exists to
    catch.
*/

#include <3rd_party/doctest/tracktion_doctest.hpp>

#include "TestSupport.h"

#include <wfg/engine/Engine.h>
#include <wfg/engine/cue/CueCommands.h>
#include <wfg/engine/cue/CueList.h>
#include <wfg/engine/document/Bundle.h>
#include <wfg/engine/document/CanonicalXml.h>
#include <wfg/engine/document/DocumentCommands.h>
#include <wfg/engine/document/EphemeralState.h>
#include <wfg/engine/log/Replay.h>

#include <juce_core/juce_core.h>

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <functional>
#include <set>
#include <string>
#include <utility>
#include <vector>

using namespace wfg;
using namespace wfg::doc;

namespace
{
    std::string fixture (const std::string& name)
    {
        const juce::File file { juce::String (std::string (WFG_TEST_FIXTURES_DIR))
                                  + "/documents/" + juce::String (name) };

        REQUIRE_MESSAGE (file.existsAsFile(), "missing fixture: " << file.getFullPathName());

        /*  Read as bytes and normalise, so a checkout that turned the fixture
            into CRLF tests the same thing as one that did not. The WRITER's
            line endings are pinned separately, below — that is the property
            that actually matters. */
        juce::MemoryBlock block;
        file.loadFileAsData (block);

        std::string text { static_cast<const char*> (block.getData()), block.getSize() };

        std::string out;
        out.reserve (text.size());

        for (const char c : text)
            if (c != '\r')
                out.push_back (c);

        return out;
    }

    ShowDocument loaded (const std::string& fixtureName)
    {
        ShowDocument document;
        const auto result = CanonicalXml::read (fixture (fixtureName), document);

        for (const auto& problem : result.problems)
            INFO (problem);

        REQUIRE (result.ok);
        return document;
    }
}

//==============================================================================
TEST_CASE ("schema: the table describes the elements a show is made of")
{
    const auto& schema = Schema::instance();

    REQUIRE (schema.element ("Show") != nullptr);
    REQUIRE (schema.element ("List") != nullptr);
    REQUIRE (schema.element ("Cue") != nullptr);
    REQUIRE (schema.element ("Group") != nullptr);
    CHECK (schema.element ("Nonsense") == nullptr);

    // A Group is a Cue (PRD §3.6), so it carries every Cue attribute as well as
    // its own. That rule lives in Schema, not in the generated table.
    REQUIRE (schema.attribute ("Cue", "name") != nullptr);
    REQUIRE (schema.attribute ("Group", "name") != nullptr);
    REQUIRE (schema.attribute ("Group", "mode") != nullptr);
    CHECK (schema.attribute ("Cue", "mode") == nullptr);      // a plain cue has no mode

    // Containment: a List holds cues and groups; a plain Cue holds nothing.
    CHECK (schema.element ("List")->mayContain ("Cue"));
    CHECK (schema.element ("List")->mayContain ("Group"));
    CHECK (schema.element ("Group")->mayContain ("Cue"));
    CHECK_FALSE (schema.element ("Cue")->mayContain ("Cue"));
    CHECK_FALSE (schema.element ("List")->mayContain ("List"));

    /*  A RANGE IS A MEDIA CUE'S, and a trigger is everybody's. §3.24 makes a
        range a region of the cue's own file, so a cue that plays nothing has
        nothing to cut up; §3.7 gives a trigger list to "a cue or a group",
        which is every kind there is. */
    REQUIRE (schema.element ("Range") != nullptr);
    CHECK (schema.element ("Media")->mayContain ("Range"));
    CHECK_FALSE (schema.element ("Cue")->mayContain ("Range"));
    CHECK_FALSE (schema.element ("Group")->mayContain ("Range"));
    CHECK (schema.element ("Media")->mayContain ("Trigger"));
    CHECK (schema.element ("Cue")->mayContain ("Trigger"));

    /*  A MIDI CUE IS A CUE and its ports are the show's. Two elements that
        both wanted to be called `Midi` - the kind and the section - are why the
        section is `MidiPorts`: two elements of one name would be one element as
        far as the schema is concerned. */
    REQUIRE (schema.element ("Midi") != nullptr);
    REQUIRE (schema.element ("MidiPorts") != nullptr);
    REQUIRE (schema.element ("Port") != nullptr);

    CHECK (schema.element ("List")->mayContain ("Midi"));
    CHECK (schema.element ("Group")->mayContain ("Midi"));
    CHECK (schema.element ("Show")->mayContain ("MidiPorts"));
    CHECK (schema.element ("MidiPorts")->mayContain ("Port"));
    CHECK_FALSE (schema.element ("MidiPorts")->mayContain ("Midi"));

    REQUIRE (schema.attribute ("Midi", "sysex") != nullptr);
    REQUIRE (schema.attribute ("Midi", "name") != nullptr);      // a cue first
    CHECK (schema.attribute ("Midi", "file") == nullptr);        // and not a media one

    REQUIRE (schema.attribute ("Range", "in") != nullptr);
    REQUIRE (schema.attribute ("Range", "loops") != nullptr);
    CHECK (schema.attribute ("Range", "index") == nullptr);   // derived, so not stored
}

TEST_CASE ("schema: a derived value is not an attribute of anything")
{
    /*  `persist=none` marks a value computed from the tree — a cue's index
        among its siblings, its kind, a list's order. Storing one would be a
        second copy of what the structure already says, and the two would
        eventually disagree. They are absent from the element entirely, which is
        what makes the writer and the reader refuse them without either having
        to know why. */
    const auto& schema = Schema::instance();

    CHECK (schema.attribute ("Cue", "index") == nullptr);
    CHECK (schema.attribute ("Cue", "parent") == nullptr);
    CHECK (schema.attribute ("Cue", "kind") == nullptr);
    CHECK (schema.attribute ("List", "order") == nullptr);

    /*  Read-only is a DIFFERENT thing from derived, and conflating them was a
        real bug here: a mount's prefix is decided by someone, lives in the file,
        and still may not be written over OSC while a show runs. */
    const auto* prefix = schema.attribute ("Mount", "prefix");
    REQUIRE (prefix != nullptr);
    CHECK (prefix->access() == Access::read);
    CHECK (prefix->persist() == Persist::show);
}

//==============================================================================
TEST_CASE ("identifiers: shape, alphabet and round trip")
{
    CHECK (Id::isValid ("K7Q2M9X4"));
    CHECK (Id::isValid ("00000000"));
    CHECK (Id::isValid ("ZZZZZZZZ"));

    CHECK_FALSE (Id::isValid (""));
    CHECK_FALSE (Id::isValid ("K7Q2M9X"));       // seven
    CHECK_FALSE (Id::isValid ("K7Q2M9X45"));     // nine
    CHECK_FALSE (Id::isValid ("k7q2m9x4"));      // lower case is a second spelling

    /*  I, L, O and U are excluded because they are the ones misread aloud and
        in handwriting, and this string is meant to be read over comms. */
    CHECK_FALSE (Id::isValid ("IIIIIIII"));
    CHECK_FALSE (Id::isValid ("LLLLLLLL"));
    CHECK_FALSE (Id::isValid ("OOOOOOOO"));
    CHECK_FALSE (Id::isValid ("UUUUUUUU"));

    for (std::uint64_t v : { 0ull, 1ull, 31ull, 32ull, 1099511627775ull /* 2^40 - 1 */ })
    {
        const auto encoded = Id::encode (v);
        INFO ("value " << v << " encoded as " << encoded);
        REQUIRE (Id::isValid (encoded));
        CHECK (Id::decode (encoded) == v);
    }

    // Eight digits carry exactly 40 bits; anything above is masked rather than
    // silently producing a longer string.
    CHECK (Id::encode (1099511627776ull) == Id::encode (0));
}

TEST_CASE ("identifiers: the registry hands out unique ones and takes them back")
{
    auto registry = IdRegistry::withSeed (20260905u);

    std::set<std::string> drawn;

    for (int i = 0; i < 2000; ++i)
    {
        const auto id = registry.generate();
        REQUIRE (Id::isValid (id));
        CHECK (drawn.insert (id).second);       // never twice while in use
    }

    CHECK (registry.size() == 2000);

    const auto sample = *drawn.begin();
    CHECK (registry.isTaken (sample));
    registry.release (sample);
    CHECK_FALSE (registry.isTaken (sample));

    // Reserving what a file supplied. A second reservation is a duplicate id,
    // which is a validation error rather than something to paper over.
    CHECK (registry.reserve ("K7Q2M9X4"));
    CHECK_FALSE (registry.reserve ("K7Q2M9X4"));
    CHECK_FALSE (registry.reserve ("not an id"));
}

TEST_CASE ("identifiers: two registries do not agree, which is the point")
{
    /*  Identifiers are drawn from entropy rather than counted, so two shows
        edited in parallel and later merged do not collide. A counter would
        guarantee that they did. */
    auto a = IdRegistry::withSystemEntropy();
    auto b = IdRegistry::withSystemEntropy();

    std::set<std::string> fromA, fromB;

    for (int i = 0; i < 200; ++i)
    {
        fromA.insert (a.generate());
        fromB.insert (b.generate());
    }

    std::set<std::string> shared;
    std::set_intersection (fromA.begin(), fromA.end(), fromB.begin(), fromB.end(),
                           std::inserter (shared, shared.begin()));

    CHECK (shared.empty());
}

//==============================================================================
TEST_CASE ("canonical xml: a hand-authored file becomes the committed golden")
{
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    /*  The real test of the writer. The input was typed by hand with its
        attributes in a jumble, its indentation wrong and several values written
        at their defaults; the golden was checked by eye. Neither came out of
        the code under test. */
    ReadResult result;
    const auto produced = CanonicalXml::canonicalise (fixture ("messy-input.xml"), result);

    for (const auto& problem : result.problems)
        INFO (problem);

    REQUIRE (result.ok);
    CHECK (produced == fixture ("canonical.xml"));
}

TEST_CASE ("canonical xml: load then save is byte-identical")
{
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    const auto canonical = fixture ("canonical.xml");

    ShowDocument document;
    const auto result = CanonicalXml::read (canonical, document);
    REQUIRE (result.ok);

    CHECK (CanonicalXml::write (document) == canonical);
}

TEST_CASE ("canonical xml: the writer emits LF and no declaration, on every platform")
{
    const auto text = CanonicalXml::write (loaded ("canonical.xml"));

    CHECK (text.find ('\r') == std::string::npos);
    CHECK (text.rfind ("<?xml", 0) != 0);
    CHECK (! text.empty());
    CHECK (text.back() == '\n');
}

TEST_CASE ("canonical xml: values keep their type through a load")
{
    /*  The defect this whole layer is shaped around. juce::ValueTree::fromXml
        stores every attribute as a string, and juce::var then reports "1.5" ==
        1.5, so a typed write over a string-typed property is dropped without a
        word. Checking the value is not enough — CHECK (v == 1.5) passes for the
        string. The TYPE is what has to be asserted. */
    const auto document = loaded ("canonical.xml");

    const auto cue = document.findById ("F7HR8TVD");
    REQUIRE (cue.isValid());

    const auto postWait = cue.getProperty ("postWait");
    CHECK (postWait.isDouble());
    CHECK_FALSE (postWait.isString());
    CHECK (static_cast<double> (postWait) == doctest::Approx (1.5));

    const auto name = cue.getProperty ("name");
    CHECK (name.isString());
}

TEST_CASE ("canonical xml: an attribute at its default is omitted, and still reads back")
{
    /*  Omitting defaults is what keeps a diff about decisions. It only works if
        an absent attribute and a present default are the same thing everywhere,
        so the getter has to agree with the writer. */
    const auto canonical = fixture ("canonical.xml");

    CHECK (canonical.find ("enabled=") == std::string::npos);
    CHECK (canonical.find ("mode=") == std::string::npos);
    CHECK (canonical.find ("advance=") == std::string::npos);

    const auto document = loaded ("canonical.xml");

    CHECK (document.getAttribute ("/godot/cue/B3N8R5TW/enabled") == std::string ("true"));
    CHECK (document.getAttribute ("/godot/cue/D9FH2JKA/mode") == std::string ("sequence"));
    CHECK (document.getAttribute ("/godot/cue/D9FH2JKA/advance") == std::string ("manual"));
}

//==============================================================================
TEST_CASE ("canonical xml: clearing an attribute writes what never setting it would")
{
    /*  Canonical means one show has exactly one spelling, and this is the case
        that nearly got away. For a row the table gives NO default - a name, a
        note, a cue number - an absent attribute still reads back as the empty
        string, because that is what getAttribute returns for one. So writing
        `notes=""` would be a second file for a show already spelled by the file
        without it, and load-save-compare would pass on both while a diff
        between two people's copies showed a change nobody made.

        The writer therefore takes its omit rule from what ABSENCE MEANS rather
        than from whether a default was declared. Clearing a note and never
        having written one are the same show. */
    ShowDocument untouched;
    REQUIRE (CanonicalXml::read (fixture ("canonical.xml"), untouched).ok);

    ShowDocument cleared;
    REQUIRE (CanonicalXml::read (fixture ("canonical.xml"), cleared).ok);
    REQUIRE (cleared.setAttribute ("/godot/cue/B3N8R5TW/notes", "").ok);

    const auto written = CanonicalXml::write (cleared);

    CHECK (written == CanonicalXml::write (untouched));
    CHECK (written.find ("notes=\"\"") == std::string::npos);
}

TEST_CASE ("canonical xml: a broken document is refused, and says why")
{
    struct Case { const char* xml; const char* mentions; };

    const Case cases[] = {
        { "<Nonsense/>",                                            "root element" },
        { "<Show><Lists><Wrong/></Lists></Show>",                   "may not contain" },
        { "<Show><Lists><List id=\"7K2QM9X4\" nope=\"1\"/></Lists></Show>", "unknown attribute" },
        { "<Show><Lists><List name=\"no id\"/></Lists></Show>",     "missing id" },
        { "<Show><Lists><List id=\"lowercase\"/></Lists></Show>",   "malformed id" },
        { "<Show><Lists><List id=\"7K2QM9X4\"/><List id=\"7K2QM9X4\"/></Lists></Show>", "duplicate id" },
        { "<Show><Lists><List id=\"7K2QM9X4\"><Cue id=\"B3N8R5TW\" preWait=\"soon\"/></Cue></List></Lists></Show>",
          "" },
        { "<Show><Lists><List id=\"7K2QM9X4\"><Cue id=\"B3N8R5TW\" preWait=\"-1\"/></List></Lists></Show>",
          "out of range" },
        { "<Show><Lists><List id=\"7K2QM9X4\"><Group id=\"D9FH2JKA\" mode=\"sideways\"/></List></Lists></Show>",
          "expected one of" },
        { "<Show><Lists id=\"7K2QM9X4\"/></Show>",                  "may not carry an id" },
        { "not xml at all",                                         "" },
    };

    for (const auto& c : cases)
    {
        INFO ("document: " << c.xml);

        ShowDocument document;
        const auto result = CanonicalXml::read (c.xml, document);

        CHECK_FALSE (result.ok);
        REQUIRE_FALSE (result.problems.empty());

        if (std::string (c.mentions).empty())
            continue;

        bool mentioned = false;

        for (const auto& problem : result.problems)
            if (problem.find (c.mentions) != std::string::npos)
                mentioned = true;

        if (! mentioned)
            for (const auto& problem : result.problems)
                INFO ("reported: " << problem);

        CHECK (mentioned);
    }
}

TEST_CASE ("canonical xml: a refused document leaves the old one untouched")
{
    /*  A show that half-loaded is worse than one that did not: the operator
        finds out during the show. */
    auto document = loaded ("canonical.xml");
    const auto before = CanonicalXml::write (document);

    const auto result = CanonicalXml::read ("<Show><Lists><Broken/></Lists></Show>", document);

    CHECK_FALSE (result.ok);
    CHECK (CanonicalXml::write (document) == before);
}

TEST_CASE ("canonical xml: awkward text survives the round trip")
{
    ShowDocument document;
    const auto list = document.createList ("Main");
    REQUIRE (list.ok);

    const std::vector<std::string> awkward {
        "a & b", "<angle>", "quote \" here", "tab\there", "line\nbreak",
        "Repetition generale", "  leading and trailing  "
    };

    for (const auto& name : awkward)
    {
        const auto cue = document.createCue (list.id, 0, "memo", name);
        REQUIRE (cue.ok);
    }

    const auto text = CanonicalXml::write (document);

    ShowDocument reloaded;
    const auto result = CanonicalXml::read (text, reloaded);

    for (const auto& problem : result.problems)
        INFO (problem);

    REQUIRE (result.ok);
    CHECK (CanonicalXml::write (reloaded) == text);
}

//==============================================================================
TEST_CASE ("document: structure is built and taken apart through the commands")
{
    ShowDocument document;

    const auto list = document.createList ("Main");
    REQUIRE (list.ok);
    CHECK (Id::isValid (list.id));

    const auto group = document.createCue (list.id, 0, "group", "Preshow");
    REQUIRE (group.ok);

    const auto first = document.createCue (group.id, 0, "memo", "Walk-in");
    const auto second = document.createCue (group.id, 1, "memo", "Announce");
    REQUIRE (first.ok);
    REQUIRE (second.ok);

    CHECK (document.findById (group.id).getNumChildren() == 2);

    // An index past the end appends rather than failing; a negative one is
    // refused, because it usually means the caller computed it wrong.
    CHECK (document.createCue (group.id, 99, "memo", "Last").ok);
    CHECK_FALSE (document.createCue (group.id, -1, "memo", "Nope").ok);

    // A group takes its contents with it, and gives every identifier back.
    const auto sizeBefore = document.ids().size();
    REQUIRE (document.remove (group.id).ok);
    CHECK (document.findById (first.id).isValid() == false);
    CHECK (document.ids().size() == sizeBefore - 4);
}

TEST_CASE ("document: a group cannot be moved inside itself")
{
    /*  Without this the tree stops being a tree: the subtree detaches with the
        node, is never seen again, and its identifiers stay reserved forever. */
    ShowDocument document;

    const auto list = document.createList ("Main");
    const auto outer = document.createCue (list.id, 0, "group", "Outer");
    const auto inner = document.createCue (outer.id, 0, "group", "Inner");

    REQUIRE (inner.ok);

    CHECK_FALSE (document.move (outer.id, inner.id, 0).ok);
    CHECK_FALSE (document.move (outer.id, outer.id, 0).ok);

    // Moving the other way round is fine.
    CHECK (document.move (inner.id, list.id, 0).ok);
    CHECK (document.findById (inner.id).getParent().getType().toString() == "List");
}

TEST_CASE ("document: an identifier supplied twice is refused")
{
    ShowDocument document;

    const auto list = document.createList ("Main", "7K2QM9X4");
    REQUIRE (list.ok);
    CHECK (list.id == "7K2QM9X4");

    CHECK_FALSE (document.createList ("Other", "7K2QM9X4").ok);
    CHECK_FALSE (document.createList ("Other", "lowercase").ok);
}

//==============================================================================
TEST_CASE ("document: addresses resolve, and only to what they name")
{
    const auto document = loaded ("canonical.xml");

    CHECK (document.resolve ("/godot/cue/B3N8R5TW/name").isValid());
    CHECK (document.resolve ("/godot/list/7K2QM9X4/name").isValid());
    CHECK (document.resolve ("/godot/mount/G1JS4VWE/prefix").isValid());
    CHECK (document.resolve ("/godot/document/formatVersion").isValid());

    // A group is addressed as a cue, because a Group is a Cue and a client with
    // an identifier should not have to know which it got.
    CHECK (document.resolve ("/godot/cue/D9FH2JKA/mode").isValid());

    CHECK_FALSE (document.resolve ("/godot/cue/B3N8R5TW/nonsense").isValid());
    CHECK_FALSE (document.resolve ("/godot/cue/ZZZZZZZZ/name").isValid());
    CHECK_FALSE (document.resolve ("/godot/cue/B3N8R5TW").isValid());
    CHECK_FALSE (document.resolve ("/elsewhere/cue/B3N8R5TW/name").isValid());

    // The owner word has to match what was found. An identifier alone is
    // unambiguous; the word is there for the reader, and a reader that can be
    // wrong is worse than no reader.
    CHECK_FALSE (document.resolve ("/godot/list/B3N8R5TW/name").isValid());
}

TEST_CASE ("document: a write is checked before it lands")
{
    ShowDocument document;
    const auto list = document.createList ("Main");
    const auto cue = document.createCue (list.id, 0, "memo", "Original");

    const auto address = "/godot/cue/" + cue.id + "/";

    CHECK (document.setAttribute (address + "name", "Renamed").ok);
    CHECK (document.getAttribute (address + "name") == std::string ("Renamed"));

    CHECK (document.setAttribute (address + "preWait", "2.5").ok);
    CHECK (document.getAttribute (address + "preWait") == std::string ("2.5"));

    // Refusals, each with the reason a client reads back.
    CHECK (document.setAttribute (address + "preWait", "soon").reason == reason::typeMismatch);
    CHECK (document.setAttribute (address + "preWait", "-1").reason == reason::typeMismatch);
    CHECK (document.setAttribute (address + "enabled", "yes").reason == reason::typeMismatch);
    CHECK (document.setAttribute (address + "nonsense", "x").reason == reason::badAddress);
    CHECK (document.setAttribute ("/godot/cue/ZZZZZZZZ/name", "x").reason == reason::badAddress);

    // Read-only means read-only, even though the value IS stored.
    const auto mount = document.createMount ("/wfs", "namespaces/wfs.json");
    REQUIRE (mount.ok);
    CHECK (document.setAttribute ("/godot/mount/" + mount.id + "/prefix", "/other").reason
             == reason::readOnly);

    // A refused write changes nothing.
    CHECK (document.getAttribute (address + "preWait") == std::string ("2.5"));
}

TEST_CASE ("document: a number keeps its VALUE through a write and a read")
{
    /*  Its value, not its spelling. A number has more than one valid text, and
        the canonical one is the shortest that reads back identically — so
        1000000 comes back as "1e+06" and 1.0 as "1". What must hold is that the
        double is the same double, which is what a replay compares. */
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    ShowDocument document;
    const auto list = document.createList ("Main");
    const auto cue = document.createCue (list.id, 0, "memo", "Timing");
    const auto address = "/godot/cue/" + cue.id + "/preWait";

    for (const char* written : { "0.5", "1.25", "0.1", "3.141592653589793",
                                 "1000000", "0.0000001", "1", "0" })
    {
        const std::string text { written };
        REQUIRE (document.setAttribute (address, text).ok);

        const auto readBack = document.getAttribute (address);
        REQUIRE (readBack.has_value());
        INFO ("wrote " << text << ", read back " << *readBack);

        const auto wanted = osc::parseDouble (text);
        const auto got = osc::parseDouble (*readBack);
        REQUIRE (wanted.has_value());
        REQUIRE (got.has_value());

        CHECK (std::memcmp (&*wanted, &*got, sizeof (double)) == 0);
    }
}

TEST_CASE ("document: the canonical spelling of a number is pinned")
{
    /*  Whatever a number is written as, canonicalising it twice gives the same
        text — that is the whole of what "canonical" claims. These are the
        spellings, recorded so a change to the formatter shows up here rather
        than as a mysterious diff in someone's show file.

        Note where the exponent appears and where it does not: every quantity a
        show actually carries — seconds, decibels, metres, hertz — is well
        inside the fixed range, so the scientific form is what you get for
        values no cue would have. */
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    ShowDocument document;
    const auto list = document.createList ("Main");
    const auto cue = document.createCue (list.id, 0, "memo", "Timing");
    const auto address = "/godot/cue/" + cue.id + "/preWait";

    const std::pair<const char*, const char*> spellings[] = {
        { "0",        "0" },
        { "0.0",      "0" },
        { "1",        "1" },
        { "1.0",      "1" },
        { "0.5",      "0.5" },
        { "2.50",     "2.5" },
        { "1e2",      "100" },
        { "3600",     "3600" },
        { "20000",    "20000" },
        { "1000000",  "1e+06" },
    };

    for (const auto& [written, canonical] : spellings)
    {
        REQUIRE (document.setAttribute (address, written).ok);
        INFO ("wrote " << std::string (written));
        CHECK (document.getAttribute (address) == std::string (canonical));
    }
}

//==============================================================================
TEST_CASE ("document commands: every structural edit is a named command")
{
    /*  PRD §4.11 — every gesture-reachable action exists as a named command. The
        document has no setter that is not one of these. */
    ShowDocument document;
    CommandRegistry registry;
    registerDocumentCommands (registry, document);

    for (const char* name : { "list.create", "cue.create", "mount.create",
                              "object.delete", "object.move", "node.set" })
    {
        INFO ("command: " << name);
        CHECK (registry.find (name) != nullptr);
    }
}

TEST_CASE ("document commands: a created identifier comes back in the applied arguments")
{
    /*  The property replay rests on. The caller omits the identifier, the engine
        draws one, and the LOG records the call with it — so replaying that
        record supplies the identifier rather than drawing a different one. */
    Engine engine;
    ShowDocument document;
    registerDocumentCommands (engine.commands(), document);

    engine.log().openInMemory ({});
    engine.submit (origin::cli, "list.create", { osc::Value::string ("Main") });
    engine.processTick (0);

    const auto parsed = LogFile::parse (engine.log().contents());
    REQUIRE (parsed.records.size() == 1);
    REQUIRE (parsed.records[0].kind == LogRecord::Kind::applied);
    REQUIRE (parsed.records[0].args.size() == 2);

    const auto id = parsed.records[0].args[1].getString();
    CHECK (Id::isValid (id));
    CHECK (document.findById (id).isValid());
}

TEST_CASE ("document commands: a rejection reaches the log with its reason")
{
    Engine engine;
    ShowDocument document;
    registerDocumentCommands (engine.commands(), document);

    engine.log().openInMemory ({});
    engine.submit (origin::cli, "node.set",
                   { osc::Value::string ("/godot/cue/ZZZZZZZZ/name"), osc::Value::string ("x") });
    engine.processTick (0);

    const auto parsed = LogFile::parse (engine.log().contents());
    REQUIRE (parsed.records.size() == 1);
    CHECK (parsed.records[0].kind == LogRecord::Kind::rejected);
    CHECK (parsed.records[0].reason == reason::badAddress);
    CHECK (engine.lastError().find (reason::badAddress) != std::string::npos);
}

//==============================================================================
TEST_CASE ("replay: a session that builds a cue list reproduces itself and its document")
{
    /*  Replay fixture #1. Two claims, and the second is the stronger one: the
        log reproduces itself record for record, AND the document the replay
        arrives at is byte-identical to the one the session saved. A log that
        replays to a different show would be a log worth nothing. */
    const auto record = [] (Engine& engine, ShowDocument& document)
    {
        engine.submit (origin::cli, "list.create", { osc::Value::string ("Main") });
        engine.processTick (0);

        const auto listId = document.root().getChildWithName ("Lists").getChild (0)
                              .getProperty ("id").toString().toStdString();

        engine.submit (origin::cli, "cue.create",
                       { osc::Value::string (listId), osc::Value::int32 (0),
                         osc::Value::string ("memo"), osc::Value::string ("House to half") });
        engine.submit (origin::cli, "cue.create",
                       { osc::Value::string (listId), osc::Value::int32 (1),
                         osc::Value::string ("group"), osc::Value::string ("Preshow") });
        engine.processTick (4);

        const auto groupId = document.root().getChildWithName ("Lists").getChild (0)
                               .getChild (1).getProperty ("id").toString().toStdString();

        engine.submit ("ws:127.0.0.1:51234", "cue.create",
                       { osc::Value::string (groupId), osc::Value::int32 (0),
                         osc::Value::string ("memo"), osc::Value::string ("Walk-in") });
        engine.processTick (9);

        const auto firstCueId = document.root().getChildWithName ("Lists").getChild (0)
                                  .getChild (0).getProperty ("id").toString().toStdString();

        engine.submit (origin::cli, "node.set",
                       { osc::Value::string ("/godot/cue/" + firstCueId + "/number"),
                         osc::Value::string ("1") });
        engine.submit (origin::cli, "node.set",
                       { osc::Value::string ("/godot/cue/" + firstCueId + "/preWait"),
                         osc::Value::string ("2.5") });
        engine.submit (origin::cli, "object.move",
                       { osc::Value::string (firstCueId), osc::Value::string (groupId),
                         osc::Value::int32 (0) });
        engine.submit (origin::cli, "node.set",
                       { osc::Value::string ("/godot/cue/ZZZZZZZZ/name"), osc::Value::string ("x") });
        engine.processTick (25);
    };

    Engine session;
    ShowDocument sessionDocument;
    registerDocumentCommands (session.commands(), sessionDocument);
    session.log().openInMemory ({});
    record (session, sessionDocument);

    const auto sessionXml = CanonicalXml::write (sessionDocument);
    const auto original = LogFile::parse (session.log().contents());

    REQUIRE (original.errors.empty());
    REQUIRE (original.records.size() == 8);

    Engine fresh;
    ShowDocument freshDocument;
    registerDocumentCommands (fresh.commands(), freshDocument);

    const auto result = replay (fresh, original);

    for (const auto& mismatch : result.mismatches)
        INFO (mismatch);

    CHECK (result.ok);
    CHECK (result.producedLog == session.log().contents());

    // And the document the replay arrived at is the same show.
    CHECK (CanonicalXml::write (freshDocument) == sessionXml);
}

//==============================================================================
TEST_CASE ("refers: a pointer at something that is not there is a warning, never a refusal")
{
    /*  THE `refers` COLUMN, and the rule it encodes. An identifier in a
        document is a pointer at another object, and until the column existed
        every one of them was checked by hand or not at all - the standby
        pointer had a function of its own and `fade/@target` had nothing.

        A WARNING AND NEVER A LOAD REFUSAL. PRD §3.8 makes a stop aimed at a cue
        that is not there a silent no-op during tech; `object.delete` repairs
        nothing referential, by design, because repairing it would mean deciding
        what somebody meant; and yesterday's saved show has to open tomorrow. So
        the file loads, validate says which pointer is dangling, and a cue that
        is actually fired fails its run. */
    ShowDocument document;

    const auto listId = document.createList ("Main").id;
    const auto target = document.createCue (listId, 0, "media", "Thunder").id;
    const auto fade = document.createCue (listId, 1, "fade", "Under").id;

    REQUIRE (document.setAttribute ("/godot/cue/" + fade + "/target", target).ok);
    CHECK (document.warnings().empty());

    /*  The cue it was aimed at is deleted, which the document allows and does
        not repair - the fade keeps pointing at a thing that has gone. */
    REQUIRE (document.remove (target).ok);

    const auto problems = document.warnings();

    /*  A WARNING AND NOT A REFUSAL, which is the property this is here for:
        the show still loads. */
    CHECK (document.validate().empty());

    REQUIRE (problems.size() == 1);
    INFO (problems[0]);
    CHECK (problems[0].find (target) != std::string::npos);
    CHECK (problems[0].find ("target") != std::string::npos);
}

TEST_CASE ("refers: a pointer at the wrong KIND of thing is caught too")
{
    /*  HALF A CHECK IS WORSE THAN NONE. A fade whose target is a bus would
        otherwise pass validate and fail at half past seven with a message about
        a run rather than about a show. The column says `cue`, so the thing
        found has to be one. */
    ShowDocument document;

    const auto listId = document.createList ("Main").id;
    const auto fade = document.createCue (listId, 0, "fade", "Under").id;

    /*  A bus, which is an object with an identifier and is not a cue. */
    auto audio = document.root().getChildWithName ("Audio");
    REQUIRE (audio.isValid());

    const auto busId = document.ids().generate();

    juce::ValueTree bus { "Bus" };
    bus.setProperty (juce::Identifier ("id"), juce::String (busId), nullptr);
    bus.setProperty (juce::Identifier ("name"), "Main L/R", nullptr);
    audio.appendChild (bus, nullptr);

    /*  Written past setAttribute, which would refuse it: the point is a file
        somebody hand-edited, or one written by an older build. */
    auto cue = document.findById (fade);
    cue.setProperty (juce::Identifier ("target"), juce::String (busId), nullptr);

    const auto problems = document.warnings();

    CHECK (document.validate().empty());

    REQUIRE (problems.size() == 1);
    INFO (problems[0]);
    CHECK (problems[0].find ("bus") != std::string::npos);
    CHECK (problems[0].find ("not a cue") != std::string::npos);
}

TEST_CASE ("refers: an empty pointer is a resting state and not a dangling one")
{
    /*  A list with no standby and a fade with no target yet are both things
        somebody is in the middle of making. §3.5 says an empty pointer is a
        resting value; a warning about one would be a warning about every show
        anybody has started writing. */
    ShowDocument document;

    const auto listId = document.createList ("Main").id;
    document.createCue (listId, 0, "fade", "Under");

    CHECK (document.warnings().empty());
    CHECK (document.validate().empty());
}

TEST_CASE ("refers: the table is what says which attributes point at things")
{
    /*  The five the column declares, read back off the schema rather than
        re-listed here - a second list would be the thing this column exists to
        remove. */
    const auto& schema = Schema::instance();

    const auto pointsAt = [&schema] (const char* element, const char* attribute)
    {
        const auto* row = schema.attribute (element, attribute);
        return row != nullptr ? std::string (row->refers()) : std::string ("(no such row)");
    };

    CHECK (pointsAt ("List", "standby") == "cue");
    CHECK (pointsAt ("Fade", "target") == "cue");
    CHECK (pointsAt ("Stop", "target") == "cue");
    CHECK (pointsAt ("Route", "bus") == "bus");
    CHECK (pointsAt ("Midi", "port") == "port");

    /*  And a value that is not a pointer says so by saying nothing. */
    CHECK (pointsAt ("Cue", "name").empty());
    CHECK (pointsAt ("Media", "file").empty());
}

//==============================================================================
TEST_CASE ("show revision: an edit to the show moves it, and a standby does not")
{
    /*  Plan decision 4, pinned where it would be broken. `/godot/document/dirty`
        compares this counter with the last save's, so a standby that moved it
        would light the dot on every GO - and an operator told there are unsaved
        changes after every GO has stopped reading the dot by the second act.

        Through the COMMANDS, because the claim is about what a client's gesture
        does and a GO moves the standby through the same door `standby.set`
        does. `revision()` is checked alongside, so a standby that moved nothing
        at all cannot pass for one that moved only the right counter. */
    auto document = loaded ("canonical.xml");

    Engine engine;
    cue::Focus focus;
    registerDocumentCommands (engine.commands(), document);
    cue::registerCueCommands (engine.commands(), document, focus);

    std::int64_t nextTick = 0;

    const auto applyOne = [&engine, &nextTick] (const std::string& command,
                                                std::vector<osc::Value> args)
    {
        REQUIRE (engine.submit (origin::cli, command, std::move (args)));
        return engine.processTick (nextTick++).applied;
    };

    const auto showAtOpen = document.showRevision();
    const auto allAtOpen = document.revision();

    // --- a standby is the operator's position, not the show ------------------
    REQUIRE (applyOne ("standby.set", { osc::Value::string ("B3N8R5TW") }) == 1);
    CHECK (document.revision() != allAtOpen);
    CHECK (document.showRevision() == showAtOpen);

    // ...and neither is the next one, which is the move GO itself makes.
    const auto allBeforeNext = document.revision();
    REQUIRE (applyOne ("standby.next", {}) == 1);
    CHECK (document.revision() != allBeforeNext);
    CHECK (document.showRevision() == showAtOpen);

    // --- a name is what someone decided --------------------------------------
    REQUIRE (applyOne ("node.set", { osc::Value::string ("/godot/cue/B3N8R5TW/name"),
                                     osc::Value::string ("Renamed since the file was read") }) == 1);

    const auto afterRename = document.showRevision();
    CHECK (afterRename != showAtOpen);

    // --- and the structure is the show, whichever door changed it ------------
    const auto added = document.createCue ("7K2QM9X4", 0, "memo", "Added");
    REQUIRE (added.ok);

    const auto afterAdd = document.showRevision();
    CHECK (afterAdd != afterRename);

    REQUIRE (document.move (added.id, "7K2QM9X4", 2).ok);
    const auto afterMove = document.showRevision();
    CHECK (afterMove != afterAdd);

    REQUIRE (document.remove (added.id).ok);
    CHECK (document.showRevision() != afterMove);
}

TEST_CASE ("show revision: a load is a change, and a value the schema does not know is guessed as one")
{
    ShowDocument document;
    const auto fresh = document.showRevision();

    /*  Never nought, so a session's nought can mean "never saved" without
        colliding with a document that has simply never been touched. */
    CHECK (fresh != 0);

    /*  A load replaces the root wholesale through `adopt`, and the verbs stamp
        their session AFTER it for exactly this reason. */
    REQUIRE (CanonicalXml::read (fixture ("canonical.xml"), document).ok);

    const auto afterLoad = document.showRevision();
    CHECK (afterLoad != fresh);

    /*  Nothing but a test can write an attribute the schema has no row for -
        every door refuses one - and when the counter has to guess which file
        such a value belongs in, it guesses the show. A false "unsaved" costs
        somebody a save; a false "saved" costs them a show. */
    document.root().setProperty ("notInTheTable", 1, nullptr);
    CHECK (document.showRevision() != afterLoad);
}

TEST_CASE ("show revision: a moved document keeps its count, and keeps counting")
{
    /*  The move is written by hand and moves every member by name, so a
        counter added to the class and not to the move would restart silently -
        and a session holding the old number would then disagree with the
        document about whether there is anything to save. */
    ShowDocument original;
    REQUIRE (original.createList ("Main").ok);
    REQUIRE (original.createList ("Second").ok);

    const auto counted = original.showRevision();
    REQUIRE (counted != ShowDocument().showRevision());

    ShowDocument moved { std::move (original) };
    CHECK (moved.showRevision() == counted);

    // It still hears its own tree, which is the other half of a careful move.
    REQUIRE (moved.createList ("Third").ok);
    const auto afterEdit = moved.showRevision();
    CHECK (afterEdit != counted);

    ShowDocument assigned;
    assigned = std::move (moved);
    CHECK (assigned.showRevision() == afterEdit);
}

//==============================================================================
/*  THE EDIT LOCK (decision W, namespace draft §14.11).

    Every case below goes through the COMMANDS where the claim is about what a
    client's gesture does, because the lock is a promise made to every client
    at once and the commands are what every client sends. The document's own
    calls are used where the claim is about the document - that a refusal
    changed nothing, that a create which makes a container on demand asks
    before it makes it.
*/
namespace
{
    const std::string lockAddress { "/godot/document/locked" };
    const std::string mainList { "7K2QM9X4" };
    const std::string houseToHalf { "B3N8R5TW" };
    const std::string preshow { "D9FH2JKA" };
    const std::string wfsMount { "G1JS4VWE" };

    bool endsWith (const std::string& whole, const std::string& tail)
    {
        return whole.size() >= tail.size()
            && whole.compare (whole.size() - tail.size(), tail.size(), tail) == 0;
    }

    /*  The hand-authored show, the document's commands, the standby's, and a
        stand-in for the mounts - a foreign write that counts what reached it
        rather than sending it anywhere. One command per tick, so each result
        is that command's and nobody else's. */
    struct LockRig
    {
        LockRig()
        {
            registerDocumentCommands (engine.commands(), document,
                                      [this] (const std::string&, const osc::Value& value)
                                      {
                                          ++foreignWrites;
                                          return Outcome::ok ({ value });
                                      });

            cue::registerCueCommands (engine.commands(), document, focus);
            engine.log().openInMemory ({});
        }

        Engine::TickResult run (const std::string& name, std::vector<osc::Value> args = {})
        {
            REQUIRE (engine.submit (origin::cli, name, std::move (args)));
            return engine.processTick (nextTick++);
        }

        Engine::TickResult setLocked (bool on)
        {
            return run ("node.set", { osc::Value::string (lockAddress), osc::Value::boolean (on) });
        }

        std::string standby() const
        {
            return document.getAttribute ("/godot/list/" + mainList + "/standby")
                     .value_or (std::string ("<unresolved>"));
        }

        ShowDocument document = loaded ("canonical.xml");
        cue::Focus focus;
        Engine engine;
        int foreignWrites = 0;
        std::int64_t nextTick = 0;
    };

    std::string bytesOf (const juce::File& file)
    {
        juce::MemoryBlock block;
        REQUIRE_MESSAGE (file.loadFileAsData (block), "cannot read " << file.getFullPathName());

        std::string out;

        /*  Without the carriage returns, for the reason `fixture` above gives:
            a checkout that turned the committed file into CRLF must test the
            same thing as one that did not. The writer's own endings are pinned
            elsewhere. */
        for (const char c : std::string (static_cast<const char*> (block.getData()), block.getSize()))
            if (c != '\r')
                out.push_back (c);

        return out;
    }
}

TEST_CASE ("edit lock: a locked show refuses every edit to it, and the refusal changes nothing")
{
    LockRig rig;

    CHECK_FALSE (rig.document.isLocked());
    REQUIRE (rig.setLocked (true).applied == 1);
    REQUIRE (rig.document.isLocked());

    const auto showBefore = CanonicalXml::write (rig.document);
    const auto revisionBefore = rig.document.revision();
    const auto showRevisionBefore = rig.document.showRevision();

    struct Attempt
    {
        const char* command;
        std::vector<osc::Value> args;
    };

    /*  A create, a write to a value show.xml records, a move and a delete:
        all four of the document's doors. Each with arguments that would be
        applied on an unlocked show - the end of this case proves it - so the
        only thing wrong with any of them is the lock. In an order that can be
        applied again once it is lifted, which is why the cue is renamed and
        moved before it is deleted. */
    const std::vector<Attempt> attempts {
        { "cue.create",    { osc::Value::string (mainList), osc::Value::int32 (0),
                             osc::Value::string ("memo"), osc::Value::string ("Added under the lock") } },
        { "node.set",      { osc::Value::string ("/godot/cue/" + houseToHalf + "/name"),
                             osc::Value::string ("Renamed under the lock") } },
        { "object.move",   { osc::Value::string (houseToHalf), osc::Value::string (mainList),
                             osc::Value::int32 (1) } },
        { "object.delete", { osc::Value::string (houseToHalf) } },
    };

    for (const auto& attempt : attempts)
    {
        INFO ("command: " << attempt.command);

        const auto result = rig.run (attempt.command, attempt.args);
        CHECK (result.applied == 0);
        CHECK (result.rejected == 1);

        /*  The line an operator reads at /godot/engine/lastError: which
            gesture was refused, and that the show being locked is why. */
        CHECK (endsWith (rig.engine.lastError(), std::string ("locked ") + attempt.command));
    }

    // --- and the show is exactly what it was --------------------------------
    CHECK (CanonicalXml::write (rig.document) == showBefore);
    CHECK (rig.document.revision() == revisionBefore);
    CHECK (rig.document.showRevision() == showRevisionBefore);

    /*  THE LOG SAYS IT IN THE SAME WORD, because the reason is part of the log
        format and a replay has to reproduce the refusal as a refusal. */
    const auto parsed = LogFile::parse (rig.engine.log().contents());
    std::size_t lockedRecords = 0;

    for (const auto& record : parsed.records)
        if (record.kind == LogRecord::Kind::rejected && record.reason == reason::locked)
            ++lockedRecords;

    CHECK (lockedRecords == attempts.size());

    // --- lifted, every one of them is applied ------------------------------
    REQUIRE (rig.setLocked (false).applied == 1);

    for (const auto& attempt : attempts)
    {
        INFO ("command, unlocked: " << attempt.command);
        CHECK (rig.run (attempt.command, attempt.args).applied == 1);
    }
}

TEST_CASE ("edit lock: where the operator is standing is not the show, so a locked show still moves it, and still unlocks")
{
    /*  The state half: the standby GO moves, the focus, and the lock's own
        release. A lock that refused these would lock the operator out of GO
        and out of unlocking, which is the opposite of show mode. */
    LockRig rig;

    const auto showAtOpen = rig.document.showRevision();

    REQUIRE (rig.setLocked (true).applied == 1);

    /*  THE LOCK ITSELF IS NOT AN EDIT TO THE SHOW, and does not light the
        dot: an operator told there are unsaved changes because they locked
        the show would learn to ignore the dot by the interval. */
    CHECK (rig.document.showRevision() == showAtOpen);

    const auto showBefore = CanonicalXml::write (rig.document);

    CHECK (rig.run ("standby.set", { osc::Value::string (houseToHalf) }).applied == 1);
    CHECK (rig.standby() == houseToHalf);

    // The move GO itself makes.
    CHECK (rig.run ("standby.next").applied == 1);
    CHECK (rig.standby() != houseToHalf);

    // The same position written as a client writes any node.
    CHECK (rig.run ("node.set", { osc::Value::string ("/godot/list/" + mainList + "/standby"),
                                  osc::Value::string (houseToHalf) }).applied == 1);
    CHECK (rig.standby() == houseToHalf);

    CHECK (rig.run ("node.set", { osc::Value::string ("/godot/list/focus"),
                                  osc::Value::string (mainList) }).applied == 1);

    /*  A MOUNTED WRITE NEVER REACHES THE DOCUMENT, so there is no door on its
        way to refuse it: somebody in row H riding a level on a processor
        because that is where the show sounds wrong is mixing, not editing
        (PRD 3.17). */
    CHECK (rig.run ("node.set", { osc::Value::string ("/wfs/input/1/gain"),
                                  osc::Value::float32 (0.5f) }).applied == 1);
    CHECK (rig.foreignWrites == 1);

    // None of it touched what show.xml records.
    CHECK (CanonicalXml::write (rig.document) == showBefore);
    CHECK (rig.document.showRevision() == showAtOpen);

    // --- and the release -----------------------------------------------------
    REQUIRE (rig.setLocked (false).applied == 1);
    CHECK_FALSE (rig.document.isLocked());

    CHECK (rig.run ("cue.create", { osc::Value::string (mainList), osc::Value::int32 (0),
                                    osc::Value::string ("memo"),
                                    osc::Value::string ("Added once it was lifted") }).applied == 1);
}

TEST_CASE ("edit lock: the refusal arrives before the value is parsed, and the lock itself is never refused as locked")
{
    LockRig rig;
    REQUIRE (rig.setLocked (true).applied == 1);

    /*  A BADLY TYPED WRITE TO THE SHOW ON A LOCKED SHOW IS `locked`, not
        `type-mismatch`: the corrected value would be refused as well, so the
        answer worth reading first is that the show is fixed. Answered the
        other way round, it would send an operator to look at their encoder. */
    CHECK (rig.run ("node.set", { osc::Value::string ("/godot/cue/" + houseToHalf + "/enabled"),
                                  osc::Value::string ("perhaps") }).rejected == 1);
    CHECK (endsWith (rig.engine.lastError(), "locked node.set"));

    /*  AND THE LOCK'S OWN ROW IS NEVER `locked`, since it is a state row: an
        integer 1 is a type mismatch whichever way the lock stands (namespace
        draft §14.2 says why the integer is not a boolean). */
    CHECK (rig.run ("node.set", { osc::Value::string (lockAddress),
                                  osc::Value::int32 (1) }).rejected == 1);
    CHECK (endsWith (rig.engine.lastError(), "type-mismatch node.set"));
    CHECK (rig.document.isLocked());

    // The text spelling is the same write as the boolean.
    CHECK (rig.run ("node.set", { osc::Value::string (lockAddress),
                                  osc::Value::string ("false") }).applied == 1);
    CHECK_FALSE (rig.document.isLocked());

    // Unlocked, the badly typed write is what it always was.
    CHECK (rig.run ("node.set", { osc::Value::string ("/godot/cue/" + houseToHalf + "/enabled"),
                                  osc::Value::string ("perhaps") }).rejected == 1);
    CHECK (endsWith (rig.engine.lastError(), "type-mismatch node.set"));
}

TEST_CASE ("edit lock: a locked channel.create leaves no rack behind and does not move the show")
{
    /*  The one create that changes the document on its way to the door: it
        makes the `Rack` container on demand and only then inserts. A lock
        asked only at the door would leave an empty rack in a locked show,
        light the dirty dot, and then refuse. */
    LockRig rig;

    const auto rackOf = [&rig]
    {
        return rig.document.root().getChildWithName ("Audio").getChildWithName ("Rack");
    };

    REQUIRE_FALSE (rackOf().isValid());
    REQUIRE (rig.setLocked (true).applied == 1);

    const auto revisionBefore = rig.document.revision();
    const auto showRevisionBefore = rig.document.showRevision();

    CHECK (rig.run ("channel.create", { osc::Value::string ("mono") }).rejected == 1);
    CHECK (endsWith (rig.engine.lastError(), "locked channel.create"));

    CHECK_FALSE (rackOf().isValid());
    CHECK (rig.document.revision() == revisionBefore);
    CHECK (rig.document.showRevision() == showRevisionBefore);

    // The same, asked of the document rather than of the command.
    const auto edit = rig.document.createRackChannel ("mono");
    CHECK_FALSE (edit.ok);
    CHECK (edit.reason == std::string (reason::locked));
    CHECK_FALSE (rackOf().isValid());
    CHECK (rig.document.revision() == revisionBefore);

    // Lifted, the identical command makes both the rack and the channel.
    REQUIRE (rig.setLocked (false).applied == 1);
    CHECK (rig.run ("channel.create", { osc::Value::string ("mono") }).applied == 1);
    CHECK (rackOf().isValid());
    CHECK (rackOf().getNumChildren() == 1);
}

TEST_CASE ("edit lock: every create is refused under the lock, and each is applied once it is lifted")
{
    /*  The ten creates, asked of the document directly with arguments that are
        good - which the second half proves - so what refuses each one is the
        lock and nothing else. The objects they need to hang from are made
        before the lock goes on. */
    auto document = loaded ("canonical.xml");

    const auto media = document.createCue (mainList, 0, "media", "The bed");
    REQUIRE (media.ok);

    const auto slot = document.createSlot (wfsMount, "/wfs/input/1");
    REQUIRE (slot.ok);

    const auto channel = document.createRackChannel ("mono");
    REQUIRE (channel.ok);

    const std::vector<std::pair<const char*, std::function<EditResult()>>> creates {
        { "list",    [&document] { return document.createList ("Locked out"); } },
        { "cue",     [&document] { return document.createCue (mainList, 0, "memo", "Locked out"); } },
        { "route",   [&document, &media] { return document.createRoute (media.id, "J3MT5XYA"); } },
        { "range",   [&document, &media] { return document.createRange (media.id, 0.0, 1.0); } },
        { "slot",    [&document] { return document.createSlot (wfsMount, "/wfs/input/2"); } },
        { "channel", [&document] { return document.createRackChannel ("stereo"); } },
        { "feed",    [&document, &media, &slot] { return document.createFeed (media.id, slot.id); } },
        { "insert",  [&document, &media, &channel] { return document.createInsert (media.id, channel.id); } },
        { "trigger", [&document, &media] { return document.createTrigger (media.id, "osc"); } },
        { "mount",   [&document] { return document.createMount ("/ext/locked", "namespaces/locked.json"); } },
    };

    REQUIRE (document.setAttribute (lockAddress, "true").ok);

    const auto showBefore = CanonicalXml::write (document);
    const auto revisionBefore = document.revision();

    for (const auto& [what, create] : creates)
    {
        INFO ("create: " << what);

        const auto edit = create();
        CHECK_FALSE (edit.ok);
        CHECK (edit.reason == std::string (reason::locked));
    }

    CHECK (CanonicalXml::write (document) == showBefore);
    CHECK (document.revision() == revisionBefore);

    REQUIRE (document.setAttribute (lockAddress, "false").ok);

    for (const auto& [what, create] : creates)
    {
        INFO ("create, unlocked: " << what);

        const auto edit = create();
        CHECK (edit.ok);
        CHECK (edit.reason.empty());
    }
}

TEST_CASE ("edit lock: an idempotent create that finds what it was asked for is applied, and one that would insert is refused")
{
    /*  `group.role` and `list.persistent` answer with the child that already
        exists before they reach a door, so on a group that has its footer they
        change nothing and are applied under the lock. That is the rule - an
        edit that would CHANGE the show is refused - and not an exemption:
        asserting that every edit command refuses under the lock would find
        these two and be red. */
    LockRig rig;

    const auto footer = rig.document.createRole (preshow, "footer");
    REQUIRE (footer.ok);

    const auto persistent = rig.document.createPersistent (mainList);
    REQUIRE (persistent.ok);

    REQUIRE (rig.setLocked (true).applied == 1);
    const auto showBefore = CanonicalXml::write (rig.document);

    CHECK (rig.run ("group.role", { osc::Value::string (preshow),
                                    osc::Value::string ("footer") }).applied == 1);
    CHECK (rig.run ("list.persistent", { osc::Value::string (mainList) }).applied == 1);

    const auto again = rig.document.createRole (preshow, "footer");
    CHECK (again.ok);
    CHECK (again.id == footer.id);

    // The group has no header, so asking for one would insert: refused.
    CHECK (rig.run ("group.role", { osc::Value::string (preshow),
                                    osc::Value::string ("header") }).rejected == 1);
    CHECK (endsWith (rig.engine.lastError(), "locked group.role"));

    CHECK (CanonicalXml::write (rig.document) == showBefore);
}

TEST_CASE ("edit lock: the lock is kept in state.xml and never in show.xml, and a released lock leaves nothing there")
{
    auto document = loaded ("canonical.xml");
    REQUIRE (document.setAttribute (lockAddress, "true").ok);

    const auto state = EphemeralState::write (document);
    const auto show = CanonicalXml::write (document);

    INFO ("state.xml:\n" << state);

    /*  A CONTAINER ENTRY, with no identifier, because the `Show` root is a
        container - one of it, addressed as `/godot/document` - and that branch
        of EphemeralState has carried `Lists focus` since Phase 3. */
    CHECK (state.find ("<Show locked=\"true\"/>") != std::string::npos);
    CHECK (show.find ("locked") == std::string::npos);

    ShowDocument reopened;
    REQUIRE (CanonicalXml::read (show, reopened).ok);

    // show.xml alone does not carry it...
    CHECK_FALSE (reopened.isLocked());

    // ...state.xml does, restored through the one write path.
    const auto restored = EphemeralState::read (state, reopened);
    INFO ("problems: " << (restored.problems.empty() ? std::string ("none")
                                                     : restored.problems.front()));
    CHECK (restored.ok);
    CHECK (reopened.isLocked());

    /*  THE RELEASE IS OMITTED, NOT WRITTEN. The state writer goes through
        CanonicalXml::attributeText, which leaves out an attribute whose text is
        the row's default, and `locked` defaults to false - so an unlocked show
        leaves nothing in state.xml, whether or not it was ever locked. For
        canonical.xml, which has no other state to remember, that is the bare
        root and not one entry more. */
    REQUIRE (document.setAttribute (lockAddress, "false").ok);

    const auto released = EphemeralState::write (document);
    INFO ("released state.xml:\n" << released);
    CHECK (released.find ("locked") == std::string::npos);
    CHECK (released == "<State formatVersion=\"1\"/>\n");

    /*  A FALSE IN THE FILE STILL UNLOCKS. The writer never produces one, but
        the grammar and the reader both accept it, and reading it into a LOCKED
        document has to unlock it - the state half getting through a lock
        exactly as a restore needs it to. The string is written by hand because
        no save of ours would ever write it. */
    const std::string handWritten = "<State formatVersion=\"1\">\n"
                                    "  <Show locked=\"false\"/>\n"
                                    "</State>\n";

    REQUIRE (reopened.isLocked());

    const auto unlocked = EphemeralState::read (handWritten, reopened);
    INFO ("problems: " << (unlocked.problems.empty() ? std::string ("none")
                                                     : unlocked.problems.front()));
    CHECK (unlocked.ok);
    CHECK_FALSE (reopened.isLocked());
}

TEST_CASE ("edit lock: the locked fixture bundle opens locked, refuses an edit, and saves and reopens locked")
{
    /*  THE SURVIVING-A-RESTART HALF, on a bundle folder rather than on two
        strings: a show locked at 20:40 whose engine was restarted at 20:44
        comes back locked, or the first thing a rebooted engine does is
        un-protect a running performance (plan decision 6). */
    const juce::File fixtureFolder { juce::String (std::string (WFG_TEST_FIXTURES_DIR))
                                       + "/bundles/locked" };

    REQUIRE_MESSAGE (fixtureFolder.isDirectory(),
                     "missing fixture bundle: " << fixtureFolder.getFullPathName());

    ShowDocument document;
    const auto opened = Bundle::open (fixtureFolder, document);

    INFO ("problems: " << (opened.problems.empty() ? std::string ("none")
                                                   : opened.problems.front()));
    REQUIRE (opened.ok);
    CHECK (opened.problems.empty());
    CHECK (document.isLocked());

    const auto refused = document.createCue ("K5ACT001", 0, "memo", "Added to a locked bundle");
    CHECK_FALSE (refused.ok);
    CHECK (refused.reason == std::string (reason::locked));

    // --- a save is not an edit, and the lock goes to disk with the show -----
    const auto scratch = juce::File::getSpecialLocation (juce::File::tempDirectory)
                           .getChildFile ("wfg-tests")
                           .getChildFile (juce::Uuid().toDashedString());

    struct Cleanup
    {
        juce::File folder;
        ~Cleanup() { folder.deleteRecursively(); }
    } cleanup { scratch };

    const auto savedFolder = scratch.getChildFile ("locked");
    REQUIRE (Bundle::save (savedFolder, document).ok);

    /*  THE SAME BYTES THE FIXTURE HOLDS, which is what makes the fixture a
        canonical one rather than one the engine merely tolerates. */
    CHECK (bytesOf (Bundle::stateFile (savedFolder)) == bytesOf (Bundle::stateFile (fixtureFolder)));
    CHECK (bytesOf (Bundle::showFile (savedFolder)) == bytesOf (Bundle::showFile (fixtureFolder)));

    ShowDocument reopened;
    REQUIRE (Bundle::open (savedFolder, reopened).ok);
    CHECK (reopened.isLocked());
}
