/*
    This file is part of Go.dot — https://github.com/pob31/go.dot

    Copyright (C) 2026 Pierre-Olivier Boulant

    Go.dot is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later
    version. Go.dot is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
    (LICENSE, at the repository root) for more details.

    SPDX-License-Identifier: GPL-3.0-or-later
*/

/*
    The `/godot` namespace: what it contains, what it publishes, what it sends
    and to whom.

    A serialisation surface, so every case here runs under fr_FR as well as C.

    THE GOLDEN IS COMMITTED AND WAS CHECKED BY HAND, field by field, against the
    rows of docs/parameters/godot-parameters.csv and the cue in the bundle
    fixture. It is not generated by the code it tests: a golden written by the
    thing under test proves only that the thing agrees with itself, which is
    exactly the failure a published reply must not have. It covers one cue
    rather than the whole tree because the whole tree is seven hundred lines,
    and a golden nobody can read is a golden nobody will check when it changes.
*/

#include <3rd_party/doctest/tracktion_doctest.hpp>

#include "TestSupport.h"

#include <wfg/engine/Engine.h>
#include <wfg/engine/audio/MediaInfo.h>
#include <wfg/engine/audio/Timbre.h>
#include <wfg/engine/document/Bundle.h>
#include <wfg/engine/document/DocumentCommands.h>
#include <wfg/engine/cue/Run.h>
#include <wfg/engine/tree/Mount.h>
#include <wfg/engine/tree/OscQueryJson.h>
#include <wfg/engine/tree/ParameterTree.h>
#include <wfg/engine/tree/TreeCommands.h>

#include <juce_core/juce_core.h>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>

using namespace wfg;
using namespace wfg::tree;

namespace
{
    juce::File fixtureBundle()
    {
        const juce::File folder { juce::String (std::string (WFG_TEST_FIXTURES_DIR))
                                    + "/bundles/minimal" };

        REQUIRE_MESSAGE (folder.isDirectory(), "missing fixture bundle: "
                                                 << folder.getFullPathName());
        return folder;
    }

    std::string readFixture (const std::string& name)
    {
        const juce::File file { juce::String (std::string (WFG_TEST_FIXTURES_DIR))
                                  + "/tree/" + juce::String (name) };

        REQUIRE_MESSAGE (file.existsAsFile(), "missing fixture: " << file.getFullPathName());

        juce::MemoryBlock block;
        REQUIRE (file.loadFileAsData (block));

        /*  Normalised, so a checkout that turned the fixture into CRLF tests
            the same thing as one that did not. The WRITER's line endings are
            pinned separately, below. */
        auto text = std::string (static_cast<const char*> (block.getData()), block.getSize());
        text.erase (std::remove (text.begin(), text.end(), '\r'), text.end());
        return text;
    }

    /*  Engine, document, commands and tree, wired exactly as `wfg tree` and
        (from PR 1.10) `serve` wire them. Held together so a test can say what
        it is about rather than repeating six lines of assembly. */
    struct Rig
    {
        Rig()
        {
            REQUIRE (doc::Bundle::open (fixtureBundle(), document).ok);
            doc::registerDocumentCommands (engine.commands(), document);
            registerTreeCommands (engine.commands(), touches);
        }

        /** Applies one command through the engine, as a client would. */
        Engine::TickResult apply (std::int64_t tick, const std::string& origin,
                                  const std::string& command, std::vector<osc::Value> args = {})
        {
            REQUIRE (engine.submit (origin, command, std::move (args)));
            const auto result = engine.processTick (tick);
            parameters.markStale();
            return result;
        }

        std::shared_ptr<const TreeSnapshot> publish (std::int64_t tick)
        {
            EngineState state;
            state.version = "test";
            state.tick = tick;
            state.errorCount = engine.errorCount();
            state.lastError = engine.lastError();
            state.documentRevision = document.showRevision();   // as serve's after-tick does
            return parameters.publish (tick, state);
        }

        Engine engine;
        doc::ShowDocument document;
        TouchTable touches;

        /*  No mounts loaded here on purpose: these cases are about /godot, and
            MountTests covers what somebody else's namespace adds. An empty
            table is a valid one. */
        MountTable mounts;
        cue::RunTable runs;
        ParameterTree parameters { document, engine.commands(), mounts, runs };
    };

    const std::string announce = "/godot/cue/F7HR8TVD";       // the second cue of the Preshow group
    const std::string preshow  = "/godot/cue/D9FH2JKA";       // the group that holds it
    const std::string mainList = "/godot/list/7K2QM9X4";
}

//==============================================================================
TEST_CASE ("tree: one cue serialises to the committed golden, byte for byte")
{
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    /*  Every field of this was read against the CSV row it comes from: the
        type tag, the access number, the range, the unit, the description and
        all four GODOT declarations. Under fr_FR too, because the two numbers
        in it - 1.5 and the MIN of 0 - go through the same formatter as the
        document, and a formatter that consulted the locale would put a comma
        in a published reply. */
    Rig rig;
    const auto snapshot = rig.publish (0);

    CHECK (OscQueryJson::describe (*snapshot, announce) == readFixture ("cue-F7HR8TVD.json"));
}

TEST_CASE ("tree: an address that names nothing produces nothing")
{
    Rig rig;
    const auto snapshot = rig.publish (0);

    CHECK (OscQueryJson::describe (*snapshot, "/godot/cue/ZZZZZZZZ").empty());
    CHECK (OscQueryJson::describe (*snapshot, "/nope").empty());
}

TEST_CASE ("tree: the root holds one of each subtree, and every address exactly once")
{
    Rig rig;
    const auto snapshot = rig.publish (0);

    for (const auto& address : { "/", "/godot", "/godot/engine", "/godot/document",
                                 "/godot/list", "/godot/cue", "/godot/mount", "/godot/cmd" })
    {
        INFO ("address: " << address);
        const auto* node = snapshot->find (address);

        REQUIRE (node != nullptr);
        CHECK (node->isContainer());
    }

    /*  The snapshot is two halves searched one after the other, so an address
        in both would make the answer depend on which was reached first. */
    std::set<std::string> seen;

    for (const auto* node : snapshot->all())
    {
        INFO ("address: " << node->address);
        CHECK (seen.insert (node->address).second);
    }

    CHECK (seen.size() == snapshot->size());
}

TEST_CASE ("tree: all() comes back in address order")
{
    Rig rig;
    const auto snapshot = rig.publish (0);
    const auto nodes = snapshot->all();

    REQUIRE (nodes.size() > 1);

    for (std::size_t i = 1; i < nodes.size(); ++i)
    {
        INFO ("at " << nodes[i]->address);
        CHECK (nodes[i - 1]->address < nodes[i]->address);
    }
}

//==============================================================================
TEST_CASE ("tree: the derived values come from the structure, not from the file")
{
    /*  kind, parent, index and order are `persist=none`: the document refuses
        to store them because the structure already says them, and the tree is
        what puts them back on the wire. If they were stored, this is where the
        second copy would start disagreeing. */
    Rig rig;
    const auto snapshot = rig.publish (0);

    const auto valueAt = [&snapshot] (const std::string& address)
    {
        const auto* node = snapshot->find (address);
        REQUIRE (node != nullptr);
        REQUIRE (node->soleValue().has_value());
        return *node->soleValue();
    };

    CHECK (valueAt (announce + "/kind") == osc::Value::string ("memo"));
    CHECK (valueAt (preshow + "/kind") == osc::Value::string ("group"));

    CHECK (valueAt (announce + "/parent") == osc::Value::string ("D9FH2JKA"));
    CHECK (valueAt (announce + "/index") == osc::Value::int32 (1));

    CHECK (valueAt (preshow + "/order") == osc::Value::string ("E4GP6QSC F7HR8TVD"));
    CHECK (valueAt (mainList + "/order") == osc::Value::string ("B3N8R5TW D9FH2JKA"));
}

TEST_CASE ("tree: a collection carries nodes of its own, beside its members")
{
    /*  `/godot/list/order` and `/godot/list/focus` sit at the CONTAINER address,
        beside `/godot/list/<id>/standby`. Three segments rather than four is
        what tells them apart, and the word stays `list` for both on purpose:
        they are one container read two ways, and a client walking the tree
        should not have to learn that the collection is spelled differently from
        the things in it.

        The same shape gives `/godot/run/order`, which is a roster rather than a
        stored value - it lists exactly what is published, retention included. */
    Rig rig;
    const auto snapshot = rig.publish (0);

    const auto valueAt = [&snapshot] (const std::string& address)
    {
        const auto* node = snapshot->find (address);
        REQUIRE_MESSAGE (node != nullptr, "no node at " << address);
        REQUIRE (node->soleValue().has_value());
        return *node->soleValue();
    };

    CHECK (valueAt ("/godot/list/order") == osc::Value::string ("7K2QM9X4"));
    CHECK (valueAt ("/godot/list/focus") == osc::Value::string (""));
    CHECK (valueAt ("/godot/run/order") == osc::Value::string (""));

    /*  A COLLECTION IS BOTH A CONTAINER AND A NODE, which is legitimate and is
        why `order` exists: a client cannot assume every child of `/godot/run` is
        a run, so the roster is the node that answers the question. The
        black-box driver found this the honest way - it listed the container's
        children before the first GO and reported a run called "order". */
    CHECK (snapshot->find ("/godot/list/7K2QM9X4/standby") != nullptr);
    CHECK (snapshot->find ("/godot/list") != nullptr);
}

TEST_CASE ("tree: a header's cues are cues, and are not members of the group")
{
    /*  A header and a footer are ordinary cue lists (§3.6), so what is in one
        is an ordinary cue with an address of its own. What a header must NOT be
        is a member: `order` is the group's cue list, and letting the header take
        index 0 in it would have shifted every real member by one - which is the
        silent version of this bug, and the reason the walk asks the element what
        it is rather than assuming every identified child is a cue. */
    Rig rig;

    const auto preshowId = std::string ("D9FH2JKA");
    const auto header = rig.document.createRole (preshowId, "header");
    REQUIRE (header.ok);

    const auto opening = rig.document.createCue (header.id, 0, "memo", "Pre-arm");
    REQUIRE (opening.ok);

    rig.parameters.markStale();
    const auto snapshot = rig.publish (1);

    const auto valueAt = [&snapshot] (const std::string& address)
    {
        const auto* node = snapshot->find (address);
        REQUIRE_MESSAGE (node != nullptr, "no node at " << address);
        REQUIRE (node->soleValue().has_value());
        return *node->soleValue();
    };

    // The group's order is its members, unchanged by gaining a header.
    CHECK (valueAt ("/godot/cue/" + preshowId + "/order")
             == osc::Value::string ("E4GP6QSC F7HR8TVD"));

    // The header has an order of its own, and its cue is published as a cue.
    CHECK (valueAt ("/godot/cue/" + preshowId + "/headerOrder")
             == osc::Value::string (opening.id));
    CHECK (valueAt ("/godot/cue/" + opening.id + "/kind") == osc::Value::string ("memo"));
    CHECK (valueAt ("/godot/cue/" + opening.id + "/parent") == osc::Value::string (preshowId));

    // And the header container itself publishes nothing: it carries no value.
    CHECK (snapshot->find ("/godot/cue/" + header.id + "/kind") == nullptr);
}

TEST_CASE ("tree: a cue keeps its address when it moves, and its index changes")
{
    /*  Identity addressing, which is what makes a client's subscription and a
        Choufleur pointer survive a reorder (PRD §3.23). The cue is the same
        node at the same address; what moved is the number that says where it
        sits. */
    Rig rig;
    const auto before = rig.publish (0);

    rig.apply (1, "cli", "object.move",
               { osc::Value::string ("F7HR8TVD"), osc::Value::string ("D9FH2JKA"),
                 osc::Value::int32 (0) });

    const auto after = rig.publish (1);

    REQUIRE (after->find (announce + "/index") != nullptr);
    CHECK (*after->find (announce + "/index")->soleValue() == osc::Value::int32 (0));
    CHECK (*after->find (preshow + "/order")->soleValue() == osc::Value::string ("F7HR8TVD E4GP6QSC"));

    /*  No path appeared or disappeared: the flat /godot/cue container holds the
        same cues it did, so a listener gets value pushes and no PATH_*. */
    const auto changes = diff (*before, *after);

    CHECK (changes.added.empty());
    CHECK (changes.removed.empty());
    CHECK (! changes.valueChanged.empty());
}

//==============================================================================
TEST_CASE ("tree: a published snapshot does not change when the next tick does")
{
    /*  The property the whole design rests on. A server thread holding tick 0's
        snapshot must still see tick 0's values however long it takes to
        serialise them, with the tick thread already building tick 1. */
    Rig rig;
    const auto first = rig.publish (0);

    const auto* nameNode = first->find (announce + "/name");
    REQUIRE (nameNode != nullptr);
    CHECK (*nameNode->soleValue() == osc::Value::string ("Announce"));

    const auto nodesBefore = first->size();

    rig.apply (1, "cli", "node.set",
               { osc::Value::string (announce + "/name"), osc::Value::string ("Renamed") });
    rig.apply (2, "cli", "cue.create",
               { osc::Value::string ("7K2QM9X4"), osc::Value::int32 (0),
                 osc::Value::string ("memo"), osc::Value::string ("New") });

    const auto second = rig.publish (2);

    // The new snapshot moved on.
    CHECK (*second->find (announce + "/name")->soleValue() == osc::Value::string ("Renamed"));
    CHECK (second->size() > nodesBefore);
    CHECK (second->tick() == 2);

    // The old one did not, and still answers with what it was published with.
    CHECK (*first->find (announce + "/name")->soleValue() == osc::Value::string ("Announce"));
    CHECK (first->size() == nodesBefore);
    CHECK (first->tick() == 0);
}

TEST_CASE ("tree: creating and deleting a cue is a path added and a path removed")
{
    Rig rig;
    const auto before = rig.publish (0);

    const auto result = rig.apply (1, "cli", "cue.create",
                                   { osc::Value::string ("7K2QM9X4"), osc::Value::int32 (0),
                                     osc::Value::string ("memo"), osc::Value::string ("Blackout"),
                                     osc::Value::string ("H5KT9WXF") });
    REQUIRE (result.applied == 1);

    const auto after = rig.publish (1);
    const auto added = diff (*before, *after);

    CHECK (added.removed.empty());
    REQUIRE (! added.added.empty());

    /*  The whole subtree appears, container and leaves, because a client that
        subscribed to /godot/cue has to be told about each address it can now
        ask for. */
    const auto mentions = [] (const std::vector<std::string>& paths, const std::string& what)
    {
        return std::find (paths.begin(), paths.end(), what) != paths.end();
    };

    CHECK (mentions (added.added, "/godot/cue/H5KT9WXF"));
    CHECK (mentions (added.added, "/godot/cue/H5KT9WXF/name"));

    // And the list's order changed, which is a value push rather than a path.
    CHECK (mentions (added.valueChanged, mainList + "/order"));

    //--------------------------------------------------------------------------
    rig.apply (2, "cli", "object.delete", { osc::Value::string ("H5KT9WXF") });
    const auto removed = diff (*after, *rig.publish (2));

    CHECK (removed.added.empty());
    CHECK (mentions (removed.removed, "/godot/cue/H5KT9WXF"));
    CHECK (mentions (removed.removed, "/godot/cue/H5KT9WXF/name"));
}

TEST_CASE ("tree: a value edit changes values and no paths")
{
    Rig rig;
    const auto before = rig.publish (0);

    rig.apply (1, "cli", "node.set",
               { osc::Value::string (announce + "/notes"), osc::Value::string ("check the mic") });

    const auto changes = diff (*before, *rig.publish (1));

    CHECK (changes.added.empty());
    CHECK (changes.removed.empty());

    /*  Exactly one node under /godot/cue moved. The engine's own counters moved
        too - the tick is one of them, and it moves on every tick by definition -
        so the claim is about the document side, which is the side an edit is
        supposed to touch. */
    std::vector<std::string> documentChanges;

    for (const auto& address : changes.valueChanged)
        if (address.rfind ("/godot/cue", 0) == 0)
            documentChanges.push_back (address);

    CHECK (documentChanges == std::vector<std::string> { announce + "/notes" });
}

//==============================================================================
TEST_CASE ("tree: the engine's own numbers are published, and are runtime only")
{
    Rig rig;

    EngineState state;
    state.version = "9.9.9";
    state.tick = 42;
    state.sampleRate = 48000;
    state.blockSize = 128;
    state.samplesPerTick = 960;
    state.lateness = 17;
    state.latenessMax = 4096;
    state.clock = "dummy";
    state.documentName = "minimal";
    state.documentDirty = true;

    const auto snapshot = rig.parameters.publish (42, state);

    const auto valueAt = [&snapshot] (const std::string& address)
    {
        const auto* node = snapshot->find (address);
        REQUIRE_MESSAGE (node != nullptr, "no node at " << address);
        REQUIRE (node->soleValue().has_value());
        return *node->soleValue();
    };

    CHECK (valueAt ("/godot/engine/product") == osc::Value::string ("Go.dot"));
    CHECK (valueAt ("/godot/engine/version") == osc::Value::string ("9.9.9"));
    CHECK (valueAt ("/godot/engine/tick") == osc::Value::int64 (42));
    CHECK (valueAt ("/godot/engine/sampleRate") == osc::Value::int32 (48000));
    CHECK (valueAt ("/godot/engine/samplesPerTick") == osc::Value::int32 (960));
    CHECK (valueAt ("/godot/engine/lateness") == osc::Value::int32 (17));
    CHECK (valueAt ("/godot/engine/latenessMax") == osc::Value::int32 (4096));
    CHECK (valueAt ("/godot/engine/clock") == osc::Value::string ("dummy"));
    CHECK (valueAt ("/godot/document/name") == osc::Value::string ("minimal"));
    CHECK (valueAt ("/godot/document/dirty") == osc::Value::boolean (true));

    // Every one of them is read-only: they are a meter, not a control.
    for (const auto* node : snapshot->childrenOf ("/godot/engine"))
    {
        INFO ("address: " << node->address);
        CHECK (node->access == Access::read);
    }
}

TEST_CASE ("tree: a rejected write is readable back, because OSC has no reply channel")
{
    /*  A client that writes something unacceptable gets no answer on the wire -
        OSC has none to give and the OSCQuery proposal defines none - so the
        only way it can find out is to read it back. */
    Rig rig;

    /*  `kind` is derived from the element, so a client cannot turn a cue into a
        group by writing to it. The tree publishes that node read-only, and the
        refusal has to say READ-ONLY rather than "no such address" - the address
        is not what is wrong with the request. */
    const auto result = rig.apply (1, "udp:192.168.1.7:9000", "node.set",
                                   { osc::Value::string (announce + "/kind"),
                                     osc::Value::string ("group") });

    CHECK (result.applied == 0);
    CHECK (result.rejected == 1);

    const auto snapshot = rig.publish (1);

    const auto* count = snapshot->find ("/godot/engine/errorCount");
    const auto* last = snapshot->find ("/godot/engine/lastError");

    REQUIRE (count != nullptr);
    REQUIRE (last != nullptr);
    CHECK (*count->soleValue() == osc::Value::int32 (1));

    /*  kind is derived from the element: a client cannot turn a cue into a
        group by writing to it, and the read-back says which node and why. */
    REQUIRE (last->soleValue().has_value());
    const auto text = last->soleValue()->getString();

    INFO ("lastError: " << text);
    CHECK (text.find ("read-only") != std::string::npos);
    CHECK (text.find ("node.set") != std::string::npos);
}

TEST_CASE ("tree: node.set takes the target's own type, not always a string")
{
    Rig rig;

    // A double, sent as a double.
    CHECK (rig.apply (1, "cli", "node.set",
                      { osc::Value::string (announce + "/preWait"),
                        osc::Value::float64 (2.5) }).applied == 1);

    CHECK (*rig.publish (1)->find (announce + "/preWait")->soleValue() == osc::Value::float64 (2.5));

    // The same value sent as text lands identically: the schema decides the type.
    CHECK (rig.apply (2, "cli", "node.set",
                      { osc::Value::string (announce + "/preWait"),
                        osc::Value::string ("2.5") }).applied == 1);

    CHECK (*rig.publish (2)->find (announce + "/preWait")->soleValue() == osc::Value::float64 (2.5));

    /*  And a word still cannot get into a number. The check moved one layer in,
        to where the type is actually known; it did not go away. */
    CHECK (rig.apply (3, "cli", "node.set",
                      { osc::Value::string (announce + "/preWait"),
                        osc::Value::string ("soon") }).rejected == 1);

    // Nor a number below the row's declared minimum.
    CHECK (rig.apply (4, "cli", "node.set",
                      { osc::Value::string (announce + "/preWait"),
                        osc::Value::float64 (-1.0) }).rejected == 1);

    CHECK (*rig.publish (4)->find (announce + "/preWait")->soleValue() == osc::Value::float64 (2.5));
}

//==============================================================================
TEST_CASE ("touch: a held node stops being pushed to whoever is holding it")
{
    /*  The fader fight, in three lines. While a surface holds a node the engine
        stops telling it what that node's value is; everyone else still hears. */
    TouchTable touches;

    const std::string surface = "ws:192.168.1.20:51234";
    const std::string other = "ws:192.168.1.21:51234";
    const std::string address = "/godot/cue/B3N8R5TW/preWait";

    CHECK (shouldPush (touches, surface, address, {}));

    CHECK (touches.touch (surface, address));
    CHECK_FALSE (touches.touch (surface, address));      // already held: not an error, not new

    CHECK_FALSE (shouldPush (touches, surface, address, {}));
    CHECK (shouldPush (touches, other, address, {}));    // everyone else still hears

    // A different node is unaffected: a touch is on one address, not on a client.
    CHECK (shouldPush (touches, surface, "/godot/cue/B3N8R5TW/name", {}));

    CHECK (touches.release (surface, address));
    CHECK (shouldPush (touches, surface, address, {}));
}

TEST_CASE ("touch: an origin is never told about a change it made itself")
{
    /*  Echo suppression, which is separate from touching and applies whether or
        not anything is held. */
    TouchTable touches;

    const std::string me = "udp:192.168.1.7:9000";
    const std::string them = "cli";
    const std::string address = "/godot/cue/B3N8R5TW/name";

    CHECK_FALSE (shouldPush (touches, me, address, me));
    CHECK (shouldPush (touches, them, address, me));

    // No origin means the engine changed it: a cue fired, a curve moved.
    CHECK (shouldPush (touches, me, address, {}));
}

TEST_CASE ("touch: a disconnect gives back everything that origin held")
{
    /*  A surface that vanished cannot release anything itself, and its touches
        would otherwise silence those nodes for a client id nobody will use
        again. */
    TouchTable touches;

    const std::string gone = "ws:192.168.1.20:51234";
    const std::string staying = "ws:192.168.1.21:51234";

    touches.touch (gone, "/godot/cue/A/x");
    touches.touch (gone, "/godot/cue/A/y");
    touches.touch (staying, "/godot/cue/A/x");

    CHECK (touches.size() == 3);
    CHECK (touches.holdersOf ("/godot/cue/A/x") == std::vector<std::string> { gone, staying });

    const auto released = touches.releaseAll (gone);

    CHECK (released == std::vector<std::string> { "/godot/cue/A/x", "/godot/cue/A/y" });
    CHECK (touches.size() == 1);
    CHECK (touches.heldBy (gone).empty());
    CHECK (touches.holdersOf ("/godot/cue/A/x") == std::vector<std::string> { staying });
}

TEST_CASE ("touch: it is a command, so a replay reproduces who was holding what")
{
    /*  PRD §3.15 admits no second path. A touch changes what the engine sends
        and to whom, so a replay that did not re-apply it would produce a
        different set of outbound messages from the session it claims to
        reproduce. */
    Rig rig;

    const std::string surface = "ws:192.168.1.20:51234";
    const auto address = announce + "/preWait";

    CHECK (rig.apply (1, surface, "node.touch", { osc::Value::string (address) }).applied == 1);
    CHECK (rig.touches.isHeld (surface, address));

    CHECK (rig.apply (2, surface, "node.release", { osc::Value::string (address) }).applied == 1);
    CHECK_FALSE (rig.touches.isHeld (surface, address));

    /*  Releasing what was never held is applied, not refused: a surface
        reconnecting after a drop has no idea what the engine thinks it holds,
        and refusing would punish exactly the client trying to get back in
        step. */
    CHECK (rig.apply (3, surface, "node.release", { osc::Value::string (address) }).applied == 1);

    // An engine-internal event has no origin, and cannot hold anything.
    CHECK (rig.apply (4, "", "node.touch", { osc::Value::string (address) }).rejected == 1);
    CHECK (rig.touches.empty());
}

//==============================================================================
TEST_CASE ("tree: commands are write-only method nodes, and node.set is not one")
{
    Rig rig;
    const auto snapshot = rig.publish (0);

    const auto* create = snapshot->find ("/godot/cmd/cue/create");
    REQUIRE (create != nullptr);

    CHECK (create->kind == Kind::event);
    CHECK (create->access == Access::write);
    CHECK (create->typeTags == "sisss");        // parent, index, kind, name, [id]
    CHECK_FALSE (create->soleValue().has_value());    // an event has no value at a given time

    CHECK (snapshot->find ("/godot/cmd/node/touch") != nullptr);
    CHECK (snapshot->find ("/godot/cmd/node/release") != nullptr);

    /*  node.set has no /cmd node because its signature is whatever the target
        declares, and its address IS the target's. */
    CHECK (snapshot->find ("/godot/cmd/node/set") == nullptr);
}

TEST_CASE ("tree: only a state node declares a rate cap, an anticipation and a panic")
{
    /*  Those three are statements about a VALUE. A container has none and an
        event has none at any given time, so claiming them would be filling in
        a form rather than saying something - and a client reading
        `"PANIC": "park"` on cue.create would be entitled to believe it. */
    Rig rig;
    const auto snapshot = rig.publish (0);

    const auto godotKey = [&snapshot] (const std::string& address)
    {
        const auto json = OscQueryJson::describe (*snapshot, address);
        const auto at = json.find ("\"GODOT\"");
        REQUIRE (at != std::string::npos);
        return json.substr (at, json.find ('\n', at) - at);
    };

    CHECK (godotKey ("/godot/cmd/cue/create").find ("PANIC") == std::string::npos);
    CHECK (godotKey ("/godot/cue").find ("PANIC") == std::string::npos);
    CHECK (godotKey (announce + "/name").find ("PANIC") != std::string::npos);
    CHECK (godotKey (announce + "/name").find ("RATE_CAP") != std::string::npos);
}

TEST_CASE ("tree: the JSON is deterministic, and its numbers do not go through JUCE")
{
    Rig rig;
    const auto snapshot = rig.publish (0);

    // Same snapshot, same bytes: a golden would be worthless otherwise.
    CHECK (OscQueryJson::describe (*snapshot, "/godot")
             == OscQueryJson::describe (*snapshot, "/godot"));

    /*  A number a client reads out of this reply has to be the number the
        engine holds. 1.5 is exact either way; the point of the check is that
        it is spelled the way the document spells it, with no locale comma and
        no trailing zeroes. */
    const auto json = OscQueryJson::describe (*snapshot, announce + "/postWait");

    INFO (json);
    CHECK (json.find ("\"VALUE\": [1.5]") != std::string::npos);
    CHECK (json.find ("\"MIN\": 0") != std::string::npos);
    CHECK (json.find (",5") == std::string::npos);
}

TEST_CASE ("tree: an empty tree is still a tree")
{
    /*  snapshot() before the first publish returns something rather than
        nullptr, so no caller has to check. An empty tree at tick -1 is the
        honest description of an engine that has not ticked yet. */
    Engine engine;
    doc::ShowDocument document;
    MountTable mounts;
        cue::RunTable runs;
    ParameterTree parameters { document, engine.commands(), mounts, runs };

    const auto empty = parameters.snapshot();

    REQUIRE (empty != nullptr);
    CHECK (empty->tick() == -1);
    CHECK (empty->size() == 0);
    CHECK (empty->find ("/godot") == nullptr);
    CHECK (OscQueryJson::describe (*empty, "/").empty());

    // And after one publish it is the published one.
    EngineState state;
    const auto first = parameters.publish (0, state);

    CHECK (parameters.snapshot() == first);
    CHECK (parameters.snapshot()->tick() == 0);
}

TEST_CASE ("tree: the document's revision moves on an edit and stays put on a standby move")
{
    /*  /godot/document/revision is the number a client keys a cached picture
        of the show on, so what does NOT move it is the point of the node: the
        document half of a snapshot is rebuilt whenever any command applies,
        and a chain of runs would have a cue list rebuilt several times a
        second for a show nobody edited. A standby move is the state-row write
        a GO makes, and it is the one this case pins as inert. */
    Rig rig;

    const auto revisionAt = [&rig] (std::int64_t tick)
    {
        const auto snapshot = rig.publish (tick);
        const auto* node = snapshot->find ("/godot/document/revision");

        REQUIRE (node != nullptr);
        REQUIRE (node->soleValue().has_value());
        REQUIRE (node->soleValue()->isInt64());     // an `h` row, like the tick
        return node->soleValue()->getInt64();
    };

    const auto opened = revisionAt (0);
    CHECK (opened >= 1);                            // never 0: that is a client's "no picture yet"
    CHECK (revisionAt (1) == opened);               // nothing applied, nothing moves

    /*  APPLIED, not merely submitted: a refused write would leave the number
        where it was and let this case pass for the wrong reason. */
    REQUIRE (rig.apply (2, "cli", "node.set",
                        { osc::Value::string ("/godot/list/7K2QM9X4/standby"),
                          osc::Value::string ("F7HR8TVD") }).applied == 1);
    CHECK (revisionAt (2) == opened);               // where the operator stands is not the show

    REQUIRE (rig.apply (3, "cli", "node.set",
                        { osc::Value::string ("/godot/cue/F7HR8TVD/name"),
                          osc::Value::string ("Renamed") }).applied == 1);
    CHECK (revisionAt (3) > opened);                // an edit is
}

//==============================================================================
/*  PR 5.8: THE TWO NODES THAT READ THE ANALYSER, a run's `timbre` and a media
    cue's `hash` - both published by the runtime half, both empty until the
    analyser has answered, and neither of them ever a guess (namespace draft
    §14.5).

    Nothing here analyses a sound. The pyramid is sixty-four frames whose bytes
    are chosen, handed to a MediaInfo the way the analyser hands it one, so
    every reading below is known before the tree is asked. */
namespace
{
    namespace timbre = audio::timbre;

    const std::string bedFile = "bed.wav";

    /*  Sixty-four hex characters, the shape the analyser publishes. Which ones
        is nothing to the tree, which prints a hash and never reads it. */
    const std::string bedHash = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

    /*  Where the MediaInfo is told the files are: an absolute folder that is
        never made, so every length reads nought and nothing depends on the
        directory the suite was started in - which a relative `file`, taken as
        given, would be read against. */
    std::string nowhere()
    {
        return juce::File::getSpecialLocation (juce::File::tempDirectory)
                   .getChildFile ("wfg-tree-" + juce::Uuid().toDashedString())
                   .getFullPathName().toStdString();
    }

    /*  A media cue naming `file`, at the head of `parentId` - the main list
        unless something else is asked for. */
    std::string addMediaCue (Rig& rig, const std::string& file,
                             const std::string& parentId = "7K2QM9X4")
    {
        const auto created = rig.document.createCue (parentId, 0, "media", "Bed");
        REQUIRE (created.ok);
        REQUIRE (rig.document.setAttribute ("/godot/cue/" + created.id + "/file", file).ok);

        rig.parameters.markStale();
        return created.id;
    }

    /*  A run of that cue as the runner leaves one: the file copied onto the run
        at its first arm, the position written on every tick. Looked up again by
        identifier afterwards and never held, because a second `create` may
        move every run in the table. */
    void addRun (Rig& rig, const std::string& runId, const std::string& cueId,
                 const std::string& file, double seconds)
    {
        rig.runs.create (runId, cueId, "media");

        auto* run = rig.runs.find (runId);
        REQUIRE (run != nullptr);

        run->media = file;
        run->position = seconds;
    }

    void moveRun (Rig& rig, const std::string& runId, double seconds)
    {
        auto* run = rig.runs.find (runId);
        REQUIRE (run != nullptr);

        run->position = seconds;
    }

    /*  SIXTY-FOUR FRAMES AT 48 kHz, each unlike its neighbours - one level,
        since a pyramid stops at sixty-four - so the frame a position picks is
        the only one that could print what it prints. Frame 30's hue byte is 8,
        which is 11.25 degrees: a half exactly, so the rounding has to say which
        way it goes. Frame 50 is silence. */
    std::vector<timbre::Frame> bedFrames()
    {
        std::vector<timbre::Frame> frames (64);

        for (std::size_t k = 0; k < frames.size(); ++k)
        {
            const auto step = static_cast<int> (k);

            frames[k].hue = static_cast<std::uint8_t> ((step * 37) % 256);
            frames[k].saturation = static_cast<std::uint8_t> (40 + step * 3);
            frames[k].lightness = static_cast<std::uint8_t> (38 + step * 2);
            frames[k].peak = static_cast<std::uint8_t> (step);
        }

        frames[30].hue = 8;
        frames[50] = timbre::Frame {};

        return frames;
    }

    /*  A record as the analyser publishes one: the hash and the pyramid
        together, never one without the other. */
    audio::MediaRecord analysedRecord (const std::string& hash, std::vector<timbre::Frame> frames)
    {
        const auto samples = static_cast<std::uint64_t> (frames.size())
                               * static_cast<std::uint64_t> (timbre::hopSize);

        audio::MediaRecord record;
        record.contentHash = hash;
        record.pyramid = std::make_shared<const audio::TimbrePyramid> (
            timbre::pyramidOf (std::move (frames), 48000u, samples));

        return record;
    }

    /*  THE TEXT, RESTATED from its rule rather than asked of the tree - a test
        that called the tree's own formatter would pass whatever it did. The
        hue to the nearest tenth of a degree, the saturation and the lightness
        to the nearest thousandth, a half rounded up, and no trailing zero.
        Worked in integers with the decimal point written by hand: a different
        road from the engine's doubles and its shortest-round-trip formatter,
        to the same text. A quotient a / b rounded half up is (2a + b) / 2b. */
    std::string expectedTimbre (const timbre::Frame& frame)
    {
        const auto decimal = [] (int scaled, int places)
        {
            int unit = 1;

            for (int i = 0; i < places; ++i)
                unit *= 10;

            auto fraction = std::to_string (scaled % unit);

            while (fraction.size() < static_cast<std::size_t> (places))
                fraction.insert (fraction.begin(), '0');

            while (! fraction.empty() && fraction.back() == '0')
                fraction.pop_back();

            const auto whole = std::to_string (scaled / unit);
            return fraction.empty() ? whole : whole + "." + fraction;
        };

        // A hue is its byte times 360 over 256 degrees, so tenths are times 3600.
        const auto tenths = (2 * frame.hue * 3600 + 256) / 512;

        // The unit range is the byte over 255, so thousandths are times 1000.
        const auto thousandths = [] (int value) { return (2 * value * 1000 + 255) / 510; };

        return decimal (tenths, 1) + " "
             + decimal (thousandths (frame.saturation), 3) + " "
             + decimal (thousandths (frame.lightness), 3);
    }

    std::string textAt (const TreeSnapshot& snapshot, const std::string& address)
    {
        const auto* node = snapshot.find (address);
        REQUIRE_MESSAGE (node != nullptr, "no node at " << address);
        REQUIRE (node->soleValue().has_value());
        return node->soleValue()->getString();
    }
}

TEST_CASE ("tree: a run's timbre is the frame at its position, in three numbers a byte can hold")
{
    /*  Under fr_FR as well as C, like every case in this file: three numbers
        with decimal points in one string is exactly what a formatter that
        consulted the locale would get wrong. */
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    Rig rig;
    const auto cueId = addMediaCue (rig, bedFile);

    audio::MediaInfo media { rig.document, nowhere() };
    media.publish (bedFile, analysedRecord (bedHash, bedFrames()));
    rig.parameters.setMediaInfo (&media);

    const auto frames = bedFrames();

    /*  The restated rule, pinned first against arithmetic done by hand, so the
        two roads cannot agree by sharing a mistake. Frame 4 is bytes 148, 52
        and 46: 208.125 degrees, 0.2039 and 0.1804. Frame 30 is 11.25 degrees,
        and a half goes up. */
    REQUIRE (expectedTimbre (frames[4]) == "208.1 0.204 0.18");
    REQUIRE (expectedTimbre (frames[30]) == "11.3 0.51 0.384");
    REQUIRE (expectedTimbre (frames[50]) == "0 0 0");

    const auto address = std::string ("/godot/run/R1/timbre");
    addRun (rig, "R1", cueId, bedFile, 0.1);

    /*  0.1 s is 4 800 samples, 4.69 hops: frame 4. */
    const auto first = rig.publish (0);
    CHECK (textAt (*first, address) == expectedTimbre (frames[4]));

    /*  What the node declares, from its row: read-only, a string, and a rate
        cap of 10 - the first in the table that is not 1, 5 or 50, on purpose,
        and an instruction to a surface rather than anything the engine does
        (§14.5). */
    const auto* node = first->find (address);
    REQUIRE (node != nullptr);
    CHECK (node->access == Access::read);
    CHECK (node->typeTags == "s");
    CHECK (node->rateCap == doctest::Approx (10.0));

    /*  0.3 s is 14 400 samples, 14.06 hops: frame 14, and another reading. */
    moveRun (rig, "R1", 0.3);
    CHECK (textAt (*rig.publish (1), address) == expectedTimbre (frames[14]));
    CHECK (expectedTimbre (frames[14]) != expectedTimbre (frames[4]));

    /*  0.65 s is 31 200 samples, 30.47 hops: the half. */
    moveRun (rig, "R1", 0.65);
    CHECK (textAt (*rig.publish (2), address) == "11.3 0.51 0.384");

    /*  1.07 s is 51 360 samples, 50.16 hops: silence, which is a reading and
        not the empty "not analysed yet". */
    moveRun (rig, "R1", 1.07);
    CHECK (textAt (*rig.publish (3), address) == "0 0 0");

    /*  And past the end of the file, its last frame: a finished run keeps its
        last playhead for as long as it is published. */
    moveRun (rig, "R1", 30.0);
    CHECK (textAt (*rig.publish (4), address) == expectedTimbre (frames[63]));
}

TEST_CASE ("tree: a run's timbre is empty until there is a frame to read, and never a guess")
{
    /*  Empty is §3.30's grey - a client draws its own - and it has to be empty
        in every case where the engine does not know, rather than a colour
        borrowed from somewhere or a nought that would read as silence. */
    Rig rig;
    const auto cueId = addMediaCue (rig, bedFile);

    addRun (rig, "R1", cueId, bedFile, 0.1);
    addRun (rig, "R2", cueId, "elsewhere.wav", 0.1);     // a file no record names
    rig.runs.create ("R3", "B3N8R5TW", "memo");           // a run that plays no file

    const auto readings = [&rig] (std::int64_t tick)
    {
        const auto snapshot = rig.publish (tick);

        return std::vector<std::string> { textAt (*snapshot, "/godot/run/R1/timbre"),
                                          textAt (*snapshot, "/godot/run/R2/timbre"),
                                          textAt (*snapshot, "/godot/run/R3/timbre") };
    };

    const std::vector<std::string> nothing { "", "", "" };

    /*  NO MEDIAINFO AT ALL, which is any tree built without `setMediaInfo`.
        No verb builds one that way: `wfg tree` and `wfg serve` both hand
        theirs the show's, and `wfg replay` builds no ParameterTree at all - it
        hands its runner the lengths the log recorded and has no tree to hand
        anything. So this is the tree's own default rather than a session
        anybody runs, and it owes the same honest nothing as every step below:
        each node there all the same, empty.

        THE MEDIA CUE'S `hash` AS WELL AS THE RUNS' TIMBRES. The roster it is
        published against is walked out of the document, not out of a
        MediaInfo, so a tree that was never told where the records are still
        knows which cues are media cues - and the shape of a cue's node list
        is the show's to decide, never a matter of which objects the verb that
        built the tree happened to wire to it. */
    CHECK (readings (0) == nothing);

    const auto hashAddress = "/godot/cue/" + cueId + "/hash";
    const auto bare = rig.parameters.snapshot();

    CHECK (bare->find (hashAddress) != nullptr);
    CHECK (textAt (*bare, hashAddress).empty());

    /*  A MediaInfo over the show before the analyser has published anything:
        the file has a record, with its length and no pyramid. */
    audio::MediaInfo media { rig.document, nowhere() };
    rig.parameters.setMediaInfo (&media);

    REQUIRE (media.snapshot()->count (bedFile) == 1u);
    CHECK (readings (1) == nothing);

    /*  A hash with no pyramid is still nothing to read a frame from. */
    audio::MediaRecord hashedOnly;
    hashedOnly.contentHash = bedHash;
    media.publish (bedFile, hashedOnly);

    CHECK (readings (2) == nothing);

    /*  Nor is a pyramid with no frames - a file of no samples - at any
        position. */
    media.publish (bedFile, analysedRecord (bedHash, {}));
    CHECK (readings (3) == nothing);

    /*  And the same rig reads a frame the moment there is one, so the empties
        above are the engine's answer and not a rig that could read nothing.
        The other two stay empty: one names a file nobody analysed, and one
        plays no file at all. */
    media.publish (bedFile, analysedRecord (bedHash, bedFrames()));
    CHECK (readings (4) == std::vector<std::string> { expectedTimbre (bedFrames()[4]), "", "" });
}

TEST_CASE ("tree: a media cue's hash is published by the runtime half, and arrives without an edit")
{
    Rig rig;
    const auto cueId = addMediaCue (rig, bedFile);

    audio::MediaInfo media { rig.document, nowhere() };
    rig.parameters.setMediaInfo (&media);

    const auto address = "/godot/cue/" + cueId + "/hash";
    const auto before = rig.publish (0);

    /*  Empty until the analyser answers - and there from the start, so a
        client watching the cue never sees its node list change shape. */
    CHECK (textAt (*before, address).empty());

    const auto* node = before->find (address);
    REQUIRE (node != nullptr);
    CHECK (node->access == Access::read);
    CHECK (node->rateCap == doctest::Approx (1.0));

    /*  A media cue's alone: a memo and a group have no file to hash. */
    CHECK (before->find (announce + "/hash") == nullptr);
    CHECK (before->find (preshow + "/hash") == nullptr);

    const auto revision = rig.document.revision();

    /*  A hash without its pyramid is one the route would answer with a 404,
        so the tree does not print it either. */
    audio::MediaRecord hashedOnly;
    hashedOnly.contentHash = bedHash;
    media.publish (bedFile, hashedOnly);

    CHECK (textAt (*rig.publish (1), address).empty());

    /*  THE PROOF IT IS THE RUNTIME HALF. The record lands and the very next
        publish reads it, with no edit to the show and no `markStale` - so the
        document half is still the one built at tick 0. Published from there,
        the hash would read empty until somebody happened to edit a cue. */
    media.publish (bedFile, analysedRecord (bedHash, bedFrames()));

    const auto after = rig.publish (2);

    CHECK (textAt (*after, address) == bedHash);
    CHECK (rig.document.revision() == revision);

    /*  And to a listener it is a value push, not a path. */
    const auto changes = diff (*before, *after);

    CHECK (changes.added.empty());
    CHECK (changes.removed.empty());
    CHECK (std::find (changes.valueChanged.begin(), changes.valueChanged.end(), address)
             != changes.valueChanged.end());

    //--------------------------------------------------------------------------
    /*  THE ROSTER IS REFILLED, NOT GROWN. The runtime half reads each hash
        against `declaredMedia`, which the document half leaves behind every
        time it is rebuilt - and everything above built that half exactly
        once, so none of it would notice a rebuild that appended to the roster,
        or one that kept a cue the show no longer has. Two edits, then, that
        pass only if it is walked afresh out of the show as it now stands.

        FIRST THE CUE IS POINTED AT ANOTHER FILE: a second take of the bed,
        analysed under a hash of its own. Both records stay in the MediaInfo,
        which files them by path and forgets nothing, so the one thing that
        can move the cue from the first to the second is a roster pairing the
        cue with the file it names NOW. A roster kept would print the old hash;
        one appended to would carry two `hash` leaves at one address, and
        `find` would answer with whichever it reached first - which is why the
        address is counted across the whole tree rather than looked up, the
        way the case below counts every address. */
    const auto takeTwo = std::string ("bed-take2.wav");
    const auto takeTwoHash = std::string ("fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210");

    REQUIRE (rig.document.setAttribute ("/godot/cue/" + cueId + "/file", takeTwo).ok);
    media.publish (takeTwo, analysedRecord (takeTwoHash, bedFrames()));
    rig.parameters.markStale();

    const auto moved = rig.publish (3);
    const auto nodes = moved->all();

    const auto occurrences = [&nodes] (const std::string& path)
    {
        return std::count_if (nodes.begin(), nodes.end(),
                              [&path] (const Node* each) { return each->address == path; });
    };

    CHECK (textAt (*moved, address) == takeTwoHash);
    CHECK (occurrences (address) == 1);
    CHECK (occurrences ("/godot/cue/" + cueId) == 1);

    /*  THEN THE CUE IS DELETED, through the engine, as a client deletes one.
        Its file's record is still in the MediaInfo - a file outlives the cue
        that named it - so the records cannot say the cue has gone, and only
        the roster can. The container has to go with the leaf: `/godot/cue/<id>`
        is the document half's for as long as the show declares the cue, and a
        `hash` leaf left behind would have the runtime half make a container of
        its own to hold it - a cue a client could still find, in a show that no
        longer has it. */
    REQUIRE (rig.apply (4, "cli", "object.delete", { osc::Value::string (cueId) }).applied == 1);

    const auto gone = rig.publish (4);

    CHECK (gone->find (address) == nullptr);
    CHECK (gone->find ("/godot/cue/" + cueId) == nullptr);
}

TEST_CASE ("tree: every media cue has one hash wherever it sits, and every run one timbre")
{
    /*  The media roster is threaded through every walk that reaches a cue - a
        list's members, a group's members, a group's header, a list's
        persistent section - so there is a media cue in each, each naming a file
        of its own, and each must come out once with exactly its own file's
        hash. And the whole tree is walked, because both halves carrying an
        address would make the answer depend on which one `find` reached
        first. */
    Rig rig;

    const auto preshowId = std::string ("D9FH2JKA");

    const auto header = rig.document.createRole (preshowId, "header");
    REQUIRE (header.ok);

    const auto section = rig.document.createPersistent ("7K2QM9X4");
    REQUIRE (section.ok);

    const std::vector<std::pair<std::string, std::string>> placements {
        { "7K2QM9X4", "bed.wav" },
        { preshowId,  "rain.wav" },
        { header.id,  "preroll.wav" },
        { section.id, "room.wav" },
        { "7K2QM9X4", "later.wav" } };      // never analysed

    std::vector<std::string> cues;

    for (const auto& [parent, file] : placements)
        cues.push_back (addMediaCue (rig, file, parent));

    audio::MediaInfo media { rig.document, nowhere() };

    /*  Every file but the last analysed, each under a hash of its own letter. */
    const auto hashFor = [&placements] (std::size_t i)
    {
        return i + 1 < placements.size() ? std::string (64, static_cast<char> ('a' + static_cast<int> (i)))
                                         : std::string();
    };

    for (std::size_t i = 0; i + 1 < placements.size(); ++i)
        media.publish (placements[i].second, analysedRecord (hashFor (i), bedFrames()));

    rig.parameters.setMediaInfo (&media);
    addRun (rig, "R1", cues.front(), "bed.wav", 0.1);

    const auto snapshot = rig.publish (0);
    const auto nodes = snapshot->all();

    const auto occurrences = [&nodes] (const std::string& address)
    {
        return std::count_if (nodes.begin(), nodes.end(),
                              [&address] (const Node* each) { return each->address == address; });
    };

    for (std::size_t i = 0; i < cues.size(); ++i)
    {
        const auto hashAddress = "/godot/cue/" + cues[i] + "/hash";
        INFO ("address: " << hashAddress);

        CHECK (occurrences (hashAddress) == 1);
        CHECK (occurrences ("/godot/cue/" + cues[i]) == 1);
        CHECK (textAt (*snapshot, hashAddress) == hashFor (i));
    }

    CHECK (occurrences ("/godot/run/R1/timbre") == 1);
    CHECK (textAt (*snapshot, "/godot/run/R1/timbre") == expectedTimbre (bedFrames()[4]));

    /*  And every address in the tree exactly once, the walk the root's own case
        makes. */
    std::set<std::string> seen;

    for (const auto* node : nodes)
    {
        INFO ("address: " << node->address);
        CHECK (seen.insert (node->address).second);
    }

    CHECK (seen.size() == snapshot->size());
}

TEST_CASE ("tree: a fade's and a stop's duration is the one the show says, and only a media cue's is its file's")
{
    /*  THREE ROWS SHARE THE NAME `duration` AND MEAN TWO THINGS. On a media cue
        it is a READOUT - how long the file is, read from its header at open and
        never stored. On a fade and a stop it is a DECISION - how long the fade
        takes - written in the show, rw, and saved. The tree answered all three
        from the media table until PR 5.8: a fade names no `file`, so it found
        nothing there and published nought, and every client showed the
        operator a two-second fade as a zero-second one, and an edit to it as
        not having happened. Caught while PR 5.8 added the media owner's second
        runtime row. */
    doc::ShowDocument document;
    const juce::File bundle { juce::String (std::string (WFG_TEST_FIXTURES_DIR))
                                + "/bundles/fade-stop" };
    REQUIRE (doc::Bundle::open (bundle, document).ok);

    Engine engine;
    MountTable mounts;
    cue::RunTable runs;
    ParameterTree parameters { document, engine.commands(), mounts, runs };

    /*  The one media cue's file, with a length nobody would mistake for a
        fade's. */
    const std::map<std::string, double> lengths { { "thunder.wav", 4.5 } };
    parameters.setMediaDurations (&lengths);

    EngineState state;
    state.version = "test";
    const auto snapshot = parameters.publish (0, state);

    const auto valueAt = [&snapshot] (const std::string& address)
    {
        const auto* node = snapshot->find (address);
        REQUIRE (node != nullptr);
        REQUIRE (node->soleValue().has_value());
        return *node->soleValue();
    };

    CHECK (valueAt ("/godot/cue/E4GP6QSC/duration") == osc::Value::float64 (2.0));    // a fade
    CHECK (valueAt ("/godot/cue/M5TQ7XVA/duration") == osc::Value::float64 (3.0));    // a stop
    CHECK (valueAt ("/godot/cue/P9XKC2WR/duration") == osc::Value::float64 (1.0));    // another fade
    CHECK (valueAt ("/godot/cue/B3N8R5TW/duration") == osc::Value::float64 (4.5));    // the media cue's file
}
