/*
    This file is part of Go.dot — https://github.com/pob31/go.dot

    Copyright (C) 2026 Pierre-Olivier Boulant

    Go.dot is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later
    version. Go.dot is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
    (LICENSE, at the repository root) for more details.

    SPDX-License-Identifier: GPL-3.0-or-later
*/

/*
    The `/godot` namespace: what it contains, what it publishes, what it sends
    and to whom.

    A serialisation surface, so every case here runs under fr_FR as well as C.

    THE GOLDEN IS COMMITTED AND WAS CHECKED BY HAND, field by field, against the
    rows of docs/parameters/godot-parameters.csv and the cue in the bundle
    fixture. It is not generated by the code it tests: a golden written by the
    thing under test proves only that the thing agrees with itself, which is
    exactly the failure a published reply must not have. It covers one cue
    rather than the whole tree because the whole tree is seven hundred lines,
    and a golden nobody can read is a golden nobody will check when it changes.
*/

#include <3rd_party/doctest/tracktion_doctest.hpp>

#include "TestSupport.h"

#include <wfg/engine/Engine.h>
#include <wfg/engine/document/Bundle.h>
#include <wfg/engine/document/DocumentCommands.h>
#include <wfg/engine/tree/OscQueryJson.h>
#include <wfg/engine/tree/ParameterTree.h>
#include <wfg/engine/tree/TreeCommands.h>

#include <juce_core/juce_core.h>

#include <algorithm>
#include <set>
#include <string>

using namespace wfg;
using namespace wfg::tree;

namespace
{
    juce::File fixtureBundle()
    {
        const juce::File folder { juce::String (std::string (WFG_TEST_FIXTURES_DIR))
                                    + "/bundles/minimal" };

        REQUIRE_MESSAGE (folder.isDirectory(), "missing fixture bundle: "
                                                 << folder.getFullPathName());
        return folder;
    }

    std::string readFixture (const std::string& name)
    {
        const juce::File file { juce::String (std::string (WFG_TEST_FIXTURES_DIR))
                                  + "/tree/" + juce::String (name) };

        REQUIRE_MESSAGE (file.existsAsFile(), "missing fixture: " << file.getFullPathName());

        juce::MemoryBlock block;
        REQUIRE (file.loadFileAsData (block));

        /*  Normalised, so a checkout that turned the fixture into CRLF tests
            the same thing as one that did not. The WRITER's line endings are
            pinned separately, below. */
        auto text = std::string (static_cast<const char*> (block.getData()), block.getSize());
        text.erase (std::remove (text.begin(), text.end(), '\r'), text.end());
        return text;
    }

    /*  Engine, document, commands and tree, wired exactly as `wfg tree` and
        (from PR 1.10) `serve` wire them. Held together so a test can say what
        it is about rather than repeating six lines of assembly. */
    struct Rig
    {
        Rig()
        {
            REQUIRE (doc::Bundle::open (fixtureBundle(), document).ok);
            doc::registerDocumentCommands (engine.commands(), document);
            registerTreeCommands (engine.commands(), touches);
        }

        /** Applies one command through the engine, as a client would. */
        Engine::TickResult apply (std::int64_t tick, const std::string& origin,
                                  const std::string& command, std::vector<osc::Value> args = {})
        {
            REQUIRE (engine.submit (origin, command, std::move (args)));
            const auto result = engine.processTick (tick);
            parameters.markStale();
            return result;
        }

        std::shared_ptr<const TreeSnapshot> publish (std::int64_t tick)
        {
            EngineState state;
            state.version = "test";
            state.tick = tick;
            state.errorCount = engine.errorCount();
            state.lastError = engine.lastError();
            return parameters.publish (tick, state);
        }

        Engine engine;
        doc::ShowDocument document;
        TouchTable touches;
        ParameterTree parameters { document, engine.commands() };
    };

    const std::string announce = "/godot/cue/F7HR8TVD";       // the second cue of the Preshow group
    const std::string preshow  = "/godot/cue/D9FH2JKA";       // the group that holds it
    const std::string mainList = "/godot/list/7K2QM9X4";
}

//==============================================================================
TEST_CASE ("tree: one cue serialises to the committed golden, byte for byte")
{
    INFO ("locale in effect: " << std::string (wfgtest::appliedLocaleName()));

    /*  Every field of this was read against the CSV row it comes from: the
        type tag, the access number, the range, the unit, the description and
        all four GODOT declarations. Under fr_FR too, because the two numbers
        in it - 1.5 and the MIN of 0 - go through the same formatter as the
        document, and a formatter that consulted the locale would put a comma
        in a published reply. */
    Rig rig;
    const auto snapshot = rig.publish (0);

    CHECK (OscQueryJson::describe (*snapshot, announce) == readFixture ("cue-F7HR8TVD.json"));
}

TEST_CASE ("tree: an address that names nothing produces nothing")
{
    Rig rig;
    const auto snapshot = rig.publish (0);

    CHECK (OscQueryJson::describe (*snapshot, "/godot/cue/ZZZZZZZZ").empty());
    CHECK (OscQueryJson::describe (*snapshot, "/nope").empty());
}

TEST_CASE ("tree: the root holds one of each subtree, and every address exactly once")
{
    Rig rig;
    const auto snapshot = rig.publish (0);

    for (const auto& address : { "/", "/godot", "/godot/engine", "/godot/document",
                                 "/godot/list", "/godot/cue", "/godot/mount", "/godot/cmd" })
    {
        INFO ("address: " << address);
        const auto* node = snapshot->find (address);

        REQUIRE (node != nullptr);
        CHECK (node->isContainer());
    }

    /*  The snapshot is two halves searched one after the other, so an address
        in both would make the answer depend on which was reached first. */
    std::set<std::string> seen;

    for (const auto* node : snapshot->all())
    {
        INFO ("address: " << node->address);
        CHECK (seen.insert (node->address).second);
    }

    CHECK (seen.size() == snapshot->size());
}

TEST_CASE ("tree: all() comes back in address order")
{
    Rig rig;
    const auto snapshot = rig.publish (0);
    const auto nodes = snapshot->all();

    REQUIRE (nodes.size() > 1);

    for (std::size_t i = 1; i < nodes.size(); ++i)
    {
        INFO ("at " << nodes[i]->address);
        CHECK (nodes[i - 1]->address < nodes[i]->address);
    }
}

//==============================================================================
TEST_CASE ("tree: the derived values come from the structure, not from the file")
{
    /*  kind, parent, index and order are `persist=none`: the document refuses
        to store them because the structure already says them, and the tree is
        what puts them back on the wire. If they were stored, this is where the
        second copy would start disagreeing. */
    Rig rig;
    const auto snapshot = rig.publish (0);

    const auto valueAt = [&snapshot] (const std::string& address)
    {
        const auto* node = snapshot->find (address);
        REQUIRE (node != nullptr);
        REQUIRE (node->value.has_value());
        return *node->value;
    };

    CHECK (valueAt (announce + "/kind") == osc::Value::string ("memo"));
    CHECK (valueAt (preshow + "/kind") == osc::Value::string ("group"));

    CHECK (valueAt (announce + "/parent") == osc::Value::string ("D9FH2JKA"));
    CHECK (valueAt (announce + "/index") == osc::Value::int32 (1));

    CHECK (valueAt (preshow + "/order") == osc::Value::string ("E4GP6QSC F7HR8TVD"));
    CHECK (valueAt (mainList + "/order") == osc::Value::string ("B3N8R5TW D9FH2JKA"));
}

TEST_CASE ("tree: a cue keeps its address when it moves, and its index changes")
{
    /*  Identity addressing, which is what makes a client's subscription and a
        Choufleur pointer survive a reorder (PRD §3.23). The cue is the same
        node at the same address; what moved is the number that says where it
        sits. */
    Rig rig;
    const auto before = rig.publish (0);

    rig.apply (1, "cli", "object.move",
               { osc::Value::string ("F7HR8TVD"), osc::Value::string ("D9FH2JKA"),
                 osc::Value::int32 (0) });

    const auto after = rig.publish (1);

    REQUIRE (after->find (announce + "/index") != nullptr);
    CHECK (*after->find (announce + "/index")->value == osc::Value::int32 (0));
    CHECK (*after->find (preshow + "/order")->value == osc::Value::string ("F7HR8TVD E4GP6QSC"));

    /*  No path appeared or disappeared: the flat /godot/cue container holds the
        same cues it did, so a listener gets value pushes and no PATH_*. */
    const auto changes = diff (*before, *after);

    CHECK (changes.added.empty());
    CHECK (changes.removed.empty());
    CHECK (! changes.valueChanged.empty());
}

//==============================================================================
TEST_CASE ("tree: a published snapshot does not change when the next tick does")
{
    /*  The property the whole design rests on. A server thread holding tick 0's
        snapshot must still see tick 0's values however long it takes to
        serialise them, with the tick thread already building tick 1. */
    Rig rig;
    const auto first = rig.publish (0);

    const auto* nameNode = first->find (announce + "/name");
    REQUIRE (nameNode != nullptr);
    CHECK (*nameNode->value == osc::Value::string ("Announce"));

    const auto nodesBefore = first->size();

    rig.apply (1, "cli", "node.set",
               { osc::Value::string (announce + "/name"), osc::Value::string ("Renamed") });
    rig.apply (2, "cli", "cue.create",
               { osc::Value::string ("7K2QM9X4"), osc::Value::int32 (0),
                 osc::Value::string ("memo"), osc::Value::string ("New") });

    const auto second = rig.publish (2);

    // The new snapshot moved on.
    CHECK (*second->find (announce + "/name")->value == osc::Value::string ("Renamed"));
    CHECK (second->size() > nodesBefore);
    CHECK (second->tick() == 2);

    // The old one did not, and still answers with what it was published with.
    CHECK (*first->find (announce + "/name")->value == osc::Value::string ("Announce"));
    CHECK (first->size() == nodesBefore);
    CHECK (first->tick() == 0);
}

TEST_CASE ("tree: creating and deleting a cue is a path added and a path removed")
{
    Rig rig;
    const auto before = rig.publish (0);

    const auto result = rig.apply (1, "cli", "cue.create",
                                   { osc::Value::string ("7K2QM9X4"), osc::Value::int32 (0),
                                     osc::Value::string ("memo"), osc::Value::string ("Blackout"),
                                     osc::Value::string ("H5KT9WXF") });
    REQUIRE (result.applied == 1);

    const auto after = rig.publish (1);
    const auto added = diff (*before, *after);

    CHECK (added.removed.empty());
    REQUIRE (! added.added.empty());

    /*  The whole subtree appears, container and leaves, because a client that
        subscribed to /godot/cue has to be told about each address it can now
        ask for. */
    const auto mentions = [] (const std::vector<std::string>& paths, const std::string& what)
    {
        return std::find (paths.begin(), paths.end(), what) != paths.end();
    };

    CHECK (mentions (added.added, "/godot/cue/H5KT9WXF"));
    CHECK (mentions (added.added, "/godot/cue/H5KT9WXF/name"));

    // And the list's order changed, which is a value push rather than a path.
    CHECK (mentions (added.valueChanged, mainList + "/order"));

    //--------------------------------------------------------------------------
    rig.apply (2, "cli", "object.delete", { osc::Value::string ("H5KT9WXF") });
    const auto removed = diff (*after, *rig.publish (2));

    CHECK (removed.added.empty());
    CHECK (mentions (removed.removed, "/godot/cue/H5KT9WXF"));
    CHECK (mentions (removed.removed, "/godot/cue/H5KT9WXF/name"));
}

TEST_CASE ("tree: a value edit changes values and no paths")
{
    Rig rig;
    const auto before = rig.publish (0);

    rig.apply (1, "cli", "node.set",
               { osc::Value::string (announce + "/notes"), osc::Value::string ("check the mic") });

    const auto changes = diff (*before, *rig.publish (1));

    CHECK (changes.added.empty());
    CHECK (changes.removed.empty());

    /*  Exactly one node under /godot/cue moved. The engine's own counters moved
        too - the tick is one of them, and it moves on every tick by definition -
        so the claim is about the document side, which is the side an edit is
        supposed to touch. */
    std::vector<std::string> documentChanges;

    for (const auto& address : changes.valueChanged)
        if (address.rfind ("/godot/cue", 0) == 0)
            documentChanges.push_back (address);

    CHECK (documentChanges == std::vector<std::string> { announce + "/notes" });
}

//==============================================================================
TEST_CASE ("tree: the engine's own numbers are published, and are runtime only")
{
    Rig rig;

    EngineState state;
    state.version = "9.9.9";
    state.tick = 42;
    state.sampleRate = 48000;
    state.blockSize = 128;
    state.samplesPerTick = 960;
    state.lateness = 17;
    state.latenessMax = 4096;
    state.clock = "dummy";
    state.documentName = "minimal";
    state.documentDirty = true;

    const auto snapshot = rig.parameters.publish (42, state);

    const auto valueAt = [&snapshot] (const std::string& address)
    {
        const auto* node = snapshot->find (address);
        REQUIRE_MESSAGE (node != nullptr, "no node at " << address);
        REQUIRE (node->value.has_value());
        return *node->value;
    };

    CHECK (valueAt ("/godot/engine/product") == osc::Value::string ("Go.dot"));
    CHECK (valueAt ("/godot/engine/version") == osc::Value::string ("9.9.9"));
    CHECK (valueAt ("/godot/engine/tick") == osc::Value::int64 (42));
    CHECK (valueAt ("/godot/engine/sampleRate") == osc::Value::int32 (48000));
    CHECK (valueAt ("/godot/engine/samplesPerTick") == osc::Value::int32 (960));
    CHECK (valueAt ("/godot/engine/lateness") == osc::Value::int32 (17));
    CHECK (valueAt ("/godot/engine/latenessMax") == osc::Value::int32 (4096));
    CHECK (valueAt ("/godot/engine/clock") == osc::Value::string ("dummy"));
    CHECK (valueAt ("/godot/document/name") == osc::Value::string ("minimal"));
    CHECK (valueAt ("/godot/document/dirty") == osc::Value::boolean (true));

    // Every one of them is read-only: they are a meter, not a control.
    for (const auto* node : snapshot->childrenOf ("/godot/engine"))
    {
        INFO ("address: " << node->address);
        CHECK (node->access == Access::read);
    }
}

TEST_CASE ("tree: a rejected write is readable back, because OSC has no reply channel")
{
    /*  A client that writes something unacceptable gets no answer on the wire -
        OSC has none to give and the OSCQuery proposal defines none - so the
        only way it can find out is to read it back. */
    Rig rig;

    /*  `kind` is derived from the element, so a client cannot turn a cue into a
        group by writing to it. The tree publishes that node read-only, and the
        refusal has to say READ-ONLY rather than "no such address" - the address
        is not what is wrong with the request. */
    const auto result = rig.apply (1, "udp:192.168.1.7:9000", "node.set",
                                   { osc::Value::string (announce + "/kind"),
                                     osc::Value::string ("group") });

    CHECK (result.applied == 0);
    CHECK (result.rejected == 1);

    const auto snapshot = rig.publish (1);

    const auto* count = snapshot->find ("/godot/engine/errorCount");
    const auto* last = snapshot->find ("/godot/engine/lastError");

    REQUIRE (count != nullptr);
    REQUIRE (last != nullptr);
    CHECK (*count->value == osc::Value::int32 (1));

    /*  kind is derived from the element: a client cannot turn a cue into a
        group by writing to it, and the read-back says which node and why. */
    REQUIRE (last->value.has_value());
    const auto text = last->value->getString();

    INFO ("lastError: " << text);
    CHECK (text.find ("read-only") != std::string::npos);
    CHECK (text.find ("node.set") != std::string::npos);
}

TEST_CASE ("tree: node.set takes the target's own type, not always a string")
{
    Rig rig;

    // A double, sent as a double.
    CHECK (rig.apply (1, "cli", "node.set",
                      { osc::Value::string (announce + "/preWait"),
                        osc::Value::float64 (2.5) }).applied == 1);

    CHECK (*rig.publish (1)->find (announce + "/preWait")->value == osc::Value::float64 (2.5));

    // The same value sent as text lands identically: the schema decides the type.
    CHECK (rig.apply (2, "cli", "node.set",
                      { osc::Value::string (announce + "/preWait"),
                        osc::Value::string ("2.5") }).applied == 1);

    CHECK (*rig.publish (2)->find (announce + "/preWait")->value == osc::Value::float64 (2.5));

    /*  And a word still cannot get into a number. The check moved one layer in,
        to where the type is actually known; it did not go away. */
    CHECK (rig.apply (3, "cli", "node.set",
                      { osc::Value::string (announce + "/preWait"),
                        osc::Value::string ("soon") }).rejected == 1);

    // Nor a number below the row's declared minimum.
    CHECK (rig.apply (4, "cli", "node.set",
                      { osc::Value::string (announce + "/preWait"),
                        osc::Value::float64 (-1.0) }).rejected == 1);

    CHECK (*rig.publish (4)->find (announce + "/preWait")->value == osc::Value::float64 (2.5));
}

//==============================================================================
TEST_CASE ("touch: a held node stops being pushed to whoever is holding it")
{
    /*  The fader fight, in three lines. While a surface holds a node the engine
        stops telling it what that node's value is; everyone else still hears. */
    TouchTable touches;

    const std::string surface = "ws:192.168.1.20:51234";
    const std::string other = "ws:192.168.1.21:51234";
    const std::string address = "/godot/cue/B3N8R5TW/preWait";

    CHECK (shouldPush (touches, surface, address, {}));

    CHECK (touches.touch (surface, address));
    CHECK_FALSE (touches.touch (surface, address));      // already held: not an error, not new

    CHECK_FALSE (shouldPush (touches, surface, address, {}));
    CHECK (shouldPush (touches, other, address, {}));    // everyone else still hears

    // A different node is unaffected: a touch is on one address, not on a client.
    CHECK (shouldPush (touches, surface, "/godot/cue/B3N8R5TW/name", {}));

    CHECK (touches.release (surface, address));
    CHECK (shouldPush (touches, surface, address, {}));
}

TEST_CASE ("touch: an origin is never told about a change it made itself")
{
    /*  Echo suppression, which is separate from touching and applies whether or
        not anything is held. */
    TouchTable touches;

    const std::string me = "udp:192.168.1.7:9000";
    const std::string them = "cli";
    const std::string address = "/godot/cue/B3N8R5TW/name";

    CHECK_FALSE (shouldPush (touches, me, address, me));
    CHECK (shouldPush (touches, them, address, me));

    // No origin means the engine changed it: a cue fired, a curve moved.
    CHECK (shouldPush (touches, me, address, {}));
}

TEST_CASE ("touch: a disconnect gives back everything that origin held")
{
    /*  A surface that vanished cannot release anything itself, and its touches
        would otherwise silence those nodes for a client id nobody will use
        again. */
    TouchTable touches;

    const std::string gone = "ws:192.168.1.20:51234";
    const std::string staying = "ws:192.168.1.21:51234";

    touches.touch (gone, "/godot/cue/A/x");
    touches.touch (gone, "/godot/cue/A/y");
    touches.touch (staying, "/godot/cue/A/x");

    CHECK (touches.size() == 3);
    CHECK (touches.holdersOf ("/godot/cue/A/x") == std::vector<std::string> { gone, staying });

    const auto released = touches.releaseAll (gone);

    CHECK (released == std::vector<std::string> { "/godot/cue/A/x", "/godot/cue/A/y" });
    CHECK (touches.size() == 1);
    CHECK (touches.heldBy (gone).empty());
    CHECK (touches.holdersOf ("/godot/cue/A/x") == std::vector<std::string> { staying });
}

TEST_CASE ("touch: it is a command, so a replay reproduces who was holding what")
{
    /*  PRD §3.15 admits no second path. A touch changes what the engine sends
        and to whom, so a replay that did not re-apply it would produce a
        different set of outbound messages from the session it claims to
        reproduce. */
    Rig rig;

    const std::string surface = "ws:192.168.1.20:51234";
    const auto address = announce + "/preWait";

    CHECK (rig.apply (1, surface, "node.touch", { osc::Value::string (address) }).applied == 1);
    CHECK (rig.touches.isHeld (surface, address));

    CHECK (rig.apply (2, surface, "node.release", { osc::Value::string (address) }).applied == 1);
    CHECK_FALSE (rig.touches.isHeld (surface, address));

    /*  Releasing what was never held is applied, not refused: a surface
        reconnecting after a drop has no idea what the engine thinks it holds,
        and refusing would punish exactly the client trying to get back in
        step. */
    CHECK (rig.apply (3, surface, "node.release", { osc::Value::string (address) }).applied == 1);

    // An engine-internal event has no origin, and cannot hold anything.
    CHECK (rig.apply (4, "", "node.touch", { osc::Value::string (address) }).rejected == 1);
    CHECK (rig.touches.empty());
}

//==============================================================================
TEST_CASE ("tree: commands are write-only method nodes, and node.set is not one")
{
    Rig rig;
    const auto snapshot = rig.publish (0);

    const auto* create = snapshot->find ("/godot/cmd/cue/create");
    REQUIRE (create != nullptr);

    CHECK (create->kind == Kind::event);
    CHECK (create->access == Access::write);
    CHECK (create->typeTags == "sisss");        // parent, index, kind, name, [id]
    CHECK_FALSE (create->value.has_value());    // an event has no value at a given time

    CHECK (snapshot->find ("/godot/cmd/node/touch") != nullptr);
    CHECK (snapshot->find ("/godot/cmd/node/release") != nullptr);

    /*  node.set has no /cmd node because its signature is whatever the target
        declares, and its address IS the target's. */
    CHECK (snapshot->find ("/godot/cmd/node/set") == nullptr);
}

TEST_CASE ("tree: only a state node declares a rate cap, an anticipation and a panic")
{
    /*  Those three are statements about a VALUE. A container has none and an
        event has none at any given time, so claiming them would be filling in
        a form rather than saying something - and a client reading
        `"PANIC": "park"` on cue.create would be entitled to believe it. */
    Rig rig;
    const auto snapshot = rig.publish (0);

    const auto godotKey = [&snapshot] (const std::string& address)
    {
        const auto json = OscQueryJson::describe (*snapshot, address);
        const auto at = json.find ("\"GODOT\"");
        REQUIRE (at != std::string::npos);
        return json.substr (at, json.find ('\n', at) - at);
    };

    CHECK (godotKey ("/godot/cmd/cue/create").find ("PANIC") == std::string::npos);
    CHECK (godotKey ("/godot/cue").find ("PANIC") == std::string::npos);
    CHECK (godotKey (announce + "/name").find ("PANIC") != std::string::npos);
    CHECK (godotKey (announce + "/name").find ("RATE_CAP") != std::string::npos);
}

TEST_CASE ("tree: the JSON is deterministic, and its numbers do not go through JUCE")
{
    Rig rig;
    const auto snapshot = rig.publish (0);

    // Same snapshot, same bytes: a golden would be worthless otherwise.
    CHECK (OscQueryJson::describe (*snapshot, "/godot")
             == OscQueryJson::describe (*snapshot, "/godot"));

    /*  A number a client reads out of this reply has to be the number the
        engine holds. 1.5 is exact either way; the point of the check is that
        it is spelled the way the document spells it, with no locale comma and
        no trailing zeroes. */
    const auto json = OscQueryJson::describe (*snapshot, announce + "/postWait");

    INFO (json);
    CHECK (json.find ("\"VALUE\": [1.5]") != std::string::npos);
    CHECK (json.find ("\"MIN\": 0") != std::string::npos);
    CHECK (json.find (",5") == std::string::npos);
}

TEST_CASE ("tree: an empty tree is still a tree")
{
    /*  snapshot() before the first publish returns something rather than
        nullptr, so no caller has to check. An empty tree at tick -1 is the
        honest description of an engine that has not ticked yet. */
    Engine engine;
    doc::ShowDocument document;
    ParameterTree parameters { document, engine.commands() };

    const auto empty = parameters.snapshot();

    REQUIRE (empty != nullptr);
    CHECK (empty->tick() == -1);
    CHECK (empty->size() == 0);
    CHECK (empty->find ("/godot") == nullptr);
    CHECK (OscQueryJson::describe (*empty, "/").empty());

    // And after one publish it is the published one.
    EngineState state;
    const auto first = parameters.publish (0, state);

    CHECK (parameters.snapshot() == first);
    CHECK (parameters.snapshot()->tick() == 0);
}
